### ISSUE TITLE
thefuck won't run at all

### ISSUE THREAD

**Issue by ParzivalWolfram** [nvbn/thefuck#1008]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    Won't get this far.

Your system (Debian 7, ArchLinux, Windows, etc.):

    Debian 5.3.7-1kali1 (2019-10-21) i686

How to reproduce the bug:

    Run `thefuck` on shell

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.29-py2.7.egg/thefuck/entrypoints/main.py", line 13, in <module>
    from .fix_command import fix_command  # noqa: E402
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.29-py2.7.egg/thefuck/entrypoints/fix_command.py", line 5, in <module>
    from .. import logs, types, const
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.29-py2.7.egg/thefuck/types.py", line 10, in <module>
    from .output_readers import get_output
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.29-py2.7.egg/thefuck/output_readers/__init__.py", line 2, in <module>
    from . import read_log, rerun, shell_logger
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.29-py2.7.egg/thefuck/output_readers/read_log.py", line 8, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size
```

If the bug only appears with a specific application, the output of that application and its version:

    N/A

Anything else you think is relevant:

    Occurs when installed through pip, apt or using latest release package.

**Comment by VilhelmPrytz** [comment]
Are you sure you are using python 3? I'm not sure if python 2.7 is supported, see issue https://github.com/nvbn/thefuck/issues/850

**Comment by ParzivalWolfram** [comment]
That... might be the issue, yeah. Lemme retest with Py3..
