### ISSUE TITLE
UnicodeDecodeError while using thefuck (Ubuntu)

### ISSUE THREAD

**Issue by vedantvohra1** [nvbn/thefuck#1012]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

   ```
The Fuck 3.29 using Python 3.5.2 and ZSH 5.1.1
```

Your system (Debian 7, ArchLinux, Windows, etc.):

    Ubuntu 16.0.4 LTS

How to reproduce the bug:

    Happens everytime I invoke thefuck

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

 ```
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'instant_mode': True,
 'no_colors': False,
 'num_close_matches': 3,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/home/vedantv/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Read output from log took: 0:00:00.002061
DEBUG: Total took: 0:00:00.025444
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/thefuck/entrypoints/main.py", line 26, in main
    fix_command(known_args)
  File "/usr/local/lib/python3.5/dist-packages/thefuck/entrypoints/fix_command.py", line 36, in fix_command
    command = types.Command.from_raw_script(raw_command)
  File "/usr/local/lib/python3.5/dist-packages/thefuck/types.py", line 82, in from_raw_script
    output = get_output(script, expanded)
  File "/usr/local/lib/python3.5/dist-packages/thefuck/output_readers/__init__.py", line 18, in get_output
    return read_log.get_output(script)
  File "/usr/local/lib/python3.5/dist-packages/thefuck/output_readers/read_log.py", line 96, in get_output
    lines = _get_output_lines(script, buffer)
  File "/usr/local/lib/python3.5/dist-packages/thefuck/output_readers/read_log.py", line 53, in _get_output_lines
    data = log_file.read().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 603679: invalid start byte
```

If the bug only appears with a specific application, the output of that application and its version:

    N.A

Anything else you think is relevant:

    I was using  --enable-experimental-instant-mode earlier but that didn't work so I removed the flag. This issue has been happening since then. I have tried updating ~/.zshrc and reloading the shell multiple times and it hasn't worked.

**Comment by scorphus** [comment]
```
DEBUG: Run with settings: {'alter_history': True,
'debug': True,
'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
'exclude_rules': [],
[snip]
