### ISSUE TITLE
thefuck can't excute

### ISSUE THREAD

**Issue by dueToLife** [nvbn/thefuck#1075]
Hi, I'm a newman in python and Linux. When I use the **python 3.6.9** and **Ubuntu 18.04** to run:

> `thefuck --version`

it gives me a message like

> `Traceback (most recent call last):
  File "/usr/bin/thefuck", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntoduetolife/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3258, in <module>
    @_call_aside
  File "/home/ubuntoduetolife/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/home/ubuntoduetolife/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ubuntoduetolife/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/ubuntoduetolife/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntoduetolife/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'decorator' distribution was not found and is required by thefuck
`

I have viewed many blog but still can't fix it.May someone can help me?

Sincerely thanks.

**Comment by scorphus** [comment]
Have you followed the installation instructions on https://github.com/nvbn/thefuck/wiki/Installation#ubuntu?

**Comment by dueToLife** [comment]
> 
> 
> Have you followed the installation instructions on https://github.com/nvbn/thefuck/wiki/Installation#ubuntu?

Oop! When I installed thefuck, I used `sudo apt thefuck"`rather than `sudo pip3 thefuck`. After retrying this, it works successfully.
Thanks a lot.
