### ISSUE TITLE
[Bug] Key error when running thefuck on termux

### ISSUE THREAD

**Issue by hXtreme** [nvbn/thefuck#1112]
( I will be crossposting it to termux's issues as well because I don't know if it's a problem with termux )

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    Can't run this, I get an error.

Your system (Debian 7, ArchLinux, Windows, etc.):

    Debian (Termux on Android 10, Pixel 3)

How to reproduce the bug:

    run: thefuck --version
    or alternatively,
    run: thefuck -h

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper        return cache[key]
KeyError: (('/proc',), frozenset())                     
During handling of the above exception, another exception occurred:                                             
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper        ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)                  PermissionError: [Errno 13] Permission denied: '/proc/stat'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1516, in wrapper
    return fun(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1734, in create_time
    bt = BOOT_TIME or boot_time()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1435, in boot_time
    with open_binary(path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/thefuck/entrypoints/main.py", line 11, in <module>
    from ..shells import shell  # noqa: E402
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/thefuck/shells/__init__.py", line 52, in <module>
    shell = _get_shell_from_env() or _get_shell_from_proc()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/thefuck/shells/__init__.py", line 45, in _get_shell_from_proc
    proc = proc.parent()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/__init__.py", line 561, in parent
    ctime = self.create_time()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1518, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=13945, name='thefuck')
```

If the bug only appears with a specific application, the output of that application and its version:

    (N/A)

Anything else you think is relevant:

    I'm using zsh as my shell, and my phone isn't rooted.

**Comment by edshamis** [comment]
Same thing
Here's the answer from termux side:
/proc is not readable on newer android versions, unless you are rooted. There is nothing we can do about this from termux side of things, hopefully thefuck can be patched to handle this keyerror better

Hope it's going to be fixed for the sake of fucking on termux

**Comment by scorphus** [comment]
Thing is, The Fuck tries to guess your shell by inspecting its parent process and that information lives in `/proc`. So, if your user can't access `/proc`, you must specify the shell manually. This is what you need:

```bash
eval $(TF_SHELL=bash thefuck --alias)
```

**Comment by scorphus** [comment]
Added a section to troubleshooting: https://github.com/nvbn/thefuck/wiki/Troubleshooting#usage-on-android-or-other-systems-that-forbid-access-to-proc

**Comment by edshamis** [comment]
Still doesn't work...
I used eval $(TF_SHELL=zsh thefuck --alias)

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'

**Comment by scorphus** [comment]
Please post the complete error message for:

```zsh
TF_SHELL=zsh THEFUCK_REQUIRE_CONFIRMATION=false thefuck "echoo ok"
```

**Comment by edshamis** [comment]
❯ eval $(TF_SHELL=zsh THEFUCK_REQUIRE_CONFIRMATION=false thefuck "echoo ok")                                                        Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
echo ok
ok

**Comment by scorphus** [comment]
Would be nice to see which line in `thefuck`'s source code the exception is raised at. I only see that in regards to `psutil`'s source code. Any idea why it's not there?

**Comment by edshamis** [comment]
What it could possibly be? I can check if you tell me what to do 
https://i.imgur.com/8Plb0Oa.jpg

**Comment by hXtreme** [comment]
What happens when you run:

```
THEFUCK_DEBUG=true thefuck --version
```

Back when I first encountered the error the above command was the simplest failing case.

**Comment by scorphus** [comment]
> What happens when you run:
> 
> ```
> THEFUCK_DEBUG=true thefuck --version
> ```
> 
> Back when I first encountered the error the above command was the simplest failing case.

Having the shell specified, what does it output in your case, @hXtreme? i.e.:

```
TF_SHELL=bash THEFUCK_DEBUG=true thefuck --version
```

**Comment by edshamis** [comment]
❯ eval $(TF_SHELL=zsh THEFUCK_DEBUG=true thefuck --version)       

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
The Fuck 3.31 using Python 3.10.1 and ZSH 5.8

**Comment by hXtreme** [comment]
```
TF_SHELL=bash THEFUCK_DEBUG=true thefuck --version
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
The Fuck 3.32 using Python 3.10.1 and Bash 5.1.12(1)-release
```

**Comment by scorphus** [comment]
Wait. I guess there's nothing wrong with The Fuck. What happens if you try the following?

```fish
python -c 'import psutil'
```

**Comment by scorphus** [comment]
I mean... there could be a try/except around those imports and then a flag to use `psutil` or not. But then, could the number of processes spawned by The Fuck that would potentially become zombies be something to worry about? Is all that worth implementing?

**Comment by edshamis** [comment]
> Wait. I guess there's nothing wrong with The Fuck. What happens if you try the following?
> 
> ```fish
> python -c 'import psutil'
> ```

Yeah, I get the same error

**Comment by edshamis** [comment]
There's some solution proposal on 
https://stackoverflow.com/questions/62640148/how-to-fix-psutil-import-error-permission-denied-on-linux

**Comment by scorphus** [comment]
Yeah, but should The Fuck support on such cases? I'm not quite sure. I have my reservations in regards to creating zombies and expecting the user to terminate them.

**Comment by edshamis** [comment]
@scorphus  If you use try/finally, will it help? 

An example from stackoverflow:
```python
import os,sys

sys.stderr = open(os.devnull, "w")
try:
  import psutil 
#except:
  #handle module not found 
finally:
  sys.stderr = sys.__stderr__
#This way, all exceptions which actually prevent the "import psutil" line from execution will get shown. just in case there is a real problem with psutil (i.e. dependency module missing).
```

**Comment by scorphus** [comment]
The major issue would be the zombie processes. Check this out:

https://github.com/nvbn/thefuck/blob/841e3f9e13f52747c18319b55c77ece8095df306/thefuck/output_readers/rerun.py#L10-L43

Not only a long-running process (like vim or some other that requires user input) couldn't be killed, it's PID wouldn't be displayed and the user would have to hunt them down somehow.

**Comment by edshamis** [comment]
Now I see. Thank you for the patience and great work!

**Comment by slacksystem** [comment]
> The major issue would be the zombie processes. Check this out:
> 
> https://github.com/nvbn/thefuck/blob/841e3f9e13f52747c18319b55c77ece8095df306/thefuck/output_readers/rerun.py#L10-L43
> 
> Not only a long-running process (like vim or some other that requires user input) couldn't be killed, it's PID wouldn't be displayed and the user would have to hunt them down somehow.

I'm confused. Is this suggestion unsafe? Is a different resolution in the works?

**Comment by Djspac3** [comment]
So I got `python -c 'import psutil'` to work but I'm getting this below from thefuck --version
```
_Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 2, in <module>
    from ..system import init_output
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/thefuck/system/unix.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'_
```

**Comment by Djspac3** [comment]
Do I install "distutils"

**Comment by maximnightingale** [comment]
> 所以我开始工作，但我从下面--version 得到这个`python -c 'import psutil'`
> 
> ```
> _Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/bin/thefuck", line 5, in <module>
>     from thefuck.entrypoints.main import main
>   File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 2, in <module>
>     from ..system import init_output
>   File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/thefuck/system/__init__.py", line 7, in <module>
>     from .unix import *  # noqa: F401,F403
>     ^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/thefuck/system/unix.py", line 6, in <module>
>     from distutils.spawn import find_executable
> ModuleNotFoundError: No module named 'distutils'_
> ```

I have the same problem.
