### ISSUE TITLE
error on termux

### ISSUE THREAD

**Issue by steve02081504** [nvbn/thefuck#1136]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    $ thefuck --version
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper
    return cache[key]
    KeyError: (('/proc',), frozenset())

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
    PermissionError: [Errno 13] Permission denied: '/proc/stat'
    The Fuck 3.30 using Python 3.8.6 and Generic Shell
    $

Your system (Debian 7, ArchLinux, Windows, etc.):

    termux0.94

How to reproduce the bug:

    fuck

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    Erase is delete.
    Interrupt is control-C (^C).
    $ export THEFUCK_DEBUG=true
    $ fuck
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper
    return cache[key]
    KeyError: (('/proc',), frozenset())

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
    PermissionError: [Errno 13] Permission denied: '/proc/stat'
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1733, in create_time
    bt = BOOT_TIME or boot_time()
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1434, in boot_time
    with open_binary(path) as f:
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
    PermissionError: [Errno 13] Permission denied: '/proc/stat'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/bin/fuck", line 5, in <module>
    from thefuck.entrypoints.not_configured import main
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/thefuck/entrypoints/not_configured.py", line 14, in <module>
    from ..shells import shell  # noqa: E402
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/thefuck/shells/__init__.py", line 52, in <module>
    shell = _get_shell_from_env() or _get_shell_from_proc()
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/thefuck/shells/__init__.py", line 45, in _get_shell_from_proc
    proc = proc.parent()
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/__init__.py", line 565, in parent
    ctime = self.create_time()
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/__init__.py", line 727, in create_time
    self._create_time = self._proc.create_time()
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1517, in wrapper
    raise AccessDenied(self.pid, self._name)
    psutil.AccessDenied: psutil.AccessDenied (pid=8919, name='fuck')

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

    FILL THIS IN

**Comment by xiexuan-lang** [comment]
That like you

**Comment by Kriper1111** [comment]
`/proc/stat` huh.. Is your device rooted? Have you tried `fuck`ing with `sudo` on? That seems like a cause.

**Comment by steve02081504** [comment]
> `/proc/stat` huh.. Is your device rooted? Have you tried `fuck`ing with `sudo` on? That seems like a cause.

```
$ /proc/stat
bash: /proc/stat: Permission denied
$ sudo /proc/stat
env: can't execute '/proc/stat': Permission denied
```
the stst on my phone is `r - -` for all user group
should i change it to `r - x`?

**Comment by Kriper1111** [comment]
Seems normal. Considering that this is a file, bash should give "Permission denied" if you're trying to access it. Erm.. If `cat /proc/stat` works okay, then.. It's weird..

**Comment by steve02081504** [comment]
@Kriper1111 
> Seems normal. Considering that this is a file, bash should give "Permission denied" if you're trying to access it. Erm.. If `cat /proc/stat` works okay, then.. It's weird..

i don't know why but
```
$ /proc/stat
bash: /proc/stat: Permission denied
$ sudo cat /proc/stat
/*works ok*/
```
cat stat works on sudo
but
```
$ sudo fuck
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/fuck", line 5, in <module>
    from thefuck.entrypoints.not_configured import main
ModuleNotFoundError: No module named 'thefuck'
```
?
orz
