### ISSUE TITLE
Causes shell crash on first loads

### ISSUE THREAD

**Issue by bduff9** [nvbn/thefuck#1265]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

```bash
❯ thefuck --version
The Fuck 3.32 using Python 3.10.1 and ZSH 5.8
```

Your system (Debian 7, ArchLinux, Windows, etc.):

    macOS Monterey 12.1

How to reproduce the bug:

    Open a new terminal session

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```bash
❯ thefuck
usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER] [--enable-experimental-instant-mode] [-h] [-y | -r] [-d] [command ...]
```

If the bug only appears with a specific application, the output of that application and its version:

This only appears the first time I open a new tab in iTerm.  With iTerm set to auto close tabs when the session ends, it opens, and then automatically closes after a couple of seconds.  I can open a new tab again and then it is fine.  However, if I open another tab, it fails again in the same way.  When I turn off auto close, I get this output that is crashing my shell the first time each tab is opened:

```bash
Last login: Thu Jan 13 12:57:40 on ttys010
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 13, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.10/site-packages/thefuck/entrypoints/main.py", line 38, in main
    shell_logger(known_args.shell_logger)
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.10/site-packages/thefuck/entrypoints/shell_logger.py", line 77, in shell_logger
    return_code = _spawn(os.environ['SHELL'], partial(_read, buffer))
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.10/site-packages/thefuck/entrypoints/shell_logger.py", line 51, in _spawn
    _set_pty_size(master_fd)
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.10/site-packages/thefuck/entrypoints/shell_logger.py", line 29, in _set_pty_size
    fcntl.ioctl(pty.STDOUT_FILENO, termios.TIOCGWINSZ, buf, True)
OSError: [Errno 25] Inappropriate ioctl for device
```

Anything else you think is relevant:

I see that this sounds similar to #1112, however, the errors are different as this seems to be a Python error, not a permission denied error on /proc.  I can open a new tab twice for now as a workaround but would like to know how the first time a tab is opened this fails and then works (working meaning the shell, plus thefuck command itself which seems to work fine once the shell is successfully opened).  Happy to provide whatever info or logging is needed to resolve this issue.  Thanks!

**Comment by scorphus** [comment]
Could you please share your `~/.zshrc` file with sensitive information filtered out?

**Comment by scorphus** [comment]
Instant mode is an experimental feature, I recommend disabling it. So, please change from

```bash
eval $(thefuck --alias --enable-experimental-instant-mode)
```
to
```bash
eval $(thefuck --alias)
```

Sorry for any inconvenience.

**Comment by Trongha** [comment]
> Instant mode is an experimental feature, I recommend disabling it. So, please change from
> 
> ```shell
> eval $(thefuck --alias --enable-experimental-instant-mode)
> ```
> 
> to
> 
> ```shell
> eval $(thefuck --alias)
> ```
> 
> Sorry for any inconvenience.

Many Thanks ^^
