### ISSUE TITLE
Gnome gets stuck on a login loop with pip version of thefuck

### ISSUE THREAD

**Issue by GiulioCentorame** [nvbn/thefuck#1269]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.32 using Python 3.10.2 and Bash 5.1.8(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

     Fedora 35

How to reproduce the bug:

    pip install thefuck, then add `eval $(thefuck --alias)` to .bashrc, then reboot. Gnome login should get stuck in a loop.

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    $ export THEFUCK_DEBUG=true
    $ thefuck
    usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
               [--enable-experimental-instant-mode] [-h] [-y | -r] [-d]
               [command ...]

If the bug only appears with a specific application, the output of that application and its version:

    $ gnome-shell --version
    GNOME Shell 41.3

Anything else you think is relevant:

    This happened after I switched from the dnf version to the pip version

**Comment by smuun** [comment]
Same problem on Fedora 36.  Output of journalctl:
```
May 08 08:06:51 hostname python3[1990]: detected unhandled Python exception in '/usr/bin/thefuck'
May 08 08:06:51 hostname python3[1990]: can't communicate with ABRT daemon, is it running? [Errno 2] No such file or directory
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]: Traceback (most recent call last):
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:   File "/usr/bin/thefuck", line 8, in <module>
May 08 08:06:51 hostname python3[1990]: error sending data to ABRT daemon:
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:     sys.exit(main())
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:   File "/usr/lib/python3.10/site-packages/thefuck/entrypoints/main.py", line 38, in main
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:     shell_logger(known_args.shell_logger)
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:   File "/usr/lib/python3.10/site-packages/thefuck/entrypoints/shell_logger.py", line 77, in shell_logger
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:     return_code = _spawn(os.environ['SHELL'], partial(_read, buffer))
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:   File "/usr/lib/python3.10/site-packages/thefuck/entrypoints/shell_logger.py", line 51, in _spawn
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:     _set_pty_size(master_fd)
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:   File "/usr/lib/python3.10/site-packages/thefuck/entrypoints/shell_logger.py", line 29, in _set_pty_size
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]:     fcntl.ioctl(pty.STDOUT_FILENO, termios.TIOCGWINSZ, buf, True)
May 08 08:06:51 hostname /usr/libexec/gdm-wayland-session[1990]: OSError: [Errno 25] Inappropriate ioctl for device
```
