### ISSUE TITLE
App just hangs when invoking

### ISSUE THREAD

**Issue by cquick01** [nvbn/thefuck#1372]
`thefuck` just hangs and does nothing when trying to use.

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

```
➜  ~ fuck -v
The Fuck 3.32 using Python 3.11.2 and ZSH 5.8.1
```

Your system (Debian 7, ArchLinux, Windows, etc.):

```
Ubuntu 22.04 (WSL2)
```

How to reproduce the bug:

```
➜   ~ gerp -R "test"
zsh: command not found: gerp
➜   ~ fuck
...
```

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```
➜   ~ gerp -R "test"
zsh: command not found: gerp
➜   ~ fuck -d
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'excluded_search_path_prefixes': [],
 'history_limit': None,
 'instant_mode': True,
 'no_colors': False,
 'num_close_matches': 3,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/home/cquick/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
^CDEBUG: Total took: 0:00:40.806389      <----- ^C after ~40 seconds
Traceback (most recent call last):
  File "/home/cquick/.local/bin/thefuck", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/entrypoints/main.py", line 31, in main
    fix_command(known_args)
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/entrypoints/fix_command.py", line 34, in fix_command
    raw_command = _get_raw_command(known_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/entrypoints/fix_command.py", line 21, in _get_raw_command
    executables = get_all_executables()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/utils.py", line 34, in wrapper
    memo[key] = fn(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/utils.py", line 124, in get_all_executables
    bins = [exe.name.decode('utf8') if six.PY2 else exe.name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/utils.py", line 128, in <listcomp>
    if not _safe(exe.is_dir, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cquick/.local/lib/python3.11/site-packages/thefuck/utils.py", line 117, in _safe
    return fn()
           ^^^^
  File "/home/cquick/.pyenv/versions/3.11.2/lib/python3.11/pathlib.py", line 1250, in is_dir
    return S_ISDIR(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/home/cquick/.pyenv/versions/3.11.2/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

If the bug only appears with a specific application, the output of that application and its version:

- Also hangs the same way with the `git push` example on a branch with no upstream.

Anything else you think is relevant:

- Alias looks like `eval $(thefuck --alias --enable-experimental-instant-mode)` in my `~/.oh-my-zsh/custom/custom.zsh` file.

**Comment by saccohuo** [comment]
Same error occured.

**Comment by brucecantarim** [comment]
Same issue here, similar env.

**Comment by jgregoire** [comment]
Same issue here.

`DEBUG: Total took: 0:01:37.035107`

**Comment by myudak** [comment]
SAME ISSUE PLEASE

edit: im on fish shell
