### ISSUE TITLE
The command does not work after brew install

### ISSUE THREAD

**Issue by WZRPW** [nvbn/thefuck#1395]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

 3.32

Your system (Debian 7, ArchLinux, Windows, etc.):

macOS monTerey 12.6.7

How to reproduce the bug:

   brew install thefuck

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

 ✘ abcdefg@abcefg-MacBook-Pro  ~  export THEFUCK_DEBUG=true
 abcdefg@abcdefg-MacBook-Pro  ~  thefuck -version
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/entrypoints/main.py", line 11, in <module>
    from ..shells import shell  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/shells/__init__.py", line 6, in <module>
    from psutil import Process
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 121, in <module>
    from . import _psosx as _psplatform
  File "/usr/local/lib/python3.7/site-packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/psutil/__init__.py)

If the bug only appears with a specific application, the output of that application and its version:

All I have is the following error when I type thefuck:

Last login: Tue Aug  1 08:46:57 on ttys003
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/thisUser/.config/thefuck/rules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 13, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/entrypoints/main.py", line 29, in main
    print_alias(known_args)
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/entrypoints/alias.py", line 27, in print_alias
    settings.init(known_args)
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/conf.py", line 21, in init
    self._setup_user_dir()
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/conf.py", line 64, in _setup_user_dir
    rules_dir.mkdir(parents=True)
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1120, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Users/thisUser/.config/thefuck'

Actually I do not have the path '/Users/thisUser/.config/thefuck'

 ✘ thisUser@thisUser-MacBook-Pro  ~  ll /Users/thisUser/.config
total 0

Anything else you think is relevant:

NO.

**Comment by scorphus** [comment]
You're getting a permission denied error: PermissionError: [Errno 13] Permission denied: '/Users/thisUser/.config/thefuck'. That's what you need to fix. thefuck needs permission to create such directory.

**Comment by WZRPW** [comment]
well. I made the directory to be rwx for every user (777).
I still see these:


 abcdefg@abcdefg  ~  thefuck -version
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/entrypoints/main.py", line 11, in <module>
    from ..shells import shell  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/shells/__init__.py", line 6, in <module>
    from psutil import Process
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 121, in <module>
    from . import _psosx as _psplatform
  File "/usr/local/lib/python3.7/site-packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/psutil/__init__.py)

**Comment by WZRPW** [comment]
> You're getting a permission denied error: PermissionError: [Errno 13] Permission denied: '/Users/thisUser/.config/thefuck'. That's what you need to fix. thefuck needs permission to create such directory.


well. I made the directory to be rwx (777) for every user.
I still see these:

abcdefg@abcdefg  ~  thefuck -version
Traceback (most recent call last):
File "/usr/local/bin/thefuck", line 9, in
from thefuck.entrypoints.main import main
File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/entrypoints/main.py", line 11, in
from ..shells import shell # noqa: E402
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Cellar/thefuck/3.32/libexec/lib/python3.11/site-packages/thefuck/shells/init.py", line 6, in
from psutil import Process
File "/usr/local/lib/python3.7/site-packages/psutil/init.py", line 121, in
from . import _psosx as _psplatform
File "/usr/local/lib/python3.7/site-packages/psutil/_psosx.py", line 15, in
from . import _psutil_osx as cext
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/psutil/init.py)
