### ISSUE TITLE
getting SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kj384g** [nvbn/thefuck#142]
[kj384g@zion.np.wc1 ~]$ /usr/bin/thefuck
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.30', 'console_scripts', 'thefuck')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/thefuck/main.py", line 9, in <module>
    from . import logs, conf, types
  File "/usr/lib/python2.6/site-packages/thefuck/conf.py", line 56
    for key in DEFAULT_SETTINGS.keys()
      ^
SyntaxError: invalid syntax

new to python, not sure what to check. Thanks!

**Comment by nvbn** [comment]
Only python 2.7 and 3.3+ are supported, 2.6 - not.
