### ISSUE TITLE
 ModuleNotFoundError: No module named 'distutils' related to #1434 

### ISSUE THREAD

**Issue by D4llo** [nvbn/thefuck#1444]
The issue may be related to #1434 

Opening a terminal throws:

```
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 2, in <module>
    from ..system import init_output
  File "/usr/lib/python3.12/site-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/thefuck/system/unix.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

The Fuck 3.32-8 using Python 3.12.3 and Bash 5.2.26(1)-release (note that thefuck --version throws:

```
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 2, in <module>
    from ..system import init_output
  File "/usr/lib/python3.12/site-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/thefuck/system/unix.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

Your system (Debian 7, ArchLinux, Windows, etc.):

EndeavourOS 6.8.7-arch1-2

How to reproduce the bug:

open an terminal and thats all

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

Still failed

Cheers,

**Comment by Sir-Caljerque** [comment]
yooo, same shit happens to me

**Comment by specarino** [comment]
According to [PEP 632](https://peps.python.org/pep-0632/), `distutils` has been removed from Python 3.12.

A band-aid fix for us users for now would be to follow the above report and just install the [`python-setuptools`](https://archlinux.org/packages/extra/any/python-setuptools/) package.

Edit: #1404 and/or #1247 appears to fix this, but they are still open PRs

**Comment by dantoms** [comment]
I did a little research before coming here and discovered the same fix.
It's been a while since the last commit. Hope the project isn't abandoned

**Comment by MaddyGuthridge** [comment]
I installed with `pipx`, and found that I still ended up with an error even after running `pipx inject thefuck distutils`.

```py
Traceback (most recent call last):
  File "/home/migue/.local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/home/migue/.local/pipx/venvs/thefuck/lib64/python3.12/site-packages/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/home/migue/.local/pipx/venvs/thefuck/lib64/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/home/migue/.local/pipx/venvs/thefuck/lib64/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'
```

Looks like getting thefuck to work nicely with Python 3.12 may be a little more painful than just adding a missing dependency, since I can't find any drop-in replacement for `imp` (which has been deprecated since Python 3.4, and got removed in Python 3.12, [source](https://docs.python.org/3.11/library/imp.html#module-imp)).

The easiest solution for `pipx` users is to stick to Python 3.11. For me, this was as simple as

```sh
$ sudo dnf install python3.11  # changes depending on your distro
$ pipx reinstall --python python3.11 thefuck
```

**Comment by tyush** [comment]
Same issue with me. If you use pipx but don't want to downgrade your system Python version (dangerous if tools from your distro rely on system Python), the following command installs `thefuck` into a venv with Python 3.11 while keeping the system Python untouched.

```
$ pipx install --fetch-missing-python --python "3.11" thefuck
$ thefuck --help
usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
...
$ python --version
Python 3.12.3
```

**Comment by virtualritz** [comment]
I have the same issue since I upgraded my Ubuntu from 23.10 to 24.04 today.

**Comment by McPringle** [comment]
Some here on a fresh install of Linux Mint on my new notebook. :-/

**Comment by KaKi87** [comment]
> Same issue with me. If you use pipx but don't want to downgrade your system Python version (dangerous if tools from your distro rely on system Python), the following command installs `thefuck` into a venv with Python 3.11 while keeping the system Python untouched.
> 
> ```
> $ pipx install --fetch-missing-python --python "3.11" thefuck
> $ thefuck --help
> usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
> ...
> $ python --version
> Python 3.12.3
> ```

Thank you !

I also had to uninstall `pipx` from APT (`sudo apt remove pipx`) and reinstall it with `brew` instead (`brew install pipx`) because Debian & Ubuntu repositories are too outdated for `--fetch-missing-python` & `--python` parameters to be available.

~~Packages previously installed with `pipx` didn't have to be reinstalled after the switch.~~ I thought so because `pipx list` still listed the previously installed packages, but they don't actually work, so they have to be reinstalled with `pipx install <package> --force`.

**Comment by NiziL** [comment]
Same here, rolling back on python3.11 did the trick for me. 
For `uv` users : `uv tool install --python 3.11 thefuck`

**Comment by KaKi87** [comment]
Thank you for making me discover `uv` !

**Comment by kierun** [comment]
This is still happening on Fedora 41.

The `uv` command does work. However, [Python 3.11 active support ended 1 year and 1 month ago ](https://endoflife.date/python). **Security updates will end 31 Oct 2027.** Thus, it would be good to have this issue resolved.

Since the last commit was in on the 25 Jan 2024… This worries me.

**Comment by kierun** [comment]
https://github.com/nvbn/thefuck/issues/1466

**Comment by Rope-a-dope** [comment]
Still happening on Fedora 43

**Comment by vidakris** [comment]
I just faced this after a macport upgrade, that broke the thing -- the fuck?:

```
❯❯❯ fuck
Traceback (most recent call last):
  File "/opt/local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/thefuck/entrypoints/main.py", line 2, in <module>
    from ..system import init_output
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/thefuck/system/unix.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

It seems that distutils is not a thing anymore, but replacing a line in the referred unix.py fixes the issue:

```
# from distutils.spawn import find_executable
from shutil import which as find_executable
```

**Comment by philippeflorent** [comment]
proposed solution does not work AT ALL

```
pip install python-setuptools
ERROR: Could not find a version that satisfies the requirement python-setuptools (from versions: none)
ERROR: No matching distribution found for python-setuptools
```

**Comment by KaKi87** [comment]
> proposed solution does not work AT ALL
> 
> ```
> pip install python-setuptools
> ```

NO ONE here proposed such a solution.

The proposed solutions are :

[From *tyush*](https://github.com/nvbn/thefuck/issues/1444#issuecomment-2130159120) :

> ```
> pipx install --fetch-missing-python --python "3.11" thefuck
> ```

[From *NiziL*](https://github.com/nvbn/thefuck/issues/1444#issuecomment-2503242004) :

> ```
> uv tool install --python 3.11 thefuck
> ```

And they WORK.
