### ISSUE TITLE
"imp" module removed in python 3.12

### ISSUE THREAD

**Issue by Alge** [nvbn/thefuck#1445]
**The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):**

Traceback (most recent call last):
  File "/home/alge/.local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/home/alge/.local/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/home/alge/.local/lib/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/home/alge/.local/lib/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'

(but the version is thefuck==3.32, installed via PIP. Same issue when installing via APT)
python version: 3.12.3

**Your system (Debian 7, ArchLinux, Windows, etc.):**

Ubuntu 24.04

**How to reproduce the bug:**

Install thefuck, try to run anything

**The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):**

Traceback (most recent call last):
  File "/home/alge/.local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/home/alge/.local/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/home/alge/.local/lib/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/home/alge/.local/lib/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'

**If the bug only appears with a specific application, the output of that application and its version:**

Nope, appears all the time

**Anything else you think is relevant:**

"imp" was removed in python 3.12, and can therefor not be found.

**Comment by Alge** [comment]
Sorry, duplicate of #1434
