### ISSUE TITLE
Cannot install on Ubuntu 24.04 LTS Noble Numbat

### ISSUE THREAD

**Issue by shalak** [nvbn/thefuck#1457]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

Cannot check

Your system (Debian 7, ArchLinux, Windows, etc.):

Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

How to reproduce the bug:

```
~$ thefuck --version
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/share/thefuck/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/thefuck/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/usr/share/thefuck/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'
~$ pip3 install thefuck --user
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):
```
ModuleNotFoundError: No module named 'imp'
```

Anything else you think is relevant:

I updated from Ubuntu 22 to 24 and now `thefuck` doesn't work due to missing `imp` in `python3.12.3`

**Comment by Stanton-e** [comment]
systems: Ubuntu Budgie on a desktop, Ubuntu 24.04 on a laptop
Distributor ID: Ubuntu
Description: Ubuntu 24.04 LTS
Release: 24.04
Codename: noble

any command to do with thefuck or fuck triggers this

```
$ thefuck --version
Traceback (most recent call last):
  File "/home/stan/.local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/home/stan/.local/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/home/stan/.local/lib/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/home/stan/.local/lib/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'
```


same issue as og post

**Comment by PaleFlyer** [comment]
Clean install of Nobel does the same. I can't get PIP3 to install thefuck.

Says the same error as the bottom half of the OP post.

**Comment by mortael** [comment]
Install it with pip directly from this repo: `pip install git+https://github.com/nvbn/thefuck`

As you can see is https://github.com/nvbn/thefuck/blob/master/thefuck/conf.py updated using importlib

**Comment by shalak** [comment]
```
$ pip install git+https://github.com/nvbn/thefuck
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
```

Would need to put it in virtualenv :/

**Comment by PVTejas** [comment]
I managed to install it by passing the `--break-system-packages` flag, but then it throws another error `no module named 'imp'`

**Comment by jalopez-arkeero** [comment]
I encountered the same issue when running the command:



`thefuck --version`

I received the following traceback:
 

```
Traceback (most recent call last):
  File "/home/tekylo/.local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
ModuleNotFoundError: No module named 'thefuck'
```

It seems like the module is not being found. Any insights on how to resolve this?

**Comment by PVTejas** [comment]
I had the same error. I had installed on Ubuntu 22.04 with py3.10. When I upgraded to 24.04, python also got upgraded to 3.12 and that environment did not have thefuck installed.

**Comment by Firesphere** [comment]
> Install it with pip directly from this repo: `pip install git+https://github.com/nvbn/thefuck`
> 
> As you can see is https://github.com/nvbn/thefuck/blob/master/thefuck/conf.py updated using importlib

This method, but using `pip3 install --user git+https://github.com/nvbn/thefuck` fixed it for me, for now.

**Comment by shalak** [comment]
I tried like this, no luck:

```
$ pipx install thefuck --force --include-deps 
Installing to existing venv 'thefuck'
⚠️  Note: thefuck was already on your PATH at /usr/bin/thefuck
  installed package thefuck 3.32, installed using Python 3.12.3
  These apps are now globally available
    - fuck
    - thefuck
done! ✨ 🌟 ✨
$ fuck
Traceback (most recent call last):
  File "/home/shalak/.local/bin/fuck", line 5, in <module>
    from thefuck.entrypoints.not_configured import main
  File "/home/shalak/.local/share/pipx/venvs/thefuck/lib/python3.12/site-packages/thefuck/entrypoints/not_configured.py", line 2, in <module>
    from ..system import init_output
  File "/home/shalak/.local/share/pipx/venvs/thefuck/lib/python3.12/site-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "/home/shalak/.local/share/pipx/venvs/thefuck/lib/python3.12/site-packages/thefuck/system/unix.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
$ pipx install distutils
Fatal error from pip prevented installation. Full pip output in file:
    /home/shalak/.local/state/pipx/log/cmd_2024-08-31_09.00.46_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
    ERROR: No matching distribution found for distutils

Error installing distutils.
$ pipx install setuptools

No apps associated with package setuptools or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.

```

**Comment by PVTejas** [comment]
pip3 uninstall thefuck​
pip3 install --user git+https://github.com/nvbn/thefuck --break-system-packages

Worked for me

**Comment by depoulo** [comment]
> pip3 uninstall thefuck​ pip3 install --user git+[nvbn/thefuck](https://github.com/nvbn/thefuck) --break-system-packages Worked for me

worked for me too, here without the linkifier:

```sh
pip3 install --user git+https://github.com/nvbn/thefuck --break-system-packages
```

**Comment by sid2364** [comment]
Should we really be using `--break-system-packages`? The whole point of it to not mess with the system installation of Python. It's clearly not recommended as an installation method. This seems unnecessarily dangerous...

Thoughts?

**Comment by PVTejas** [comment]
You're right. we need to be VERY careful using that option. In my opinion, it's fine in this case because:

- `thefuck` doesn't overwrite an existing system package
- `requirements.txt` specifies a version for only one package: `setup-tools`, and it is a `>=` type so it is likely fine in py3.12

Still, it's good to be clear about these reasons, so thanks for bringing it up.

**Comment by sean-abbott** [comment]
Uninstalling for now (my install via pipx was complaining about no distutils, and when I tried to install distutils in the virtuealenv it complained), but will return if it's fixed. :-)

**Comment by ylyxa** [comment]
Seems like the reason this is happening is that `distutils` was deprecated for Python 3.12. Fix for the `pipx` installed version without using `--break-system-packages`:

Navigate to the `bin` directory in thefuck's venv (usually  `~/.local/share/pipx/venvs/thefuck/bin`), then run `./python3 -m pip install setuptools`. 

Should be something similar for other versions, basically you need to install `setuptools`, which will also install `distutils`.

**Comment by sean-abbott** [comment]
Doesn't seem to work for me:
```
✦ ❯ pipx runpip thefuck list
Package    Version
---------- -------
colorama   0.4.6
decorator  5.1.1
pip        24.3.1
psutil     6.1.0
pyte       0.8.2
setuptools 75.6.0
six        1.17.0
thefuck    3.32
wcwidth    0.2.13

~ via  v20.14.0 via 💎 v3.0.0 on ☁️  (us-east-1)
✦ ❯ thefuck --help
Traceback (most recent call last):
  File "/home/sean/.local/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/home/sean/.local/pipx/venvs/thefuck/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/thefuck/lib/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/home/sean/.local/pipx/venvs/thefuck/lib/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'
```

https://discuss.python.org/t/how-do-i-migrate-from-imp/27885/9

**Comment by ylyxa** [comment]
@sean-abbott yours is a different issue. See https://github.com/nvbn/thefuck/issues/1449#issuecomment-2137634221 about fixing the use of the deprecated `imp` module.

**Comment by lygamac** [comment]
Consider using a maintained alternative instead:

- https://github.com/nvbn/thefuck/issues/1466#issuecomment-2473799114
- https://github.com/iffse/pay-respects/

**Comment by DRSDavidSoft** [comment]
Updating from Ubuntu 22 LTS to Ubuntu 24 LTS in 2025:

I installed the `imp` patched version from #1501 with **`pipx`**.

Then for the missing distutils, I ran:

```
pipx inject thefuck setuptools
```

And _et voilà_! Thefuck using latest Python 3.12 on Ubuntu 24 LTS, without touching any system packages.

```
# thefuck --version

The Fuck 3.32 using Python 3.12.3 and Bash 5.2.21(1)-release
```

The solution is a band-aid one that works for now, as `setuptools` package provides a replacement to the missing distutils, and the linked patch fixes the `imp` dependency.

As others have already stated, the long term solution is to either for the maintainer to become active again, someone else to pick up the project, or to use something else completely altogether.

---

**Update:** I applied some of the ongoing PRs into my fork to drop legacy Python 2.x support and use modern alternative dependencies. Installing now is simple as using pipx to:

```
pipx install --global git+https://github.com/DRSDavidSoft/thefuck
```

**Comment by rohitkhatri75436** [comment]
in my case i simply used "pip3 install thefuck --user --break-system-packages" and it worked perfectly

**Comment by Dapid** [comment]
On Ubuntu, installing `python3-zombie-imp` makes it work. On Fedora it is directly marked as a dependency.
