### ISSUE TITLE
 use python 3.12.5 on macOS Sonoma and cannot use the*ck as a result because the*ck depends on packages which have been removed in 3.12.5

### ISSUE THREAD

**Issue by interglobalmedia** [nvbn/thefuck#1467]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    FILL THIS IN

Your system (Debian 7, ArchLinux, Windows, etc.):

    FILL THIS IN

How to reproduce the bug:

    FILL THIS IN

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

    FILL THIS IN

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

command not found: fuck
Traceback (most recent call last):
  File "/Users/mariacam/.pyenv/versions/3.12.5/bin/thefuck", line 5, in <module>
    from thefuck.entrypoints.main import main
  File "/Users/mariacam/.pyenv/versions/3.12.5/lib/python3.12/site-packages/thefuck/entrypoints/main.py", line 8, in <module>
    from .. import logs  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/mariacam/.pyenv/versions/3.12.5/lib/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/Users/mariacam/.pyenv/versions/3.12.5/lib/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'
 ✘ mariacam@Marias-MBP  ~  fuck
Traceback (most recent call last):
  File "/Users/mariacam/.pyenv/versions/3.12.5/bin/fuck", line 5, in <module>
    from thefuck.entrypoints.not_configured import main
  File "/Users/mariacam/.pyenv/versions/3.12.5/lib/python3.12/site-packages/thefuck/entrypoints/not_configured.py", line 13, in <module>
    from .. import logs, const  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mariacam/.pyenv/versions/3.12.5/lib/python3.12/site-packages/thefuck/logs.py", line 8, in <module>
    from .conf import settings
  File "/Users/mariacam/.pyenv/versions/3.12.5/lib/python3.12/site-packages/thefuck/conf.py", line 1, in <module>
    from imp import load_source
ModuleNotFoundError: No module named 'imp'

I really wanted to be able to use this tool, but I guess I have to wait until if and when it works with Python 3.12.5 and above.

**Comment by just-MG** [comment]
I was able to circumvent this when I swapped the `thefuck/conf.py` and `thefuck/types.py` to how they look in GH-1465.
