### ISSUE TITLE
Lack of some files of thefuck

### ISSUE THREAD

**Issue by Jy-Liu** [nvbn/thefuck#157]
I downloaded the thefuck(version 1.3.2) yesterday and get the problem at the bottom.
what should I do?  Is that thefuck's problem or it's my python and pip broken?
I use brew to install my python on my Mac OSX(Yosemite)and the version of python is 2.7.6.
I have followed the two step below
```
sudo pip install thefuck
```
```
alias fuck='eval $(thefuck $(fc -ln -1))'
# You can use whatever you want as an alias, like for Mondays:
alias FUCK='fuck'
```

```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.32', 'console_scripts', 'thefuck')()
  File "/Library/Python/2.7/site-packages/thefuck/main.py", line 134, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/Library/Python/2.7/site-packages/thefuck/main.py", line 81, in get_matched_rule
    for rule in rules:
  File "/Library/Python/2.7/site-packages/thefuck/main.py", line 39, in get_rules
    loaded_rule = load_rule(rule)
  File "/Library/Python/2.7/site-packages/thefuck/main.py", line 24, in load_rule
    rule_module = load_source(rule.name[:-3], str(rule))
  File "/Library/Python/2.7/site-packages/thefuck/rules/brew_unknown_command.py", line 69, in <module>
    brew_commands += _get_brew_tap_specific_commands(brew_path_prefix)
  File "/Library/Python/2.7/site-packages/thefuck/rules/brew_unknown_command.py", line 36, in _get_brew_tap_specific_commands
    for user in _get_directory_names_only(brew_taps_path):
  File "/Library/Python/2.7/site-packages/thefuck/rules/brew_unknown_command.py", line 61, in _get_directory_names_only
    return [d for d in os.listdir(path)
OSError: [Errno 2] No such file or directory: '/usr/local/Library/Taps'
```

**Comment by nvbn** [comment]
Try to upgrade to 1.34+, probably fixed.

**Comment by Jy-Liu** [comment]
I finally found that it was the problem about path.
'/usr/local/Library/Taps'--->This folder isn't exist, so I mkdir a empty folder named:Taps and then solved.
Thank you.
