### ISSUE TITLE
TypeError: 'Process' object is not callable

### ISSUE THREAD

**Issue by ChillarAnand** [nvbn/thefuck#161]
i have installed thefuck but when i run fuck i am getting this error

```
# anand at anand-X550EA in ~ [21:23:06]
$ apt-get install vim
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

# anand at anand-X550EA in ~ [21:23:10]
$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.35', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 125, in main
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 73, in get_command
    script = shells.from_shell(script)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/shells.py", line 108, in from_shell
    return _get_shell().from_shell(command)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/shells.py", line 103, in _get_shell
    shell = Process(os.getpid()).parent().cmdline()[0]
TypeError: 'Process' object is not callable

# anand at anand-X550EA in ~ [21:23:13]
$ 
```

**Comment by underscorejho** [comment]
did you install python-dev?

**Comment by ChillarAnand** [comment]
@underscorejho  yes, i already have that.

**Comment by nvbn** [comment]
Can you post output of:
```bash
python -c 'from psutil import Process; print(Process); Process()'
```

**Comment by ChillarAnand** [comment]
@nvbn output:
```
<class 'psutil.Process'>
```

**Comment by ChillarAnand** [comment]
after upgrading issue was solved

**Comment by smaniato** [comment]
@ChillarAnand I'm getting `TypeError: 'Process' object is not callable` even after:
```
sudo apt-get update
sudo apt-get upgrade
sudo pip install thefuck --upgrade
```
What do you mean by "after upgrading" issue was solved?

@nvbn in case it helps:
```
python -c 'from psutil import Process; print(Process); Process()'
<class 'psutil.Process'>
```

Thank you both!

PS. I'm on Python 2.7.6

**Comment by ChillarAnand** [comment]
@smaniato  i tried 

    sudo pip install thefuck --upgrade

and it worked. i have no idea why it worked. version 1.35 and above seems to work.

**Comment by smaniato** [comment]
This (hopefully temporary) hack in `shells.py` (L102) will get it working:
```python
def _get_shell():
    shell = Process(os.getpid()).parent().cmdline()[0]
    return shells['bash'] # hardcode 'bash' or 'zsh'
```
This is what I get when upgrading btw:
```
$ sudo pip install thefuck --upgrade
Requirement already up-to-date: thefuck in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

**Comment by nvbn** [comment]
@smaniato, it's strange. Can you post output of this:
```bash
python -c 'from thefuck.shells import Process; print(Process); Process()'
```

**Comment by smaniato** [comment]
@nvbn 
```python
$ python -c 'from thefuck.shells import Process; print(Process); Process()'
<class 'psutil.Process'>
```

**Comment by nvbn** [comment]
@smaniato, and of:
```bash
python -c 'from thefuck import shells; import os; print(shells.Process(os.getpid()).parent().cmdline()[0])'
```

**Comment by smaniato** [comment]
@nvbn Interesting!
```python
$ python -c 'from thefuck import shells; import os; print(shells.Process(os.getpid()).parent().cmdline()[0])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'Process' object is not callable
```

**Comment by nvbn** [comment]
@smaniato, and:
```bash
python -c 'from thefuck import shells; import os; print(shells.Process(os.getpid()).parent.cmdline()[0])'
```

**Comment by smaniato** [comment]
@nvbn That gave me:
```
$ python -c 'from thefuck import shells; import os; print(shells.Process(os.getpid()).parent.cmdline()[0])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'list' object is not callable
```
I think the correct one is:
```
$ python -c 'from thefuck import shells; import os; print(shells.Process().parent.cmdline[0])'
bash
```

**Comment by nvbn** [comment]
@smaniato, yep, different `psutil` versions.

Try to upgrade to 1.40, probably fixed =)

**Comment by smaniato** [comment]
Fix confirmed. Thanks @nvbn ! Feel free to close this issue again.
