### ISSUE TITLE
Fuck, how install it?

### ISSUE THREAD

**Issue by a-x-** [nvbn/thefuck#173]
Hi, :)

openstack Ubuntu

i attempt to install thefuck, but fuck!

```sh
sudo easy_install pip
sudo pip install thefuck
```

```
...
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=221 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o

psutil/_psutil_linux.c:12: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/psutil/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9O39Xm-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/psutil
Storing complete log in /home/invntrm/.pip/pip.log
```

**Comment by a-x-** [comment]
also, i attempt with 
```sh
sudo apt-get install python-pip python-dev
sudo pip install thefuck
```
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==1.4
```

**Comment by a-x-** [comment]
:ok_hand: i uninstall pip, installed by `easy_install ` and use instruction on page https://github.com/nvbn/thefuck/wiki/Installation#ubuntu

What about make this instructions default?
