### ISSUE TITLE
Some Unicode error in Ubuntu 14.10

### ISSUE THREAD

**Issue by MAD-GooZe** [nvbn/thefuck#20]
```bash
$ apt-get update
E: Не удалось открыть файл блокировки /var/lib/apt/lists/lock - open (13: Отказано в доступе)
E: Невозможно заблокировать каталог /var/lib/apt/lists/
E: Не удалось открыть файл блокировки /var/lib/dpkg/lock - open (13: Отказано в доступе)
E: Не удалось выполнить блокировку управляющего каталога (/var/lib/dpkg/); у вас есть права суперпользователя?
$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.7', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 91, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 67, in get_matched_rule
    if rule.match(command, settings):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 41, in wrapper
    return fn(command, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/no_command.py", line 19, in match
    output = _get_output(command, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/no_command.py", line 13, in _get_output
    return result.stderr.read().decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

**Comment by Sekhmet** [comment]
Same thing here, but with `0xc4` byte.

**Comment by MarekAG** [comment]
Similar bug here but on ubuntu 14.04. System lang "polish", python version 2.7.6:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.7', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 91, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 67, in get_matched_rule
    if rule.match(command, settings):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 41, in wrapper
    return fn(command, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/no_command.py", line 19, in match
    output = _get_output(command, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/no_command.py", line 13, in _get_output
    return result.stderr.read().decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 29: ordinal not in range(128)
```

**Comment by nvbn** [comment]
Is it repeats with newest version (1.10+)?

**Comment by MarekAG** [comment]
@nvbn 
I'm on 1.9 but I manually do this https://github.com/nvbn/thefuck/commit/a84671dd3b7505d4d73f11ee9c7d057429542e24
and everything is now ok. So 1.10 should do the job (at least for me). Thanks! Good job.

**Comment by nvbn** [comment]
Cool =)
