### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by LorenzLeitner** [nvbn/thefuck#218]
```
lo@lo-laptop:~ 0 
$ apt-get install vim
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
lo@lo-laptop:~ 100 
$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.main import main
  File "/home/lo/.local/lib/python2.7/site-packages/thefuck/main.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

I am on **Ubuntu 15.04 using Python 2.7**. I installed like the Wiki suggests for Ubuntu users. I have the alias added in the bashrc.

I suspect the error lies within pip, since pip freeze gives me an error too:
```
lo@lo-laptop:~ 130 
$ pip freeze
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 299, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /tmp/tmpwJhsPG
```

**Comment by SanketDG** [comment]
Try this in the command line with sudo rights.

`pip install -U setuptools`
`pip install -U pip`

**Comment by LorenzLeitner** [comment]
Thank you it worked after those two commands and reinstalling thefuck.

Any insight on why I needed to do that?

**Comment by SanketDG** [comment]
Well, basically your `setuptools` was probably outdated, so `pip` didn't work. But I don't know why `setuptools` would be outdated in 15.04.
