### ISSUE TITLE
Install in CentOS 

### ISSUE THREAD

**Issue by roth1002** [nvbn/thefuck#244]
My OS version 6.5
 
When I upgrade to python 2.7( wget python 2.7 source with tar.bz2 and complie it and relpace /usr/bin/python link to my 2.7 bin file)

I got following message:

Traceback (most recent call last):
  File "/usr/bin/thefuck", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3074, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3060, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 645, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 946, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 833, in resolve
pkg_resources.DistributionNotFound: The 'thefuck==1.45' distribution was not found and is required by the application

Did I lose some step?

**Comment by roth1002** [comment]
I also update setuptools

**Comment by nvbn** [comment]
Probably you should reinstall thefuck:
```bash
pip uninstall thefuck
pip install thefuck
```

**Comment by roth1002** [comment]
I reinstall python 2.7 and use it compile setuptools and pip 

then done.

Thanks :)

**Comment by Prankal** [comment]
It did trick for me: In case of upgrade

yum reinstall -y python2-*
yum remove -y python2-paramiko*
yum install -y python2-paramiko*

rerun setup
