### ISSUE TITLE
thefuck can't handle non-ascii chars

### ISSUE THREAD

**Issue by maxried** [nvbn/thefuck#247]
I'm on `Darwin Gotthold.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64`, aka OSX 10.10.3. I'm using `fish` built from HEAD. 

When I try to fuck a command containing ß it fails with the follow message. My locale is

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

```
max@Gotthold ~$ ls ß                                                                                                                12:26:46
ls: ß: No such file or directory
(1) max@Gotthold ~$ fuck                                                                                                            12:26:52
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.45', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/site-packages/thefuck-1.45-py2.7.egg/thefuck/main.py", line 129, in main
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/site-packages/thefuck-1.45-py2.7.egg/thefuck/main.py", line 81, in get_command
    script = shells.from_shell(script)
  File "/usr/local/lib/python2.7/site-packages/thefuck-1.45-py2.7.egg/thefuck/shells.py", line 195, in from_shell
    return _get_shell().from_shell(command)
  File "/usr/local/lib/python2.7/site-packages/thefuck-1.45-py2.7.egg/thefuck/shells.py", line 114, in from_shell
    return self._expand_aliases(command_script)
  File "/usr/local/lib/python2.7/site-packages/thefuck-1.45-py2.7.egg/thefuck/shells.py", line 108, in _expand_aliases
    return 'fish -ic "{}"'.format(command_script.replace('"', r'\"'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 3: ordinal not in range(128)
```

**Comment by SanketDG** [comment]
:+1: for reporting this. A simple `.encode("utf8")` at the end of the `return` statement in line 108 in  `thefuck/shells.py` should fix it.

**Comment by nvbn** [comment]
Fix is a bit different =)

**Comment by SanketDG** [comment]
Are you sure mine won't work? I think I did the same thing as you did. Yours is just much more concise.

**Comment by nvbn** [comment]
@SanketDG your fix worked too, but only with 2.7. Also it mixes bytes and strings, it's a bit error prone.

**Comment by SanketDG** [comment]
I am pretty sure `encode` works in python 3.

**Comment by nvbn** [comment]
@SanketDG `.encode` works in python 3, but I meant this - https://travis-ci.org/nvbn/thefuck/builds/65711118

**Comment by SanketDG** [comment]
Oh, I see. Yeah that never worked.

**Comment by nvbn** [comment]
@SanketDG, and also the problem with bytes in python 3:

```python
In [1]: cmd = 'ls -la'

In [2]: cmd_bytes = cmd.encode('utf-8')

In [3]: cmd_bytes.replace('-la', '-lah')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-1363ba948de3> in <module>()
----> 1 cmd_bytes.replace('-la', '-lah')

TypeError: 'str' does not support the buffer interface
```

So when `_expand_aliases` returns bytes, a rule, which uses `.replace`, will be broken.

**Comment by SanketDG** [comment]
Ah! I learnt something new. Python 3's encoding is all about bytes! Thanks.

But sill, python 3 baffles me. :disappointed:
