### ISSUE TITLE
Fuck got stuck

### ISSUE THREAD

**Issue by vdidonato** [nvbn/thefuck#255]
I was running something like:
      tar -C /usr/local -xzf ....
and then I typed fuck and I got:

    Traceback (most recent call last):
    File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
    File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 129, in main
    command = get_command(settings, sys.argv)
    File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 84, in get_command
    if wait_output(settings, result):
    File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 65, in wait_output
    for child in proc.get_children(recursive=True):
    AttributeError: 'Process' object has no attribute 'get_children'

**Comment by scorphus** [comment]
Thanks for reporting, @vdidonato!

**Comment by scorphus** [comment]
Not too late to mention, I guess... in the meantime this can be fixed with:

```bash
$ pip install -U "psutil<3"
```
