### ISSUE TITLE
ImportError: No module named psutil

### ISSUE THREAD

**Issue by polybuildr** [nvbn/thefuck#268]
Had to `sudo apt-get install python-psutil` to fix.

**Comment by drblue** [comment]
Just a note, on Ubuntu 14.04.4 LTS the installation succeeded but trying to run `thefuck` resulted in error about `psutil` missing. Only got it working after I ran `sudo apt-get install python-psutil` as @polybuildr suggested.

Error-msg:
```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.main import main
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 10, in <module>
    from . import logs, types
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 6, in <module>
    from psutil import Process, TimeoutExpired
ImportError: No module named psutil
```

**Comment by prasad-high-5** [comment]
I have installed psutils and trying to import psutil on SLES 12 platform, but still its shouting with no modules. Any suggestions please.


```
SLES_12:~ # rpm -qa | grep psutils
psutils-p17-1023.1.2.x86_64
SLES_12:~ #
SLES_12:~ # python -c 'import psutil'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named psutil
SLES_12:~ #
```

**Comment by Liguo-Ma** [comment]
pip install psutil works well on my pc
