### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by chatainsim** [nvbn/thefuck#273]
Hello,

I've just installed thefuck through pip.
Add the .bashrc alias then source it.

But when I use fuck, I have this error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 129, in main
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 73, in get_command
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
```

Do you know how to fix it ?

I'm using python Python 2.7.3.

Thanks

**Comment by SanketDG** [comment]
`pip install six` should do the job.

**Comment by chatainsim** [comment]
Thanks @SanketDG but six seems to be already installed : 
```
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages
```
And when trying to upgrade : 
```
Collecting six
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.1.0
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'six'. No files were found to uninstall.
Successfully installed six-1.1.0
```
But I still have the issue : 
```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 129, in main
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 73, in get_command
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
```

**Comment by SanketDG** [comment]
Probably upgrade pip and then try?
`pip install -U pip`
It's better if you install all these packages in a virtualenv.

**Comment by chatainsim** [comment]
I've already upgrade pip to the latest version : 
```
pip 7.1.0 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by scorphus** [comment]
Hey, @chatainsim. Could you please give us a little bit more info?

 * What OS are you on?
 * What's the output of:

```bash
$ which python
```

 * What's the output of:

```bash
$ which thefuck
```

 * What's the output of:

```bash
$ pip freeze | grep six
```

 * What's the output of:

```bash
$ python -c 'import six; print(six); print(six.__version__); print(six.PY2)'
```

Thanks!

**Comment by chatainsim** [comment]
Hi @scorphus 
Here are the infos:
I'm using Ubuntu 12.04.5 LTS - 3.13.0-55-generic - 64 bits
```
$ which python
/usr/bin/python
```
```
$ which thefuck
/usr/local/bin/thefuck
```
```
$ pip freeze | grep six
six==1.1.0
```
```
$ python -c 'import six; print(six); print(six.__version__); print(six.PY2)'
<module 'six' from '/usr/lib/python2.7/dist-packages/six.pyc'>
1.1.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PY2'
```

**Comment by SanketDG** [comment]
@chatainsim your `six` is pretty old. The current `six` version is 1.9.0.
Do `sudo pip install --upgrade six` to update it.

**Comment by chatainsim** [comment]
I've already tried this, I got:
```
Collecting six
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.1.0
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'six'. No files were found to uninstall.
Successfully installed six-1.1.0
```

**Comment by bugaevc** [comment]
@chatainsim Are you sure you tried with `sudo`? Btw. have you tried `sudo pip uninstall six` and then `sudo pip install six`?

**Comment by chatainsim** [comment]
@bugaevc Yes, i'm using sudo.
When I try uninstall six:
```
simon@ubuntu-server:~$ sudo pip uninstall six
[sudo] password for simon:
The directory '/home/simon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/simon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
Can't uninstall 'six'. No files were found to uninstall.
```

**Comment by SanketDG** [comment]
@chatainsim So you didnt use pip.
Then you do:

```sudo apt-get remove python-six```

Then:
```sudo pip install six```
Again, I strongly advise you to use a virtualenv. But if this works, then that's okay.

**Comment by chatainsim** [comment]
Thanks @SanketDG I'll try this.
But how can I use the virtualenv ?
What's the difference ?

**Comment by chatainsim** [comment]
Ok, so just an 
```
sudo apt-get remove python-six
```
and now it's working !
```
sudo pip install six
```
Tell me that six is already installed.

**Comment by SanketDG** [comment]
@chatainsim What is the current status.
Now you could again `sudo pip uninstall six` and then `sudo pip install six`

**Comment by chatainsim** [comment]
Nice, I'm now able to install six.
```
$ sudo pip uninstall six
Uninstalling six-1.9.0:
  /usr/local/lib/python2.7/dist-packages/six-1.9.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/six-1.9.0.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/six-1.9.0.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/six-1.9.0.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/six-1.9.0.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/six-1.9.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/six.py
  /usr/local/lib/python2.7/dist-packages/six.pyc
Proceed (y/n)? y
  Successfully uninstalled six-1.9.0
```
```
$ sudo pip install six
Collecting six
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.9.0
```
```
$ python -c 'import six; print(six); print(six.__version__); print(six.PY2)'
<module 'six' from '/usr/local/lib/python2.7/dist-packages/six.pyc'>
1.9.0
True
```

**Comment by chatainsim** [comment]
I've tried thefuck two times and only work one:
```
$ pip install --upgrade youtube-dl
Collecting youtube-dl
  Downloading youtube_dl-2015.07.07-py2.py3-none-any.whl (977kB)
    100% |ââââââââââââââââââââââââââââââââ| 978kB 200kB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2015.5.20
    Uninstalling youtube-dl-2015.5.20:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 726, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 314, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/bin/youtube-dl'
```
```
$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 129, in main
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 84, in get_command
    if wait_output(settings, result):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 65, in wait_output
    for child in proc.get_children(recursive=True):
AttributeError: 'Process' object has no attribute 'get_children'
```
```
$ apt-get update
E: Impossible d'ouvrir le fichier verrou /var/lib/apt/lists/lock - open (13: Permission non accordÃ©e)
E: Impossible de verrouiller le rÃ©pertoire /var/lib/apt/lists/
E: Impossible d'ouvrir le fichier verrou /var/lib/dpkg/lock - open (13: Permission non accordÃ©e)
E: Impossible de verrouiller le rÃ©pertoire d'administration (/var/lib/dpkg/). Avez-vous les privilÃ¨ges du superutilisateurÂ ?
```
```
$ fuck
sudo apt-get update [enter/ctrl+c]
Atteint http://ppa.launchpad.net precise Release.gpg
Atteint http://ppa.launchpad.net precise Release.gpg
Atteint http://ppa.launchpad.net precise Release.gpg
Atteint http://ppa.launchpad.net precise Release.gpg
Atteint http://ppa.launchpad.net precise Release.gpg
Atteint http://ppa.launchpad.net precise Release.gpg
Atteint http://ppa.launchpad.net precise Release
Atteint http://ppa.launchpad.net precise Release
[...]
```
