### ISSUE TITLE
UnicodeEncodeError on non-english systems

### ISSUE THREAD

**Issue by jon1012** [nvbn/thefuck#301]
When a command outputs a sequence with non-ascii characters, no fucks are given with a dirty UnicodeEncodeError followed by a grep --compact not recognized option.

Example : 

```
~$ aptget blah
La commande « aptget » est introuvable, vouliez-vous dire :
 La commande « apt-get » du paquet « apt » (main)
aptget : commande introuvable
~$ fuck
apt-get blah [enter/ctrl+c]
E: L'opération blah n'est pas valable
~$ fuck
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/main.py", line 100, in get_matched_rule
    if rule.match(command, settings):
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/rules/history.py", line 28, in match
    _history_of_exists_without_current(command)))
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/utils.py", line 109, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/rules/history.py", line 19, in _history_of_exists_without_current
    history = get_history()
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/utils.py", line 109, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/shells.py", line 267, in get_history
    return list(_get_shell().get_history())
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/shells.py", line 67, in get_history
    prepared = self._script_from_history(line)\
  File "/usr/local/lib/python2.7/dist-packages/thefuck-2.1-py2.7.egg/thefuck/shells.py", line 103, in _script_from_history
    print(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
----------------------------

No fuck given
grep : option non reconnue « --compact »
Utilisation : grep [OPTION]... MOTIF [FICHIER]...
Exécutez « grep --help » pour obtenir des renseignements complémentaires.
sync: ignorer tous les arguments
```

**Comment by nvbn** [comment]
Probably fixed in 2.2.

**Comment by Tailszefox** [comment]
Still happening in 2.4:
````
[~]$ mv Tést                                                                                                                                                                                                                                       
mv: missing destination file operand after ‘Tést’
Try 'mv --help' for more information.
[~]$ fuck                                                                                                                                                                                                                                          
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [],
 'wait_command': 15}
DEBUG: Total took: 0:00:00.204458
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 140, in main
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 91, in get_command
    result.stderr.read().decode('utf-8'))
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/logs.py", line 74, in debug_time
    debug('{} took: {}'.format(msg, datetime.now() - started), settings)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)
````

**Comment by casterx** [comment]
Still happening in 3.2:

```Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.2/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 64: ordinal not in range(128)```

**Comment by scorphus** [comment]
Thank you for reporting, I'm investigating this. I'll have time to do so more closely this weekend.

**Comment by nelson-liu** [comment]
I still have this as well:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/main.py", line 77, in 
main                                                                                                               
    fix_command()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/main.py", line 28, in 
fix_command                                                                                                        
    selected_command = select_command(corrected_commands)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/ui.py", line 106, in s
elect_command                                                                                                      
    logs.confirm_text(selector.value)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/logs.py", line 61, in 
confirm_text                                                                                                       
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 60: ordinal not in range(128)
```

**Comment by casterx** [comment]
Hello @scorphus, could you please update us on this issue? Thanks :)

**Comment by scorphus** [comment]
Hello everyone!

Sorry for being offline, I was enjoying my vacations! 

@casterx and @all: Most of the action related to this issue has taken place in #398, which has a few referenced commits. Can you please install TheFuck from master and confirm? I'll appreciate that :smiley: 

Thanks!

**Comment by scorphus** [comment]
Here is the related pull request: #411

**Comment by casterx** [comment]
Hi, it's still happening for me. I installed master branch

```
🍺  [22:58] nhattran@mbp:~ $ brew reinstall thefuck --HEAD
==> Reinstalling thefuck
==> Cloning https://github.com/nvbn/thefuck.git
Cloning into '/Library/Caches/Homebrew/thefuck--git'...
remote: Counting objects: 209, done.
remote: Compressing objects: 100% (205/205), done.
remote: Total 209 (delta 14), reused 25 (delta 1), pack-reused 0
Receiving objects: 100% (209/209), 787.93 KiB | 375.00 KiB/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
==> Checking out branch master
==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.2.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> Downloading https://pypi.python.org/packages/source/p/pathlib/pathlib-1.0.1.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> Downloading https://pypi.python.org/packages/source/p/psutil/psutil-3.2.1.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> Downloading https://pypi.python.org/packages/source/c/colorama/colorama-0.3.3.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> Downloading https://pypi.python.org/packages/source/d/decorator/decorator-4.0.2.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/HEAD/li
==> Caveats
Add the following to your .bash_profile, .bashrc or .zshrc:

  eval "$(thefuck --alias)"

For other shells, check https://github.com/nvbn/thefuck/wiki/Shell-aliases
==> Summary
🍺  /usr/local/Cellar/thefuck/HEAD: 550 files, 2.3M, built in 16 seconds
```

And tried

```
🍺  [23:02] nhattran@mbp:~ $ gi
-bash: gi: command not found
🍺  [23:02] nhattran@mbp:~ $ fu
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/HEAD/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/HEAD/libexec/lib/python2.7/site-packages/thefuck/main.py", line 79, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/HEAD/libexec/lib/python2.7/site-packages/thefuck/main.py", line 31, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/HEAD/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 83, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/Cellar/thefuck/HEAD/libexec/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 38: ordinal not in range(128)
```

Already double checked the installed revision

```
🍺  [23:02] nhattran@mbp:~ $ cd /Library/Caches/Homebrew/thefuck--git/
🍺  [23:05] nhattran@mbp:thefuck--git (master) $ git log -1
commit a0ef0efe46f7dba793839a4c16d6f16fdc51eb48
Author: Vladimir Iakovlev <nvbn.rm@gmail.com>
Date:   Wed Dec 30 00:58:30 2015 +0300

    Merge pull request #419 from mcarton/fix-unzip

    Fix the `dirty_unzip` rule
```

**Comment by scorphus** [comment]
@casterx I may be wrong but maybe your `fuck` alias is missing `PYTHONIOENCODING=utf-8`? Could you please show us how it looks like? And how does its definition look like? Thanks!

**Comment by casterx** [comment]
Could you please show me how to check that? I'm not familiar with python :P

**Comment by scorphus** [comment]
Cool! I'm glad it works! I'm not sure how you set the `PYTHONIOENCODING` variable but I do **not** encourage your to set it system-wide. Instead, set it just for thefuck script – aka its alias. Make sure you set the alias as we recommend: https://github.com/nvbn/thefuck/wiki/Shell-aliases

**Comment by taz77** [comment]
On a Mac (which this questiosn is about). Use the following in your .bash_profile:

`PYTHONIOENCODING="UTF-8"
export PYTHONIOENCODING`

**Comment by scorphus** [comment]
That shouldn't be done! Not system-wide like that, at least.

Setting it in the alias is enough. But latest changes to the aliases have broken the correct setting of `PYTHONIOENCODING` and other variables right in the alias. I'm fixing it and will soon open a pull request. This should be okay in the next release.
