### ISSUE TITLE
Permission denied: '.bash_history'

### ISSUE THREAD

**Issue by ValentinH** [nvbn/thefuck#318]
When I run fuck and type Enter to accept a suggestion, I get:
```sh
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 153, in main
    run_rule(matched_rule, command, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 127, in run_rule
    shells.put_to_history(new_command)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/shells.py", line 252, in put_to_history
    return _get_shell().put_to_history(command)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/shells.py", line 49, in put_to_history
    with open(history_file_name, 'a') as history:
IOError: [Errno 13] Permission denied: '/home/me/.bash_history'
```

What could be the cause?

**Comment by ValentinH** [comment]
Well my .bach_history file was owned by root....
