### ISSUE TITLE
Handling of simple compilation errors

### ISSUE THREAD

**Issue by SylvainDe** [nvbn/thefuck#320]
Hi
I know this is pretty far-fetched and out of this project scope but I just got this error while compiling my code `Tests_Feature/my_test_file.cpp:1925:2: error: expected ';' before 'MyClassName'` and thought "FUCK". Then I just opened the file, went to line 1925 and inserted a ';' before "MyClassName" *.
I think this error contains enough information for some automatic processing to fix the issue and I'd like to give it a try when I have a bit of spare time.

* I actually added the ';' at the end of line 1924 but it would have worked anyway.

**Comment by mcarton** [comment]
Maybe running `$EDITOR Tests_Feature/my_test_file.cpp +1925 && the_previous_command` would be enough?
(I'm actually surprised the `+line` thing works with `vi`, `vim`, `nano` and `emacs`).

**Comment by scorphus** [comment]
In the meantime – while TheFuck still makes no amendments in source code files – it's fair enough to open the file in the user's preferred editor.

**Comment by mcarton** [comment]
I'll implement that tomorrow.
I started to list some patterns:

pattern | tools | note
--- | --- | ---
`{file}:{line}:{col}: error:` | gcc, clang, rustc
`at {file} line {line}` | perl
`{file}: line {line}: ` | sh, bash
`{file}:{line}:` | zsh, ruby | unfortunately the rest of the line is not consistent through errors
`    {file}:{line}:{col}:` | cargo
`  File "{file}", line {line}` | python
`lua: {file}:{line}:` | lua
`{file} (line {line}):` | fish

Fell free to add a comment if you have other ideas of easy to identify patterns.

**Comment by SylvainDe** [comment]
Wahoo! You guys are crazy! Thanks for the quick and comprehensive answers!

**Comment by scorphus** [comment]
Nice! My addition:

pattern | tools | note
------- | ----- | ----
`at {file}:{line}:{col}` | js, node | the pattern appears many times, should take the first reference

**Comment by mcarton** [comment]
@scorphus can you give me an example of output for the tests?

**Comment by scorphus** [comment]
Absolutely!

```javascript
// fuck.js
process.argv.slice(2).forEach(function(arg) {
    conole.log(arg);
});
```

```
» node fuck.js asdf qwer
/Users/pablo/Workspace/barebones/fuck.js:2
    conole.log(arg);  // this should read console.log(arg);
    ^
ReferenceError: conole is not defined
    at /Users/pablo/Workspace/barebones/fuck.js:2:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/pablo/Workspace/barebones/fuck.js:1:85)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
