### ISSUE TITLE
Add vagrant support

### ISSUE THREAD

**Issue by Hipska** [nvbn/thefuck#322]
Could it be possible to add some support for vagrant commands? Here are some that I would love to see in `thefuck`:

``` console
$ vagrant ssh
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.
```

`fuck` would then run `vagrant up`.

``` console
$ vagrant ssh hostname
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.
```

A little more tricky, but `fuck` would then run `vagrant up hostname`.

``` console
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
..
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
..
```

`fuck` would then run `vagrant provision`.

And I probably forgot some more that I use/fuckup regularly.

**Comment by scorphus** [comment]
Yes! I already have this unfuck in my TheFuck's to-do list! I'll dig this one.

**Comment by Hipska** [comment]
Nice, do you have other _unfuck_ suggestions?

**Comment by scorphus** [comment]
Yes! *Unfuck* a fucked `make` command.

BTW, would you like to implement the `vagrant_up` rule?

**Comment by Hipska** [comment]
What has `make` to do with `vagrant`?

And I don't think that I have enough knowledge and time to create rules in python.

**Comment by scorphus** [comment]
Oh... I generalized :smile: It's just an unfuck suggestion.

Okay, I'll do it then.

**Comment by mlk** [comment]
@scorphus How far have you got? I've started work on this as well but my Python is basic at best. If you want to take over/pull in your work then let me know.

https://github.com/mlk/thefuck/tree/322_vagrant

**Comment by mlk** [comment]
re: fucking vagrant up - I'm not sure that is a good idea as (I anyway) vagrant up to just bring up an existing instance. 
`vagrant provision`
feels to me a like a deliberate command rather than a fucked command. Does that make sense? 

I can tots do it but I think it should be default to off.

**Comment by scorphus** [comment]
Hello, @milk. Haven't done much, though. But I'm really glad you took it up and it's looking good! :+1: 

I haven't tested it yet, though, but by just looking at it I'll make a couple of line comments. Later today I'll be able to look at it closer.

Thanks!

**Comment by mlk** [comment]
On vagrant provision - The more I think about this the more I think this is a bad idea as vagrant up will have succeeded. 

@scorphus Thanks for you feedback. I've pushed update.

**Comment by mlk** [comment]
Vagrant up us now merged. Any other vagranty suggestions?

**Comment by scorphus** [comment]
Thank you for your contributions, @mlk! Good job!

**Comment by mlk** [comment]
@Hipska this is now part of thefuck 2.8, does it work as you expect?

**Comment by Hipska** [comment]
Yes it did, sorry for not responding. Didn't see the mention.

It did until now, after upgrading to El Capitan. I updated homebrew and other packages as well.

```
12:42 $ vagrant ssh
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.
12:42 $ fuck
No fucks given
12:43 $ thefuck -v
thefuck 3.0
12:43 $ vagrant -v
Vagrant 1.7.4
12:43 $ brew -v
Homebrew 0.9.5 (git revision 26b6f; last commit 2015-10-05)
```

**Comment by mlk** [comment]
Sorry I don't have easy access to a Mac to test this on (Mmm... maybe I can try spinning up a Vagranted Mac later ;) ).

Could you execute 
`thefuck vagrant ssh`

for me?

Cheers

**Comment by Hipska** [comment]
This just returns: "No fucks given"

**Comment by mlk** [comment]
`THEFUCK_DEBUG=true thefuck ssh app-server-redy01`

**Comment by Hipska** [comment]
```
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x10ca49130>],
 'user_dir': PosixPath('/Users/Hipska/.thefuck'),
 'wait_command': 3}
DEBUG: Execution timed out!
DEBUG: Call: vagrant ssh; with env: {'GIT_TRACE': '1', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'LOGNAME': 'Hipska', 'USER': 'Hipska', 'XPC_SERVICE_NAME': '0', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin:/opt/X11/bin', 'HOME': '/Users/Hipska', 'DISPLAY': '/private/tmp/com.apple.launchd.2W8TJStYS8/org.macosforge.xquartz:0', 'TERM_PROGRAM': 'iTerm.app', 'LANG': 'C', 'THEFUCK_DEBUG': 'true', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'COLORFGBG': '7;0', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '1', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w0t4p0', '_': '/usr/local/bin/thefuck', 'JAVA_HOME': '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home', 'DESTINATION': '/var/folders/sr/py8zdj8x169gstw6wl608kzm0000gn/T/iTerm 2.1.1 Update', 'PYTHONPATH': '/usr/local/Cellar/thefuck/3.0/libexec/lib/python2.7/site-packages:/usr/local/Cellar/thefuck/3.0/libexec/vendor/lib/python2.7/site-packages', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.9IrOW2920N/Listeners', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.3JmS5kj0bP/Render', 'ITERM_PROFILE': 'Default', 'LC_ALL': 'C', 'TMPDIR': '/var/folders/sr/py8zdj8x169gstw6wl608kzm0000gn/T/', '__GIT_PROMPT_IGNORE_STASH': '', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/Hipska/Documents/***hidden***'}; took: 0:00:03.028214
DEBUG: Importing rule: apt_get; took: 0:00:00.000724
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000940
DEBUG: Importing rule: brew_install; took: 0:00:00.001176
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000289
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000162
DEBUG: Importing rule: cargo; took: 0:00:00.000158
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000529
DEBUG: Importing rule: cd_correction; took: 0:00:00.002050
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000488
DEBUG: Importing rule: cd_parent; took: 0:00:00.000261
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000480
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000635
DEBUG: Importing rule: cpp11; took: 0:00:00.000462
DEBUG: Importing rule: dirty_untar; took: 0:00:00.003307
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000698
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000234
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000165
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000674
DEBUG: Importing rule: dry; took: 0:00:00.000295
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000429
DEBUG: Importing rule: fix_file; took: 0:00:00.004115
DEBUG: Importing rule: git_add; took: 0:00:00.001689
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000469
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000641
DEBUG: Importing rule: git_checkout; took: 0:00:00.000495
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000540
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000414
DEBUG: Importing rule: git_not_command; took: 0:00:00.000397
DEBUG: Importing rule: git_pull; took: 0:00:00.000397
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000386
DEBUG: Importing rule: git_push; took: 0:00:00.000377
DEBUG: Importing rule: git_push_force; took: 0:00:00.000379
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000383
DEBUG: Importing rule: git_stash; took: 0:00:00.000471
DEBUG: Importing rule: go_run; took: 0:00:00.000453
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000538
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000407
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000488
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000490
DEBUG: Importing rule: history; took: 0:00:00.000258
DEBUG: Importing rule: java; took: 0:00:00.000380
DEBUG: Importing rule: javac; took: 0:00:00.000379
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000682
DEBUG: Importing rule: ls_lah; took: 0:00:00.000414
DEBUG: Importing rule: man; took: 0:00:00.000257
DEBUG: Importing rule: man_no_space; took: 0:00:00.000154
DEBUG: Importing rule: mercurial; took: 0:00:00.000392
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000542
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000592
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000426
DEBUG: Importing rule: no_command; took: 0:00:00.000437
DEBUG: Importing rule: no_such_file; took: 0:00:00.000207
DEBUG: Importing rule: open; took: 0:00:00.000906
DEBUG: Importing rule: pacman; took: 0:00:00.000639
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000296
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000544
DEBUG: Importing rule: python_command; took: 0:00:00.000434
DEBUG: Importing rule: python_execute; took: 0:00:00.000408
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000431
DEBUG: Importing rule: rm_dir; took: 0:00:00.000598
DEBUG: Importing rule: rm_root; took: 0:00:00.000565
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000707
DEBUG: Importing rule: sl_ls; took: 0:00:00.000269
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000500
DEBUG: Importing rule: sudo; took: 0:00:00.000322
DEBUG: Importing rule: switch_lang; took: 0:00:00.000195
DEBUG: Importing rule: systemctl; took: 0:00:00.000741
DEBUG: Importing rule: test.py; took: 0:00:00.000181
DEBUG: Importing rule: tmux; took: 0:00:00.000430
DEBUG: Importing rule: touch; took: 0:00:00.000381
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000380
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000419
DEBUG: Importing rule: unknown_command; took: 0:00:00.000166
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000496
DEBUG: Importing rule: whois; took: 0:00:00.000380
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000658
No fucks given
DEBUG: Total took: 0:00:03.091693
```

**Comment by mlk** [comment]
Thanks @Hipska. 

Unfortunately I was a muppet and copy & pasted the wrong thing. 

`THEFUCK_DEBUG=true thefuck vagrant ssh`

**Comment by Hipska** [comment]
Yeah, I saw that and used that actual command to get this output.

**Comment by mlk** [comment]
Cool. Thanks.

The application is unable to get the response from vagrant. To start with we should give it more time (10 seconds). 

`THEFUCK_WAIT_COMMAND=10 thefuck vagrant ssh`

**Comment by Hipska** [comment]
Yes indeed, then it works..

**Comment by mlk** [comment]
Has later releases on Mac OS fixed this or is it still broken?

**Comment by Hipska** [comment]
Hi didn't use thefuck for a while, but it seems more broken now:
```DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x109d09160>],
 'user_dir': PosixPath('/Users/Hipska/.thefuck'),
 'wait_command': 10}
DEBUG: Received stdout:
DEBUG: Received stderr: A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.

DEBUG: Call: vagrant ssh; with env: {'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'LOGNAME': 'Hipska', 'USER': 'Hipska', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin:/opt/X11/bin', 'HOME': '/Users/Hipska', 'DISPLAY': '/private/tmp/com.apple.launchd.EYEI2z8M3z/org.macosforge.xquartz:0', 'TERM_PROGRAM': 'iTerm.app', 'LANG': 'C', 'THEFUCK_DEBUG': 'true', 'TERM': 'xterm', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.1Du1TyzKyU/Render', 'COLORFGBG': '7;0', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '1', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w0t3p0', '_': '/usr/local/bin/thefuck', 'JAVA_HOME': '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home', 'XPC_SERVICE_NAME': '0', 'PYTHONPATH': '/usr/local/Cellar/thefuck/3.3/libexec/lib/python2.7/site-packages:/usr/local/Cellar/thefuck/3.3/libexec/vendor/lib/python2.7/site-packages', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.8TIf5kxaHp/Listeners', 'SHELL': '/bin/bash', 'ITERM_PROFILE': 'Default', 'LC_ALL': 'C', 'TMPDIR': '/var/folders/sr/py8zdj8x169gstw6wl608kzm0000gn/T/', 'GIT_TRACE': '1', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/Hipska'}; took: 0:00:01.395693
DEBUG: Importing rule: apt_get; took: 0:00:00.000657
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000789
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.002086
DEBUG: Importing rule: brew_install; took: 0:00:00.000673
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000171
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000086
DEBUG: Importing rule: cargo; took: 0:00:00.000087
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000482
DEBUG: Importing rule: cd_correction; took: 0:00:00.001879
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000629
DEBUG: Importing rule: cd_parent; took: 0:00:00.000074
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000363
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000619
DEBUG: Importing rule: cpp11; took: 0:00:00.000317
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001978
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000317
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000062
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000059
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000673
DEBUG: Importing rule: dry; took: 0:00:00.000061
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000317
DEBUG: Importing rule: fix_file; took: 0:00:00.003376
DEBUG: Importing rule: git_add; took: 0:00:00.000570
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000353
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000321
DEBUG: Importing rule: git_checkout; took: 0:00:00.000315
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000296
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000305
DEBUG: Importing rule: git_not_command; took: 0:00:00.000289
DEBUG: Importing rule: git_pull; took: 0:00:00.000294
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000288
DEBUG: Importing rule: git_push; took: 0:00:00.000305
DEBUG: Importing rule: git_push_force; took: 0:00:00.000335
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000318
DEBUG: Importing rule: git_stash; took: 0:00:00.000299
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000294
DEBUG: Importing rule: go_run; took: 0:00:00.000269
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000274
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000281
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000288
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000405
DEBUG: Importing rule: history; took: 0:00:00.000091
DEBUG: Importing rule: java; took: 0:00:00.000280
DEBUG: Importing rule: javac; took: 0:00:00.000305
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000492
DEBUG: Importing rule: ls_lah; took: 0:00:00.000285
DEBUG: Importing rule: man; took: 0:00:00.000289
DEBUG: Importing rule: man_no_space; took: 0:00:00.000071
DEBUG: Importing rule: mercurial; took: 0:00:00.000293
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000288
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000276
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000294
DEBUG: Importing rule: no_command; took: 0:00:00.000290
DEBUG: Importing rule: no_such_file; took: 0:00:00.000073
DEBUG: Importing rule: open; took: 0:00:00.000279
DEBUG: Importing rule: pacman; took: 0:00:00.000414
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000137
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000433
DEBUG: Importing rule: python_command; took: 0:00:00.000298
DEBUG: Importing rule: python_execute; took: 0:00:00.000448
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000084
DEBUG: Importing rule: rm_dir; took: 0:00:00.000320
DEBUG: Importing rule: rm_root; took: 0:00:00.000393
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000353
DEBUG: Importing rule: sl_ls; took: 0:00:00.000062
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000467
DEBUG: Importing rule: sudo; took: 0:00:00.000070
DEBUG: Importing rule: switch_lang; took: 0:00:00.000099
DEBUG: Importing rule: systemctl; took: 0:00:00.000517
DEBUG: Importing rule: test.py; took: 0:00:00.000057
DEBUG: Importing rule: tmux; took: 0:00:00.000288
DEBUG: Importing rule: touch; took: 0:00:00.000294
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000289
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000290
DEBUG: Importing rule: unknown_command; took: 0:00:00.000066
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000555
DEBUG: Importing rule: whois; took: 0:00:00.000416
DEBUG: Trying rule: dry; took: 0:00:00.000227
DEBUG: Trying rule: test.py; took: 0:00:00.000021
DEBUG: Trying rule: apt_get_search; took: 0:00:00.000594
DEBUG: Trying rule: apt_invalid_operation; took: 0:00:00.000215
DEBUG: Trying rule: brew_install; took: 0:00:00.000021
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000018
DEBUG: Trying rule: brew_upgrade; took: 0:00:00.000017
DEBUG: Trying rule: cargo; took: 0:00:00.000016
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000210
DEBUG: Trying rule: cd_correction; took: 0:00:00.000203
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000192
DEBUG: Trying rule: cd_parent; took: 0:00:00.000019
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000197
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000194
DEBUG: Trying rule: cpp11; took: 0:00:00.000200
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000189
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000188
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000019
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000017
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000195
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000024
DEBUG: Trying rule: fix_file; took: 0:00:00.000024
DEBUG: Trying rule: git_add; took: 0:00:00.000200
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000190
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000195
DEBUG: Trying rule: git_checkout; took: 0:00:00.000188
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000187
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000187
DEBUG: Trying rule: git_not_command; took: 0:00:00.000187
DEBUG: Trying rule: git_pull; took: 0:00:00.000187
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000186
DEBUG: Trying rule: git_push; took: 0:00:00.000186
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000193
DEBUG: Trying rule: git_stash; took: 0:00:00.000187
DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000209
DEBUG: Trying rule: go_run; took: 0:00:00.000187
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000187
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000194
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000039
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000194
DEBUG: Trying rule: java; took: 0:00:00.000228
DEBUG: Trying rule: javac; took: 0:00:00.000208
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000199
DEBUG: Trying rule: ls_lah; took: 0:00:00.000199
DEBUG: Trying rule: man; took: 0:00:00.000201
DEBUG: Trying rule: mercurial; took: 0:00:00.000191
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000021
DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000190
DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000193
DEBUG: Trying rule: no_such_file; took: 0:00:00.001223
DEBUG: Trying rule: open; took: 0:00:00.000233
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000208
DEBUG: Trying rule: python_command; took: 0:00:00.000024
DEBUG: Trying rule: python_execute; took: 0:00:00.000199
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000019
DEBUG: Trying rule: rm_dir; took: 0:00:00.000020
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000198
DEBUG: Trying rule: sl_ls; took: 0:00:00.000019
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000194
DEBUG: Trying rule: sudo; took: 0:00:00.000099
DEBUG: Trying rule: switch_lang; took: 0:00:00.000017
DEBUG: Trying rule: systemctl; took: 0:00:00.000199
DEBUG: Trying rule: tmux; took: 0:00:00.000189
DEBUG: Trying rule: touch; took: 0:00:00.000194
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000188
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000183
DEBUG: Trying rule: unknown_command; took: 0:00:00.000974
DEBUG: Trying rule: vagrant_up; took: 0:00:00.000201
DEBUG: Trying rule: whois; took: 0:00:00.000289
DEBUG: Trying rule: man_no_space; took: 0:00:00.000025
DEBUG: Trying rule: no_command; took: 0:00:00.000022
DEBUG: Trying rule: history; took: 0:00:00.099972
DEBUG: Total took: 0:00:01.573020
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.3/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.3', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/3.3/libexec/lib/python2.7/site-packages/thefuck/main.py", line 79, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/3.3/libexec/lib/python2.7/site-packages/thefuck/main.py", line 31, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.3/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 83, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/Cellar/thefuck/3.3/libexec/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 45: ordinal not in range(128)```
The same happens for all fucks I try. Did reinstall of thefuck but that didn't help.

**Comment by nvbn** [comment]
@Hipska can you try with 3.7?

**Comment by Hipska** [comment]
Not much better here :(
```
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.7/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.7', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/3.7/libexec/lib/python2.7/site-packages/thefuck/main.py", line 80, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/3.7/libexec/lib/python2.7/site-packages/thefuck/main.py", line 32, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.7/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 78, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/Cellar/thefuck/3.7/libexec/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 45: ordinal not in range(128)
```

**Comment by mlk** [comment]
I've just tried this on a mac and it all works for me.

**Comment by Hipska** [comment]
Please, tell me what i'm doing wrong then, I still got the same stack trace. (python version not good?)

**Comment by mlk** [comment]
What is the output of `thefuck --version`?

Are you using a brew version of python or the default MacOS version? (Looks like the default MacOS version).

**Comment by Hipska** [comment]
>$ thefuck --version
The Fuck 3.7 using Python 2.7.10

Yes, I think it's the default, as I'm not doing anything specific with python.
>$ which python
/usr/bin/python

**Comment by nvbn** [comment]
@Hipska, does it repeats with latest version?

**Comment by Hipska** [comment]
It works fine when doing `vagrant ssh` and afterwards `fuck`, but when I run that debug command or just `thefuck vagrant ssh` I still get that stack trace with the **UnicodeEncodeError**.

**Comment by nvbn** [comment]
@Hipska can you try with 3.5?
