### ISSUE TITLE
AttributeError with ssh_known_hosts rule

### ISSUE THREAD

**Issue by felixonmars** [nvbn/thefuck#338]
I got the following error while triggering ssh_known_hosts rule:

```
$ ssh root@<removed>
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:<removed>.
Please contact your system administrator.
Add correct host key in /home/felix/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/felix/.ssh/known_hosts:870
RSA host key for <removed> has changed and you have requested strict checking.
Host key verification failed.
$ fuck
ssh root@<removed> (+side effect)
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==2.7', 'console_scripts', 'thefuck')()
  File "/usr/lib/python3.4/site-packages/thefuck/main.py", line 129, in main
    fix_command()
  File "/usr/lib/python3.4/site-packages/thefuck/main.py", line 97, in fix_command
    run_command(selected_command, settings)
  File "/usr/lib/python3.4/site-packages/thefuck/main.py", line 79, in run_command
    command.side_effect(command, settings)
  File "/usr/lib/python3.4/site-packages/thefuck/rules/ssh_known_hosts.py", line 30, in side_effect
    offending = offending_pattern.findall(command.stderr)
AttributeError: 'CorrectedCommand' object has no attribute 'stderr'
```

Any hints?

**Comment by tels7ar** [comment]
Yeah I'm seeing this too.  I'm on macos x 10.10.5 if that helps any.  Latest thefuck installed.

**Comment by felixonmars** [comment]
I have tried to downgrade openssh from 7.0p1 to 6.9p1 (which worked for me before) - and still getting the same error.
