### ISSUE TITLE
How to install thefuck 2.7?

### ISSUE THREAD

**Issue by hilen** [nvbn/thefuck#341]
```
[site-packages] sudo pip install thefuck --upgrade                                                                            10:53:45
The directory '/Users/hilenlai/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/hilenlai/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting thefuck
  Downloading thefuck-2.7-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 98kB 2.6MB/s
Requirement already up-to-date: psutil in /Library/Python/2.7/site-packages (from thefuck)
Requirement already up-to-date: six in ./six-1.9.0-py2.7.egg (from thefuck)
Requirement already up-to-date: pathlib in /Library/Python/2.7/site-packages (from thefuck)
Requirement already up-to-date: colorama in /Library/Python/2.7/site-packages (from thefuck)
Installing collected packages: thefuck
  Found existing installation: thefuck 2.6
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 683, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 512, in unique
    for item in fn(*args, **kw):
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 531, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1619, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1611, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1722, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/thefuck-2.6.dist-info/RECORD'

[site-packages]
```

I want to upgrade thefuck 2.7 , but something is wrong . How to fix it?

**Comment by nvbn** [comment]
Something strange, try:
```bash
pip uninstall thefuck
pip install thefuck
```

**Comment by hilen** [comment]
Still not work
```
[~] sudo pip uninstall thefuck                                        23:39:55
Password:
The directory '/Users/hilenlai/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/hilenlai/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 305, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 683, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 512, in unique
    for item in fn(*args, **kw):
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 531, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1619, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1611, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1722, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/thefuck-2.6.dist-info/RECORD'

```

**Comment by nvbn** [comment]
Maybe this will help:
```bash
rm -rf /Library/Python/2.7/site-packages/thefuck*
```

**Comment by hilen** [comment]
Okay, I delete the packages and install it . Thanks  :+1:
