### ISSUE TITLE
dirty_unzip rule fails when trying to remove directory

### ISSUE THREAD

**Issue by jarrodldavis** [nvbn/thefuck#363]
I was playing around with a few of the rules and it appears that `dirty_unzip` doesn't quite work. I installed using `brew install thefuck`, if that helps any.

```
Jarrods-MacBook-Pro:Downloads jarrodldavis$ unzip Archive.zip 
Archive:  Archive.zip
  inflating: LICENSE.txt             
  inflating: README.md               
   creating: ShapeEdit/
<snip>
Jarrods-MacBook-Pro:Downloads jarrodldavis$ fuck
unzip Archive.zip -d Archive (+side effect) [enter/ctrl+c]
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/2.8/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==2.8', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/2.8/libexec/lib/python2.7/site-packages/thefuck/main.py", line 135, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/2.8/libexec/lib/python2.7/site-packages/thefuck/main.py", line 103, in fix_command
    run_command(command, selected_command, settings)
  File "/usr/local/Cellar/thefuck/2.8/libexec/lib/python2.7/site-packages/thefuck/main.py", line 80, in run_command
    command.side_effect(old_cmd, command.script, settings)
  File "/usr/local/Cellar/thefuck/2.8/libexec/lib/python2.7/site-packages/thefuck/rules/dirty_unzip.py", line 36, in side_effect
    os.remove(file)
OSError: [Errno 1] Operation not permitted: 'ShapeEdit/'
```

After trying with a few more archives, it appears to be a problem with directories in general.

**Comment by mcarton** [comment]
I can't reproduce:
```bash
# mkdir a
# touch a/b a/c d
# tree
.
├── a
│   ├── b
│   └── c
└── d

1 directory, 3 files
# zip test.zip a/b a/c d
  adding: a/b (stored 0%)
  adding: a/c (stored 0%)
  adding: d (stored 0%)
# tree
.
├── a
│   ├── b
│   └── c
├── d
└── test.zip

1 directory, 4 files
# rm -r a d
# unzip test.zip
Archive:  test.zip
 extracting: a/b
 extracting: a/c
 extracting: d
# fuck
unzip test.zip -d test (+side effect) [enter/↑/↓/ctrl+c]
Archive:  test.zip
 extracting: test/a/b
 extracting: test/a/c
 extracting: test/d
# tree
.
├── a
├── test
│   ├── a
│   │   ├── b
│   │   └── c
│   └── d
└── test.zip

3 directories, 4 files
```
The empty directory `a` is left there because there is no way to know if it already existed before extraction or was created by `unzip`.

**Comment by mcarton** [comment]
It's more complicated that it seems.
When the archive contains a file `foo/bar`, we should not remove the directory `foo/` as there is no way to no if it already existed. But there does not seem to be a way to know the file to remove (ie. the file in the zip archive) is `foo/bar` without actually extracting it (listing the files in the archives only gives `foo/`).
