### ISSUE TITLE
git_fix_stash warning

### ISSUE THREAD

**Issue by michahell** [nvbn/thefuck#372]
Hi, this thing is awesome! such a great idea.

However, when invoking just ```git``` and after that ```fuck``` throws the following warning:

```bash
[WARN] Rule git_fix_stash:
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.0/libexec/lib/python2.7/site-packages/thefuck/types.py", line 211, in is_match
    if compatibility_call(self.match, command):
  File "/usr/local/Cellar/thefuck/3.0/libexec/lib/python2.7/site-packages/thefuck/utils.py", line 224, in compatibility_call
    return fn(*args)
  File "<string>", line 2, in match
  File "/usr/local/Cellar/thefuck/3.0/libexec/lib/python2.7/site-packages/thefuck/specific/git.py", line 32, in git_support
    return fn(command)
  File "/usr/local/Cellar/thefuck/3.0/libexec/lib/python2.7/site-packages/thefuck/rules/git_fix_stash.py", line 8, in match
    return (command.script.split()[1] == 'stash'
IndexError: list index out of range
----------------------------
```

**Comment by mcarton** [comment]
This has [already been fixed](https://github.com/nvbn/thefuck/issues/369). It will be in the next version.
