### ISSUE TITLE
thefuck Permission denied brand new OSX 10.10.5

### ISSUE THREAD

**Issue by michalgnacek** [nvbn/thefuck#379]
Brand new OSX 10.10.5
.zshrc
```
TF_ALIAS=fuck alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
```
ERROR
```
# michalgn at motorola.local in ~ [13:51:09]
$ pwdd   
zsh: command not found: pwdd

# michalgn at motorola.local in ~ [13:51:55]
$ fuck
pwd [enter/↑/↓/ctrl+c]
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.1/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.1', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/main.py", line 31, in fix_command
    selected_command.run(command)
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/types.py", line 270, in run
    shells.put_to_history(self.script)
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/shells.py", line 276, in put_to_history
    return _get_shell().put_to_history(command)
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/shells.py", line 49, in put_to_history
    with open(history_file_name, 'a') as history:
IOError: [Errno 13] Permission denied: '/Users/michalgn/.zsh_history'
```

**Comment by Bioto** [comment]
Try:
```
sudo chown -v $(whoami):staff ~/.zsh_history | chmod 740 ~/.zsh_history
```

That should make you the owner of ~/.zsh_history and give you full access to the file.
then run "fuck" again

**Comment by michalgnacek** [comment]
Thanks a lot, worked right away!
