### ISSUE TITLE
Bug with encoding

### ISSUE THREAD

**Issue by rakshazi** [nvbn/thefuck#396]
Hello!
Please, fix this bug.
### Problem
```
(eval):fc:1: no such event: 0
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 928-934: ordinal not in range(128)

```
### Soft
The Fuck 3.1 using Python 2.7.10
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

### Distrubive
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

### How to reproduce
Don't know. This problem was on clean OS (just installed os and tools and after that this error shows)
### Output with THEFUCK_DEBUG=TRUE
```
(eval):fc:1: no such event: 0
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x7f0fe8ade0d0>],
 'user_dir': PosixPath('/home/user/.thefuck'),
 'wait_command': 3}
```
And after that I can't enter any command (shell prompt doesn't show)

### Anything else
This problem shows only when I open new terminal window, but not when working in shell

**Comment by nvbn** [comment]
Can you post your `.zshrc`?

**Comment by rakshazi** [comment]
@nvbn here is it:
```
# General config
export LANG=en_US.UTF-8
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH"
ZSH_THEME="pygmalion"
export EDITOR='vim'
export ZSH=$HOME/.zsh
#export THEFUCK_DEBUG=true
###Disable AutoUpdate prompt
DISABLE_UPDATE_PROMPT=true
###Plugins
plugins=(copydir, copyfile, cp, git, git-prompt, git-extras, git-remote-branch, gitfast, github, gitignore, history, history-substring-search, sudo, zsh-syntax-highlighting, colored-man, colorize, extract, screen, vi-mode, mercurial, composer)

# Hotkeys
###vi style
	bindkey -v
###emacs style
#bindkey -e

# Aliases
###Console tools
	alias ls='ls --color=auto'
	alias grep='grep --colour=auto'

# Autocomplete
	autoload -U compinit promptinit
	compinit
	promptinit
###Just promt dir path to cd
	setopt autocd
###Show autocomplete menu
	zstyle ':completion:*' menu select=long-list select=0
	zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
###Correct input
	setopt CORRECT_ALL

# History
###History file
	export HISTFILE=~/.zsh_history
###Max commands saved in session
	export HISTSIZE=1000
	export SAVEHIST=$HISTSIZE
###Enable commands history
	setopt APPEND_HISTORY
###Remove duplicates, emty strings, etc.
	setopt HIST_IGNORE_ALL_DUPS
	setopt HIST_IGNORE_SPACE
	setopt HIST_REDUCE_BLANKS

# Help
	autoload -U run-help
	autoload run-help-git
	autoload run-help-svn
	autoload run-help-svk
	alias help=run-help

# Functions
### Create archive
	pk () {
		if [ $1 ] ; then
			case $1 in
				tbz)       tar cjvf $2.tar.bz2 $2      ;;
		tgz)       tar czvf $2.tar.gz  $2       ;;
		tar)      tar cpvf $2.tar  $2       ;;
		bz2)    bzip $2 ;;
		gz)        gzip -c -9 -n $2 > $2.gz ;;
		zip)       zip -r $2.zip $2   ;;
		7z)        7z a $2.7z $2    ;;
		*)         echo "'$1' cannot be packed via pk()" ;;
		esac
		else
			echo "'$1' is not a valid file"
				fi
	}

# Source Oh My Zsh
	source $ZSH/oh-my-zsh.sh
eval TF_ALIAS=fuck alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
eval alias fuck='TF_ALIAS=fuck eval $(thefuck $(fc -ln -1))'
```

**Comment by nvbn** [comment]
Try to replace:
```
eval TF_ALIAS=fuck alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
eval alias fuck='TF_ALIAS=fuck eval $(thefuck $(fc -ln -1))'
```
with:
```
eval "$(thefuck --alias)"
```

**Comment by rakshazi** [comment]
Thank you! This variant works!
pS: Please, update docs for zsh, because I got bugged variant from your wiki

**Comment by prewk** [comment]
Same error, tried `cd sr` (the correct dir name is `src`) and then `fuck`:

````
 oskar@Oskars-iMac  ~  cd sr
cd: no such file or directory: sr
 ✘ oskar@Oskars-iMac  ~  fuck
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x105026160>],
 'user_dir': PosixPath('/Users/oskar/.config/thefuck'),
 'wait_command': 3}
DEBUG: Received stdout:
DEBUG: Received stderr: /bin/sh: line 0: cd: sr: No such file or directory

DEBUG: Call: cd sr; with env: {'LESS': '-R', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'LC_CTYPE': '', 'LOGNAME': 'oskar', 'USER': 'oskar', 'PATH': '/usr/local/bin:/Users/oskar/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'HOME': '/Users/oskar', 'ZSH': '/Users/oskar/.oh-my-zsh', 'TERM_PROGRAM': 'iTerm.app', 'LANG': 'C', 'THEFUCK_DEBUG': 'TRUE', 'TERM': 'xterm-256color', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.tJ83YfY5Lr/Render', 'COLORFGBG': '12;8', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '0', 'SECURITYSESSIONID': '186a8', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w0t1p0', '_': '/usr/local/bin/thefuck', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.GmOUBAfWd3/Listeners', 'PYTHONPATH': '/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages:/usr/local/Cellar/thefuck/3.2/libexec/vendor/lib/python2.7/site-packages', 'XPC_SERVICE_NAME': '0', 'SHELL': '/bin/zsh', 'ITERM_PROFILE': 'Default', 'LC_ALL': 'C', 'TMPDIR': '/var/folders/xb/lz_hwys161b_pg3_hyckstpw0000gn/T/', 'LSCOLORS': 'Gxfxcxdxbxegedabagacad', 'GIT_TRACE': '1', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/oskar', 'PAGER': 'less'}; took: 0:00:00.002986
DEBUG: Importing rule: apt_get; took: 0:00:00.000181
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000289
DEBUG: Importing rule: brew_install; took: 0:00:00.000323
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000106
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000038
DEBUG: Importing rule: cargo; took: 0:00:00.000035
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000189
DEBUG: Importing rule: cd_correction; took: 0:00:00.000786
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000273
DEBUG: Importing rule: cd_parent; took: 0:00:00.000040
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000203
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000287
DEBUG: Importing rule: cpp11; took: 0:00:00.000183
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001115
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000204
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000051
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000050
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000310
DEBUG: Importing rule: dry; took: 0:00:00.000051
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000193
DEBUG: Importing rule: fix_file; took: 0:00:00.001827
DEBUG: Importing rule: git_add; took: 0:00:00.000343
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000202
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000190
DEBUG: Importing rule: git_checkout; took: 0:00:00.000199
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000187
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000268
DEBUG: Importing rule: git_not_command; took: 0:00:00.000211
DEBUG: Importing rule: git_pull; took: 0:00:00.000196
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000190
DEBUG: Importing rule: git_push; took: 0:00:00.000188
DEBUG: Importing rule: git_push_force; took: 0:00:00.000188
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000187
DEBUG: Importing rule: git_stash; took: 0:00:00.000184
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000188
DEBUG: Importing rule: go_run; took: 0:00:00.000169
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000176
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000187
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000178
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000174
DEBUG: Importing rule: history; took: 0:00:00.000051
DEBUG: Importing rule: java; took: 0:00:00.000153
DEBUG: Importing rule: javac; took: 0:00:00.000151
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000254
DEBUG: Importing rule: ls_lah; took: 0:00:00.000215
DEBUG: Importing rule: man; took: 0:00:00.000145
DEBUG: Importing rule: man_no_space; took: 0:00:00.000033
DEBUG: Importing rule: mercurial; took: 0:00:00.000152
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000153
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000144
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000153
DEBUG: Importing rule: no_command; took: 0:00:00.000155
DEBUG: Importing rule: no_such_file; took: 0:00:00.000038
DEBUG: Importing rule: open; took: 0:00:00.000168
DEBUG: Importing rule: pacman; took: 0:00:00.000192
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000069
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000210
DEBUG: Importing rule: python_command; took: 0:00:00.000154
DEBUG: Importing rule: python_execute; took: 0:00:00.000147
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000032
DEBUG: Importing rule: rm_dir; took: 0:00:00.000165
DEBUG: Importing rule: rm_root; took: 0:00:00.000176
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000162
DEBUG: Importing rule: sl_ls; took: 0:00:00.000030
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000160
DEBUG: Importing rule: sudo; took: 0:00:00.000035
DEBUG: Importing rule: switch_lang; took: 0:00:00.000047
DEBUG: Importing rule: systemctl; took: 0:00:00.000260
DEBUG: Importing rule: test.py; took: 0:00:00.000030
DEBUG: Importing rule: tmux; took: 0:00:00.000153
DEBUG: Importing rule: touch; took: 0:00:00.000229
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000145
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000146
DEBUG: Importing rule: unknown_command; took: 0:00:00.000034
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000156
DEBUG: Importing rule: whois; took: 0:00:00.000196
DEBUG: Trying rule: dry; took: 0:00:00.000068
DEBUG: Trying rule: test.py; took: 0:00:00.000010
DEBUG: Trying rule: apt_get_search; took: 0:00:00.000315
DEBUG: Trying rule: brew_install; took: 0:00:00.000012
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000008
DEBUG: Trying rule: brew_upgrade; took: 0:00:00.000007
DEBUG: Trying rule: cargo; took: 0:00:00.000007
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000092
DEBUG: Trying rule: cd_correction; took: 0:00:00.000094
DEBUG: Total took: 0:00:00.025918
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.2/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/Cellar/thefuck/3.2/libexec/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 56: ordinal not in range(128)
````

Using `zsh` with `eval "$(thefuck --alias)"` in my `.zshrc`.

Installed `thefuck` with `brew`: `The Fuck 3.2 using Python 2.7.10`

**Comment by CoreISP** [comment]
Experiencing the same issue all of a sudden. Not exactly sure what changed, other than maybe the brew being updated.


LvH-MBP:~ liroy$ grip
-bash: grip: command not found
LvH-MBP:~ liroy$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/lib/python2.7/site-packages/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/lib/python2.7/site-packages/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 39: ordinal not in range(128)
