### ISSUE TITLE
Error with fish shell function

### ISSUE THREAD

**Issue by simonbcn** [nvbn/thefuck#412]
```
Ubuntu 14.04 64 bits
fish shell v2.2.0
The Fuck 3.2 using Python 2.7.10

```

```
$ thefuck --alias
function fuck -d "Correct your previous console command"
    set -l exit_code $status
    set -x TF_ALIAS fuck
    set -l fucked_up_command $history[1]
    thefuck $fucked_up_command | read -l unfucked_command
    if [ "$unfucked_command" != "" ]
        eval $unfucked_command
        if test $exit_code -ne 0
            history --delete $fucked_up_command
            history --merge ^ /dev/null
            return 0
        end
    end
end
```

I have defined this fish function: 

```
function purge 
    if test (count $argv) -gt 0
        command sudo aptitude purge $argv; and command sudo aptitude clean -y
        command notify-send -h int:transient:1 -t 10000 -u normal -i system-software-update "aptitude" "Paquete purgado"
    else
        echo "Debe indicar el nombre del paquete/s a eliminar..."
    end
end

```

I execute:

```
$ purge gitbook
Couldn't find package "gitbook".  However, the following
packages contain "gitbook" in their name:
  gitbook-editor 
Couldn't find package "gitbook".  However, the following
packages contain "gitbook" in their name:
  gitbook-editor 
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/main.py", line 22, in fix_command
    command = types.Command.from_raw_script(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py", line 116, in from_raw_script
    if cls._wait_output(result):
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py", line 78, in _wait_output
    child.kill()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 299, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1089, in kill
    self._send_signal(signal.SIGKILL)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1026, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=18339)

```

**Comment by scorphus** [comment]
What does your `fuck` function look like? Please post the output of:

```fish
functions fuck
```

Where do you define your function? Can you also post its definition?

Thanks!
Em 25/11/2015 09:30, "Simón" <notifications@github.com> escreveu:

**Comment by nvbn** [comment]
Can you post result of `thefuck purge gitbook`?

**Comment by simonbcn** [comment]
I've installed it via [omf plugin](https://github.com/oh-my-fish/plugin-thefuck)
```
function fuck --description 'Correct your previous console command'
	set -l exit_code $status;    set -x TF_ALIAS fuck;    set -l fucked_up_command $history[1];    thefuck $fucked_up_command | read -l unfucked_command;    if [ "$unfucked_command" != "" ];        eval $unfucked_command;        if test $exit_code -ne 0;            history --delete $fucked_up_command;            history --merge ^ /dev/null;            return 0;        end;    end;
end
```

**Comment by simonbcn** [comment]
```
$ thefuck purge gitbook                                                                                                                         15:48
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/main.py", line 22, in fix_command
    command = types.Command.from_raw_script(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py", line 116, in from_raw_script
    if cls._wait_output(result):
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py", line 78, in _wait_output
    child.kill()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 299, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1089, in kill
    self._send_signal(signal.SIGKILL)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1026, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=21816)
```

**Comment by nvbn** [comment]
`purge` is an alias?

And also can you post result of `thefuck git bran`?

**Comment by simonbcn** [comment]
`purge` is a function (*it's in my first post*).

`thefuck git bran` works well until I press `↑` or `↓`:
```
$ thefuck git bran
git branch [enter/↑/↓/ctrl+c][WARN] Rule history:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/utils.py", line 252, in compatibility_call
    return fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/rules/history.py", line 29, in match
    _history_of_exists_without_current(command)))
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/utils.py", line 28, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/rules/history.py", line 19, in _history_of_exists_without_current
    history = get_history()
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/utils.py", line 28, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/shells.py", line 315, in get_history
    return list(_get_shell().get_history())
  File "/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/shells.py", line 68, in get_history
    prepared = self._script_from_history(line)\
AttributeError: 'Fish' object has no attribute '_script_from_history'
----------------------------

git prune [enter/↑/↓/ctrl+c]
Aborted
```

**Comment by nvbn** [comment]
Fixed in previous releases.
