### ISSUE TITLE
Traceback from running The Fuck after unzip

### ISSUE THREAD

**Issue by LoadingPleaseWait** [nvbn/thefuck#416]
After running `unzip --help`, I ran The Fuck and got the following traceback:

```
michael@rembatchlord:~$ fuck
[WARN] Rule dirty_unzip:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 237, in compatibility_call
    return fn(*args)
  File "<string>", line 2, in match
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 158, in _for_app
    return fn(command)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/dirty_unzip.py", line 28, in match
    and _is_bad_zip(_zip_file(command)))
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/dirty_unzip.py", line 8, in _is_bad_zip
    with zipfile.ZipFile(file, 'r') as archive:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python2.7/zipfile.py", line 208, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'NoneType' object has no attribute 'seek'
----------------------------

junit --help [enter/↑/↓/ctrl+c]
```

A quick way to get the stack trace would be to run `thefuck "unzip"`.

I'm using Bash on Ubuntu 15.10 Wily Werewolf. Running `thefuck --version` prints `The Fuck 3.2 using Python 2.7.10`. After setting `THEFUCK_DEBUG` to `true` and running The Fuck after `unzip --help` again, I got the following output:

```
michael@rembatchlord:~$ fuck
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x7f0265e950d0>],
 'user_dir': PosixPath('/home/michael/.config/thefuck'),
 'wait_command': 3}
DEBUG: Received stdout: UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
  -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
  -I CHARSET  specify a character encoding for UNIX and other archives

See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

DEBUG: Received stderr: 
DEBUG: Call: unzip --help; with env: {'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/michael', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'UPSTART_EVENTS': 'started starting', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'XDG_SESSION_TYPE': 'x11', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'michael', 'USER': 'michael', 'GNOME_KEYRING_CONTROL': '', 'XDG_VTNR': '7', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/db/bin:/home/michael/.wine/drive_c/users/michael/ucpp/ucpp', 'DISPLAY': ':0', 'LANG': 'C', 'THEFUCK_DEBUG': 'true', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session1', 'XAUTHORITY': '/home/michael/.Xauthority', 'LANGUAGE': 'en_US', 'SHLVL': '1', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'JOB': 'gnome-session', 'UPSTART_INSTANCE': '', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'WINDOWID': '83886090', 'CLUTTER_IM_MODULE': 'xim', 'XMODIFIERS': '@im=ibus', 'JAVA_HOME': '/usr/lib/jvm/java-8-oracle', 'HOME': '/home/michael', 'QT4_IM_MODULE': 'xim', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LC_ALL': 'C', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XDG_RUNTIME_DIR': '/run/user/1000', 'COMP_WORDBREAKS': ' \t\n"\'><;|&(:', 'SESSIONTYPE': 'gnome-session', 'VTE_VERSION': '4002', 'J2SDKDIR': '/usr/lib/jvm/java-8-oracle', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'UPSTART_JOB': 'unity-settings-daemon', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/7574', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'XDG_CURRENT_DESKTOP': 'Unity', 'XDG_SESSION_ID': 'c4', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-XbWpsnRxUD', '_': '/usr/local/bin/thefuck', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'GTK_IM_MODULE': 'ibus', 'DESKTOP_SESSION': 'ubuntu', 'GPG_AGENT_INFO': '/tmp/gpg-eRpYDR/S.gpg-agent:7697:1', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'GNOME_KEYRING_PID': '', 'GIT_TRACE': '1', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'GDM_LANG': 'en_US', 'GTK_MODULES': 'unity-gtk-module', 'INSTANCE': 'Unity', 'PWD': '/home/michael', 'DERBY_HOME': '/usr/lib/jvm/java-8-oracle/db', 'J2REDIR': '/usr/lib/jvm/java-8-oracle/jre', 'XDG_SEAT': 'seat0'}; took: 0:00:00.006405
DEBUG: Importing rule: apt_get; took: 0:00:00.000841
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000374
DEBUG: Importing rule: brew_install; took: 0:00:00.000386
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000094
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000047
DEBUG: Importing rule: cargo; took: 0:00:00.000050
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000260
DEBUG: Importing rule: cd_correction; took: 0:00:00.001167
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000439
DEBUG: Importing rule: cd_parent; took: 0:00:00.000066
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000263
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000438
DEBUG: Importing rule: cpp11; took: 0:00:00.000252
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001367
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000293
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000070
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000064
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000479
DEBUG: Importing rule: dry; took: 0:00:00.000068
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000411
DEBUG: Importing rule: fix_file; took: 0:00:00.002858
DEBUG: Importing rule: git_add; took: 0:00:00.000418
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000250
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000241
DEBUG: Importing rule: git_checkout; took: 0:00:00.000264
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000238
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000250
DEBUG: Importing rule: git_not_command; took: 0:00:00.000237
DEBUG: Importing rule: git_pull; took: 0:00:00.000233
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000288
DEBUG: Importing rule: git_push; took: 0:00:00.000287
DEBUG: Importing rule: git_push_force; took: 0:00:00.000252
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000233
DEBUG: Importing rule: git_stash; took: 0:00:00.000235
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000234
DEBUG: Importing rule: go_run; took: 0:00:00.000221
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000227
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000234
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000227
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000235
DEBUG: Importing rule: history; took: 0:00:00.000077
DEBUG: Importing rule: java; took: 0:00:00.000233
DEBUG: Importing rule: javac; took: 0:00:00.000240
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000543
DEBUG: Importing rule: ls_lah; took: 0:00:00.000203
DEBUG: Importing rule: man; took: 0:00:00.000217
DEBUG: Importing rule: man_no_space; took: 0:00:00.000059
DEBUG: Importing rule: mercurial; took: 0:00:00.000229
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000233
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000227
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000245
DEBUG: Importing rule: no_command; took: 0:00:00.000245
DEBUG: Importing rule: no_such_file; took: 0:00:00.000056
DEBUG: Importing rule: open; took: 0:00:00.000228
DEBUG: Importing rule: pacman; took: 0:00:00.000380
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000121
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000329
DEBUG: Importing rule: python_command; took: 0:00:00.000257
DEBUG: Importing rule: python_execute; took: 0:00:00.000215
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000046
DEBUG: Importing rule: rm_dir; took: 0:00:00.000227
DEBUG: Importing rule: rm_root; took: 0:00:00.000224
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000231
DEBUG: Importing rule: sl_ls; took: 0:00:00.000046
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000227
DEBUG: Importing rule: sudo; took: 0:00:00.000050
DEBUG: Importing rule: switch_lang; took: 0:00:00.000075
DEBUG: Importing rule: systemctl; took: 0:00:00.000389
DEBUG: Importing rule: test.py; took: 0:00:00.000043
DEBUG: Importing rule: tmux; took: 0:00:00.000219
DEBUG: Importing rule: touch; took: 0:00:00.000219
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000219
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000218
DEBUG: Importing rule: unknown_command; took: 0:00:00.000167
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000226
DEBUG: Importing rule: whois; took: 0:00:00.000271
DEBUG: Trying rule: dry; took: 0:00:00.000109
DEBUG: Trying rule: test.py; took: 0:00:00.000018
DEBUG: Trying rule: apt_get; took: 0:00:00.000017
DEBUG: Trying rule: apt_get_search; took: 0:00:00.000351
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000020
DEBUG: Trying rule: brew_upgrade; took: 0:00:00.000016
DEBUG: Trying rule: cargo; took: 0:00:00.000016
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000170
DEBUG: Trying rule: cd_correction; took: 0:00:00.000160
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000154
DEBUG: Trying rule: cd_parent; took: 0:00:00.000018
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000153
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000164
DEBUG: Trying rule: cpp11; took: 0:00:00.000156
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000151
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000179
[WARN] Rule dirty_unzip:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 237, in compatibility_call
    return fn(*args)
  File "<string>", line 2, in match
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 158, in _for_app
    return fn(command)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/dirty_unzip.py", line 28, in match
    and _is_bad_zip(_zip_file(command)))
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/dirty_unzip.py", line 8, in _is_bad_zip
    with zipfile.ZipFile(file, 'r') as archive:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python2.7/zipfile.py", line 208, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'NoneType' object has no attribute 'seek'
----------------------------

DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000022
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000017
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000173
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000021
DEBUG: Trying rule: fix_file; took: 0:00:00.000027
DEBUG: Trying rule: git_add; took: 0:00:00.000165
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000158
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000156
DEBUG: Trying rule: git_checkout; took: 0:00:00.000155
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000157
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000152
DEBUG: Trying rule: git_not_command; took: 0:00:00.000151
DEBUG: Trying rule: git_pull; took: 0:00:00.000151
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000153
DEBUG: Trying rule: git_push; took: 0:00:00.000150
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000149
DEBUG: Trying rule: git_stash; took: 0:00:00.000149
DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000152
DEBUG: Trying rule: go_run; took: 0:00:00.000150
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000149
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000154
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000029
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000153
DEBUG: Trying rule: java; took: 0:00:00.000151
DEBUG: Trying rule: javac; took: 0:00:00.000150
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000174
DEBUG: Trying rule: ls_lah; took: 0:00:00.000145
DEBUG: Trying rule: man; took: 0:00:00.000159
DEBUG: Trying rule: mercurial; took: 0:00:00.000143
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000019
DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000144
DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000138
DEBUG: Trying rule: no_such_file; took: 0:00:00.000846
DEBUG: Trying rule: open; took: 0:00:00.000172
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000160
DEBUG: Trying rule: python_command; took: 0:00:00.000021
DEBUG: Trying rule: python_execute; took: 0:00:00.000154
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000018
DEBUG: Trying rule: rm_dir; took: 0:00:00.000018
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000152
DEBUG: Trying rule: sl_ls; took: 0:00:00.000025
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000159
DEBUG: Trying rule: sudo; took: 0:00:00.000184
DEBUG: Trying rule: switch_lang; took: 0:00:00.000017
DEBUG: Trying rule: systemctl; took: 0:00:00.000156
DEBUG: Trying rule: tmux; took: 0:00:00.000147
DEBUG: Trying rule: touch; took: 0:00:00.000173
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000148
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000145
DEBUG: Trying rule: unknown_command; took: 0:00:00.000163
DEBUG: Trying rule: vagrant_up; took: 0:00:00.000156
DEBUG: Trying rule: whois; took: 0:00:00.000155
DEBUG: Trying rule: man_no_space; took: 0:00:00.000017
DEBUG: Trying rule: no_command; took: 0:00:00.000019
DEBUG: Trying rule: history; took: 0:00:00.633776
junit --help [enter/↑/↓/ctrl+c]
```

I was also able to reproduce this in a virtual machine running Ubuntu 14.04.3 LTS Trusty Tahr. I've attached a screenshot of that.
![thefuck](https://cloud.githubusercontent.com/assets/6393711/11919421/ebfb992e-a717-11e5-9b56-3c44938d98d5.png)

**Comment by mcarton** [comment]
Oups, my bad :sweat_smile:. I've made a PR: #419.
Anyway, thanks for the very well-detailed issue :smiley:
