### ISSUE TITLE
fuck fails to execute a command if .bash_history does not have write permissions

### ISSUE THREAD

**Issue by flutterhash** [nvbn/thefuck#428]
# Synopsis
When attempting to execute a command selected with fuck, if fuck cannot write to the .bash_history, it will throw an exception explaining that permission was denied, and fuck will **not** execute the command. fuck should always execute the command, regardless of whether it is able to modify .bash_history or not (or this should be provided as an flag, and probably enabled by default).

# Traceback
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck.real')()
  File "/usr/share/thefuck/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/share/thefuck/thefuck/main.py", line 31, in fix_command
    selected_command.run(command)
  File "/usr/share/thefuck/thefuck/types.py", line 281, in run
    shells.put_to_history(self.script)
  File "/usr/share/thefuck/thefuck/shells.py", line 293, in put_to_history
    return _get_shell().put_to_history(command)
  File "/usr/share/thefuck/thefuck/shells.py", line 51, in put_to_history
    with open(history_file_name, 'a') as history:
IOError: [Errno 13] Permission denied: '/home/REDACTED/.bash_history'

# Environment
Debian sid
thefuck (3.2-1)
python3 (3.5.0-2)

**Comment by nvbn** [comment]
In 3.3 it only shows warning when histfile is readonly. Also now `alter_history` can be used for disabling writing to histfile:
```python
alter_history = False
```
Or:
```bash
export THEFUCK_ALTER_HISTORY=false
```
