### ISSUE TITLE
Still getting "UnicodeEncodeError: 'ascii' codec can't encode character..."

### ISSUE THREAD

**Issue by Amorymeltzer** [nvbn/thefuck#433]
I thought #411 would fix this in the most recent (3.3) update, but it seems not to have.

````shell
>thefuck --version
The Fuck 3.3 using Python 2.7.11
>thefuck -a
TF_ALIAS=fuck alias fuck='PYTHONIOENCODING=utf-8 eval $(thefuck $(fc -ln -1)); history -r'
> puthon
-bash: puthon: command not found
> fuck
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/main.py", line 79, in main
    fix_command()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/main.py", line 31, in fix_command
    selected_command = select_command(corrected_commands)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/ui.py", line 83, in select_command
    logs.confirm_text(selector.value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 41: ordinal not in range(128)
````

Doing `export PYTHONIOENCODING=UTF-8` before the above as (not) suggested in #301 and #398 of course works, as does `export LC_ALL=en_US.UTF-8`.  OSX 10.9, happy to provide debug output (left it off since there's likely sufficient history here).

**Comment by scorphus** [comment]
Hello, @Amorymeltzer. I'm investigating this. I'm glad you're happy to provide debug output, please do so if you still can. Thanks a lot!

**Comment by Amorymeltzer** [comment]
Sure, it's not an issue
````shell
> export THEFUCK_DEBUG=true
> puthon
-bash: puthon: command not found
> fuck
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'no_colors': False,
 'priority': {},
 'require_confirmation': True,
 'rules': [<object object at 0x102862100>],
 'user_dir': PosixPath('/Users/Amory/.thefuck'),
 'wait_command': 3}
DEBUG: Received stdout: 
DEBUG: Received stderr: /bin/sh: puthon: command not found

DEBUG: Call: puthon; with env: {'HISTTIMEFORMAT': '[%F %T] ', 'Color_White_Bold': '\\033[1;37m', 'HOMEBREW_CASK_OPTS': '--appdir=/Applications --qlplugindir=/Library/Quicklook', 'LESS': '-FXiRgMw', 'Color_Cyan_Bold': '\\033[1;36m', 'Color_White_Intense': '\\033[0;97m', 'Color_Blue_Bold_Intense': '\\033[1;94m', 'DBUS_LAUNCHD_SESSION_BUS_SOCKET': '/tmp/launch-XkqMmB/unix_domain_listener', 'Color_Red_Bold': '\\033[1;31m', 'SHELL': '/opt/local/bin/bash', 'Color_Green_Bold_Intense': '\\033[1;92m', 'SECURITYSESSIONID': '186a4', 'HISTSIZE': '500000', 'PERL_MM_USE_DEFAULT': '1', 'MANPATH': '/opt/local/share/perl5.20/siteman:/opt/local/share/perl5.20/man:', 'Color_zBold': '\\033[1m', 'LESS_TERMCAP_ue': '\x1b[0m', 'Color_Yellow_zBackground': '\\033[43m', 'GIT_TRACE': '1', 'Color_Black_Bold': '\\033[1;30m', 'Color_White_Bold_Intense': '\\033[1;97m', 'LESS_TERMCAP_us': '\x1b[4;35m', 'Color_Green_zBackground': '\\033[42m', 'Color_Cyan_Intense': '\\033[0;96m', 'LESSOPEN': '| /opt/local/bin/lesspipe.sh %s', 'Color_Black_zBackground': '\\033[40m', 'USER': 'Amory', 'PS2': '\\[\\033[0;36m\\]\xe2\x86\x92\\[\\033[0m\\] ', 'PS3': '#? ', 'Color_Black_Bold_Intense': '\\033[1;90m', 'PS1': '\\[\\033[0;30m\\]$fill\\n\\[\\033[0;36m\\]\xe2\x94\x8c\xe2\x94\x80[\\[\\033[0;91m\\]\\u\\[\\033[0;34m\\]@\\[\\033[0;91m\\]\\h\\[\\033[0;36m\\]]-[\\[\x1b[0;95m\\]\\t Fri 15 Jan\\[\\033[0;36m\\]]-[\\[\\033[0;33m\\]-\\[\\033[0;36m\\]]-[\\[\\033[0;33m\\]\\w\\[\\033[0;36m\\]]\\n\\[\\033[0;36m\\]\xe2\x94\x94\xe2\x94\x80[\\[\\033[0;91m\\]$\\[\\033[0;36m\\]]\\[\\]->\\[\\033[0m\\] ', 'PS4': '+ ', 'Color_Magenta_Intense': '\\033[0;95m', 'THEFUCK_DEBUG': 'true', 'SHLVL': '1', 'EDITOR': 'emacs', 'Color_zInvisible': '\\033[8m', 'Color_Magenta_zBackground': '\\033[45m', 'Color_Green_Intense': '\\033[0;92m', 'Color_Blue_Bold': '\\033[1;34m', 'TERM_SESSION_ID': 'C09A2FBE-1B46-4913-9D55-502D1F64C46E', 'Color_Magenta_Bold': '\\033[1;35m', 'MANPAGER': 'less -FXiRgMw', 'Color_Yellow_Bold_Intense': '\\033[1;93m', '_': '/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/thefuck', 'Color_Red': '\\033[0;31m', 'Color_Black_Intense': '\\033[0;90m', 'PERL5DB': 'use Devel::NYTProf', 'TERM_PROGRAM_VERSION': '326', 'HOME': '/Users/Amory', 'Color_Green_Bold': '\\033[1;32m', 'TERM_PROGRAM': 'Apple_Terminal', 'LANG': 'C', 'Apple_PubSub_Socket_Render': '/tmp/launch-gt5ipy/Render', 'Color_Black': '\\033[0;30m', 'TMPDIR': '/var/folders/h7/1_b2zfh17pzbyrjy5lnm5crh0000gn/T/', 'Color_Red_Bold_Intense': '\\033[1;91m', 'Color_Cyan_zBackground': '\\033[46m', 'Color_White_zBackground': '\\033[47m', 'Color_Blue_Intense': '\\033[0;94m', 'Color_Yellow_Intense': '\\033[0;93m', 'Color_Yellow': '\\033[0;33m', '__CF_USER_TEXT_ENCODING': '0x1F5:0:0', '__CHECKFIX1436934': '1', 'Color_Blue': '\\033[0;34m', 'Color_Blue_zBackground': '\\033[44m', 'LOGNAME': 'Amory', 'PATH': '/Users/Amory/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/opt/local/libexec/perl5.22/sitebin:/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin', 'Color_Cyan': '\\033[0;36m', 'HISTCONTROL': 'ignoreboth', 'TERM': 'xterm-color', 'Color_Magenta': '\\033[0;35m', 'LESS_TERMCAP_me': '\x1b[0m', 'LESS_TERMCAP_md': '\x1b[0;34m', 'Color_Magenta_Bold_Intense': '\\033[1;95m', 'LESS_TERMCAP_mb': '\x1b[0;37m', 'GREP_COLOR': '0;35', 'Color_Yellow_Bold': '\\033[1;33m', 'HISTFILESIZE': '500000', 'Color_Green': '\\033[0;32m', 'HTML_TIDY': '/Users/Amory/.tidyrc', 'SSH_AUTH_SOCK': '/tmp/launch-lJGYgl/Listeners', 'Color_Cyan_Bold_Intense': '\\033[1;96m', 'LC_ALL': 'C', 'Color_Red_Intense': '\\033[0;91m', 'HISTIGNORE': 'ls:la:ll:lal:lla:l1:ltr:lsr:lasr:lt:l:cdl:pwd:* --help:* -h:btc:clear:exit:logout:history*:h:pg', 'Color_zOff': '\\033[0m', 'Color_White': '\\033[0;37m', 'CLICOLOR': '1', 'LESS_TERMCAP_se': '\x1b[0m', 'PWD': '/Users/Amory', 'Color_Red_zBackground': '\\033[41m', 'LESS_TERMCAP_so': '\x1b[0;31m'}; took: 0:00:00.008089
DEBUG: Importing rule: apt_get; took: 0:00:00.000797
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000660
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.003456
DEBUG: Importing rule: brew_install; took: 0:00:00.000846
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000197
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000108
DEBUG: Importing rule: cargo; took: 0:00:00.000098
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000492
DEBUG: Importing rule: cd_correction; took: 0:00:00.022676
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000910
DEBUG: Importing rule: cd_parent; took: 0:00:00.000129
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000507
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000839
DEBUG: Importing rule: cpp11; took: 0:00:00.000440
DEBUG: Importing rule: dirty_untar; took: 0:00:00.025935
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000748
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000157
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000127
DEBUG: Importing rule: docker_not_command; took: 0:00:00.001010
DEBUG: Importing rule: dry; took: 0:00:00.000161
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000661
DEBUG: Importing rule: fix_file; took: 0:00:00.017391
DEBUG: Importing rule: git_add; took: 0:00:00.001141
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000530
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000514
DEBUG: Importing rule: git_checkout; took: 0:00:00.000632
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000844
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000589
DEBUG: Importing rule: git_not_command; took: 0:00:00.000521
DEBUG: Importing rule: git_pull; took: 0:00:00.003529
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000990
DEBUG: Importing rule: git_push; took: 0:00:00.000504
DEBUG: Importing rule: git_push_force; took: 0:00:00.000465
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000437
DEBUG: Importing rule: git_stash; took: 0:00:00.000424
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000428
DEBUG: Importing rule: go_run; took: 0:00:00.000406
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000461
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000396
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000435
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000404
DEBUG: Importing rule: history; took: 0:00:00.000225
DEBUG: Importing rule: java; took: 0:00:00.000401
DEBUG: Importing rule: javac; took: 0:00:00.000377
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000698
DEBUG: Importing rule: ls_lah; took: 0:00:00.000375
DEBUG: Importing rule: man; took: 0:00:00.000388
DEBUG: Importing rule: man_no_space; took: 0:00:00.000101
DEBUG: Importing rule: mercurial; took: 0:00:00.000381
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000422
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000547
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000392
DEBUG: Importing rule: no_command; took: 0:00:00.000423
DEBUG: Importing rule: no_such_file; took: 0:00:00.000109
DEBUG: Importing rule: open; took: 0:00:00.000395
DEBUG: Importing rule: pacman; took: 0:00:00.001061
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000474
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000632
DEBUG: Importing rule: python_command; took: 0:00:00.000442
DEBUG: Importing rule: python_execute; took: 0:00:00.000379
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000095
DEBUG: Importing rule: rm_dir; took: 0:00:00.000435
DEBUG: Importing rule: rm_root; took: 0:00:00.000411
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000392
DEBUG: Importing rule: sl_ls; took: 0:00:00.000093
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000411
DEBUG: Importing rule: sudo; took: 0:00:00.000111
DEBUG: Importing rule: switch_lang; took: 0:00:00.000152
DEBUG: Importing rule: systemctl; took: 0:00:00.000733
DEBUG: Importing rule: test.py; took: 0:00:00.000117
DEBUG: Importing rule: tmux; took: 0:00:00.000401
DEBUG: Importing rule: touch; took: 0:00:00.000393
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000388
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000369
DEBUG: Importing rule: unknown_command; took: 0:00:00.000101
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000393
DEBUG: Importing rule: whois; took: 0:00:00.000686
DEBUG: Trying rule: dry; took: 0:00:00.000282
DEBUG: Trying rule: test.py; took: 0:00:00.000027
DEBUG: Trying rule: apt_get_search; took: 0:00:00.009043
DEBUG: Trying rule: apt_invalid_operation; took: 0:00:00.000345
DEBUG: Trying rule: brew_install; took: 0:00:00.000029
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000029
DEBUG: Trying rule: brew_upgrade; took: 0:00:00.000026
DEBUG: Trying rule: cargo; took: 0:00:00.000025
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000291
DEBUG: Trying rule: cd_correction; took: 0:00:00.000290
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000272
DEBUG: Trying rule: cd_parent; took: 0:00:00.000026
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000282
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000280
DEBUG: Trying rule: cpp11; took: 0:00:00.000280
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000344
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000277
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000027
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000025
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000286
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000032
DEBUG: Trying rule: fix_file; took: 0:00:00.000177
DEBUG: Trying rule: git_add; took: 0:00:00.000294
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000278
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000276
DEBUG: Trying rule: git_checkout; took: 0:00:00.000280
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000274
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000274
DEBUG: Trying rule: git_not_command; took: 0:00:00.000274
DEBUG: Trying rule: git_pull; took: 0:00:00.000272
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000273
DEBUG: Trying rule: git_push; took: 0:00:00.000275
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000274
DEBUG: Trying rule: git_stash; took: 0:00:00.000281
DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000273
DEBUG: Trying rule: go_run; took: 0:00:00.000275
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000309
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000273
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000056
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000277
DEBUG: Trying rule: java; took: 0:00:00.000292
DEBUG: Trying rule: javac; took: 0:00:00.000297
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000282
DEBUG: Trying rule: ls_lah; took: 0:00:00.000282
DEBUG: Trying rule: man; took: 0:00:00.000298
DEBUG: Trying rule: mercurial; took: 0:00:00.000303
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000035
DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000290
DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000272
DEBUG: Trying rule: no_such_file; took: 0:00:00.001692
DEBUG: Trying rule: open; took: 0:00:00.000325
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000286
DEBUG: Trying rule: python_command; took: 0:00:00.000032
DEBUG: Trying rule: python_execute; took: 0:00:00.000275
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000027
DEBUG: Trying rule: rm_dir; took: 0:00:00.000028
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000288
DEBUG: Trying rule: sl_ls; took: 0:00:00.000029
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000287
DEBUG: Trying rule: sudo; took: 0:00:00.000087
DEBUG: Trying rule: switch_lang; took: 0:00:00.000286
DEBUG: Trying rule: systemctl; took: 0:00:00.000290
DEBUG: Trying rule: tmux; took: 0:00:00.000277
DEBUG: Trying rule: touch; took: 0:00:00.000280
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000275
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000289
DEBUG: Trying rule: unknown_command; took: 0:00:00.000500
DEBUG: Trying rule: vagrant_up; took: 0:00:00.000297
DEBUG: Trying rule: whois; took: 0:00:00.000289
DEBUG: Trying rule: man_no_space; took: 0:00:00.000030
DEBUG: Trying rule: no_command; took: 0:00:01.088361
DEBUG: Total took: 0:00:01.770493
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/main.py", line 79, in main
    fix_command()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/main.py", line 31, in fix_command
    selected_command = select_command(corrected_commands)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/ui.py", line 83, in select_command
    logs.confirm_text(selector.value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 41: ordinal not in range(128)
````
