### ISSUE TITLE
Проблема при исправлении команды с русскими символами 

### ISSUE THREAD

**Issue by akeinhell** [nvbn/thefuck#457]
Ветка в гите содержит русские символы, при попытке выполнить fuck получил ошибочку.

2016-02-11 02:31:52 ☆  akeinhell in /var/www/users/js/coffee
± |U-70-Группы U:3 ?:1 ✗| → git pull 
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> U-70-Группы

 2016-02-11 02:33:06 ☆  akeinhell in /var/www/users/js/coffee
± |U-70-Группы U:3 ?:1 ✗| → fuck 
```
git branch --set-upstream-to=origin/U-70-Группы U-70-Группы && git pull [enter/↑/↓/ctrl+c]
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 79, in main
    fix_command()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 34, in fix_command
    selected_command.run(command)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 284, in run
    print(self.script)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-46: ordinal not in range(128)
```

**Comment by nvbn** [comment]
Какая ос?

**Comment by akeinhell** [comment]
Ubuntu 14.04.3 LTS
Python 2.7.6

**Comment by nvbn** [comment]
А кодировка какая?

**Comment by akeinhell** [comment]
ru_RU.UTF-8
