### ISSUE TITLE
Problem in Git BASH on Windows - DistributionNotFound: decorator

### ISSUE THREAD

**Issue by macmodrov** [nvbn/thefuck#496]
When attempting to run thefuck:
```bash
$ fuck
Traceback (most recent call last):
  File "C:\Python27\Scripts\fuck-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build\bdist.win32\egg\pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "build\bdist.win32\egg\pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "build\bdist.win32\egg\pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: decorator
```
But pip claims that decorator is installed:
```bash
$ pip install decorator
Requirement already satisfied (use --upgrade to upgrade): decorator in c:\python
27\lib\site-packages
```
```bash
$ pip show decorator
---
Metadata-Version: 2.0
Name: decorator
Version: 4.0.9
Summary: Better living through Python with decorators
Home-page: https://github.com/micheles/decorator
Author: Michele Simionato
Author-email: michele.simionato@gmail.com
License: new BSD License
Location: c:\python27\lib\site-packages
Requires:
```
### Thefuck version:
master as of 21.04.2016, aquired with the following line
`pip install -U git+https://github.com/nvbn/thefuck.git`
Output of thefuck --version is the same error message with no version given.
```bash
$ pip show thefuck
---
Metadata-Version: 1.0
Name: thefuck
Version: 3.8
Summary: Magnificent app which corrects your previous console command
Home-page: https://github.com/nvbn/thefuck
Author: Vladimir Iakovlev
Author-email: nvbn.rm@gmail.com
License: MIT
Location: c:\python27\lib\site-packages
Requires: psutil, colorama, six, decorator, pathlib, win-unicode-console
Entry-points:
  [console_scripts]
  thefuck-alias = thefuck.main:print_alias
  thefuck = thefuck.main:main
  fuck = thefuck.main:how_to_configure_alias
```
### Environment
Shell: Git Bash (GNU bash, version 4.3.42(5))
Python: 2.7.6
OS: Windows 7 (64-bit).
thefuck

**Comment by macmodrov** [comment]
Using easy-install instead of pip to install decorator fixed this particular issue for me.
