### ISSUE TITLE
version 2.5.6-1: AttributeError: 'NoneType' object has no attribute 'stdout'

### ISSUE THREAD

**Issue by rubo77** [nvbn/thefuck#516]
I installed via apt-get version 2.5.6-1 in Ubuntu 15.10:

```
apt-get install thefuck
```

But I only always get this error, for example:

```
rubo77:~$ pyton
... did you mean »python« ? ...
rubo77:~$ thefuck 
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==2.5.6', 'console_scripts', 'thefuck.real')()
  File "/usr/share/thefuck/thefuck/main.py", line 160, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/usr/share/thefuck/thefuck/main.py", line 105, in get_matched_rule
    script_only = command.stdout is None and command.stderr is None
AttributeError: 'NoneType' object has no attribute 'stdout'
```

**Comment by nvbn** [comment]
Try to use `thefuck` from pip.

**Comment by rubo77** [comment]
doesn't work either:

```
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-0XUa46/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-M8zRBr-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-0XUa46/psutil
Storing debug log for failure in /home/ruben/.pip/pip.log

```

**Comment by rubo77** [comment]
This works:

```
sudo apt update
sudo apt install python3-dev python3-pip
sudo -H pip3 install thefuck
```

seems like there are some dependencies missing in the current debian package. You should fix that

**Comment by rubo77** [comment]
I found out:
On my Ubuntu it still gets the same errors unless I add this in my .bashrc:

    eval $(thefuck --alias)

It seems like this sentence

> You should place this command in your .bash_profile, .bashrc, .zshrc or other startup script

is not really convincing to really do it

should be changed:
https://github.com/nvbn/thefuck/pull/613
