### ISSUE TITLE
Issuing warnings on unicode inputs

### ISSUE THREAD

**Issue by theReticent** [nvbn/thefuck#533]
Everytime I try thefuck after forgetting to change my keyboard language and writing the command in unicode Persian characters by mistake, I get a bunch of these warnings (OS X 10.11.5 & ZSH 5.0.8):

[WARN] Rule composer_not_command:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 237, in compatibility_call
    return fn(*args)
  File "<decorator-gen-25>", line 2, in match
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 157, in _for_app
    if is_app(command, *app_names, **kwargs):
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 28, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 148, in is_app
    if command.script_parts is not None and len(command.script_parts) > at_least:
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 35, in script_parts
    self, sys.exc_info()))
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 48, in __repr__
    self.script, self.stdout, self.stderr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
----------------------------

[WARN] Rule cp_omitting_directory:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 237, in compatibility_call
    return fn(*args)
  File "<decorator-gen-28>", line 2, in match
  File "/Library/Python/2.7/site-packages/thefuck/specific/sudo.py", line 10, in sudo_support
    return fn(command)
  File "<decorator-gen-27>", line 2, in match
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 157, in _for_app
    if is_app(command, *app_names, **kwargs):
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 28, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 148, in is_app
    if command.script_parts is not None and len(command.script_parts) > at_least:
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 35, in script_parts
    self, sys.exc_info()))
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 48, in __repr__
    self.script, self.stdout, self.stderr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
----------------------------

[WARN] Rule tsuru_login:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 237, in compatibility_call
    return fn(*args)
  File "<decorator-gen-131>", line 2, in match
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 157, in _for_app
    if is_app(command, *app_names, **kwargs):
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 28, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/thefuck/utils.py", line 148, in is_app
    if command.script_parts is not None and len(command.script_parts) > at_least:
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 35, in script_parts
    self, sys.exc_info()))
  File "/Library/Python/2.7/site-packages/thefuck/types.py", line 48, in __repr__
    self.script, self.stdout, self.stderr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
----------------------------

**Comment by scorphus** [comment]
1. What does your alias look like?
2. How do you define it?
3. What's the output of `thefuck --version`?

**Comment by theReticent** [comment]
1. alias | grep fuck
fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

2. I have the following line in my .zshrc
eval "$(thefuck --alias)"

3. The Fuck 3.2 using Python 2.7.10

**Comment by theReticent** [comment]
Upgrading to The Fuck 3.11 fixed the issue for me.
