### ISSUE TITLE
Repeated fucking fucks up with UnicodeDecodeError (Python 2.7.6)

### ISSUE THREAD

**Issue by beigela** [nvbn/thefuck#623]
OS: Ubuntu 14.04
Terminals: xterm, terminator

```
user@host:~$ thefuck --version
The Fuck 3.15 using Python 2.7.6
# also tested with:
The Fuck 3.15 using Python 3.4.3
user@host:~$ echo $SHELL
/bin/bash
user@host:~$ /bin/bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
```

Issue: `UnicodeDecodeError` on repeated `fuck`ing. (Python 2.7.6 only -- Python 3.4.3 works fine)

Example 1.
```
user@host:~$ ls
. . . 邔 . . .
user@host:~$ fuck
No fucks given
user@host:~$ fuck
[WARN] Rule missing_space_before_subcommand:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 228, in is_match
    if self.match(command):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/missing_space_before_subcommand.py", line 13, in match
    and _get_executable(command.script_parts[0]))
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 34, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/missing_space_before_subcommand.py", line 7, in _get_executable
    if script_part.startswith(executable):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
----------------------------

No fucks given
```

Example 2.
```
user@host:~$ source ~/.bashrc
user@host:~$ fuck
[WARN] Rule missing_space_before_subcommand:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/types.py", line 228, in is_match
    if self.match(command):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/missing_space_before_subcommand.py", line 13, in match
    and _get_executable(command.script_parts[0]))
  File "/usr/local/lib/python2.7/dist-packages/thefuck/utils.py", line 34, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/rules/missing_space_before_subcommand.py", line 7, in _get_executable
    if script_part.startswith(executable):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
----------------------------

gresource ~/.bashrc [enter/↑/↓/ctrl+c]
```

**Comment by nvbn** [comment]
Does it still happens in 3.16?

**Comment by nitriques** [comment]
It stills happens on Windows, The Fuck 3.18 using Python 2.7.3

**Comment by scorphus** [comment]
Please check #673 for hints/solutions.
