### ISSUE TITLE
thefuck installed from Ubuntu repo does not work in Fish

### ISSUE THREAD

**Issue by adrfantini** [nvbn/thefuck#625]
I installed thefuck from the Ubuntu repos:
```
thefuck --version
The Fuck 3.2 using Python 2.7.12
```

And, since I use Fish, I did what specified here:
https://github.com/nvbn/thefuck/wiki/Shell-aliases

However...
```
[18:48:29]-[~]                                                                                                                                                                                              
[hp6-clima-10.ictp.it]->  puthon                                                                                                                                                                    18:48:29
No command 'puthon' found, did you mean:
 Command 'python' from package 'python3' (main)
 Command 'python' from package 'python-minimal' (main)
puthon: command not found
[18:48:34]-[~]                                                                                                                                                                                              
[hp6-clima-10.ictp.it]->  fuck                                                                                                                                                                      18:48:34
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck.real')()
  File "/usr/share/thefuck/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/share/thefuck/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/share/thefuck/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/share/thefuck/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 41: ordinal not in range(128)
```

**Comment by nvbn** [comment]
Please use thefuck from pip. 
In ubuntu repo it's very outdated and python 2 only.

**Comment by adrfantini** [comment]
That made it, thanks.
