### ISSUE TITLE
A seeming error, after 'apt update && apt upgrade' 

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [nvbn/thefuck#634]
```
[sudo] password for nicholas: 
Hit:1 http://ppa.launchpad.net/wseverin/ppa/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/dawidd0811/neofetch/ubuntu xenial InRelease                  
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                                
Ign:4 http://linuxmintpkg.efemef.ovh serena InRelease                                       
Hit:5 http://ppa.launchpad.net/dlech/keepass2-plugins/ubuntu xenial InRelease               
Hit:6 http://mirror.as29550.net/archive.ubuntu.com xenial InRelease                         
Hit:7 http://dl.google.com/linux/chrome/deb stable Release                                  
Hit:8 http://linuxmintpkg.efemef.ovh serena Release                                         
Hit:9 http://ppa.launchpad.net/gottcode/gcppa/ubuntu xenial InRelease                       
Hit:10 http://mirror.as29550.net/archive.ubuntu.com xenial-updates InRelease                
Hit:11 http://ppa.launchpad.net/linrunner/tlp/ubuntu xenial InRelease                       
Hit:12 http://ppa.launchpad.net/me-davidsansome/clementine/ubuntu xenial InRelease          
Hit:13 http://mirror.as29550.net/archive.ubuntu.com xenial-backports InRelease              
Hit:14 http://ppa.launchpad.net/nemh/systemback/ubuntu xenial InRelease                     
Hit:15 http://us.archive.ubuntu.com/ubuntu xenial InRelease                                 
Get:16 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                 
Hit:17 http://ppa.launchpad.net/noobslab/themes/ubuntu xenial InRelease                     
Hit:18 http://ppa.launchpad.net/paulo-miguel-dias/pkppa/ubuntu xenial InRelease             
Hit:19 http://ppa.launchpad.net/rvm/smplayer/ubuntu xenial InRelease                        
Hit:20 http://ppa.launchpad.net/shutter/ppa/ubuntu xenial InRelease                         
Hit:21 http://download.mono-project.com/repo/debian wheezy InRelease                        
Hit:22 http://ppa.launchpad.net/snwh/pulp/ubuntu xenial InRelease                           
Hit:23 http://ppa.launchpad.net/umang/indicator-stickynotes/ubuntu xenial InRelease         
Hit:24 http://download.virtualbox.org/virtualbox/debian xenial InRelease                    
Hit:25 http://ppa.launchpad.net/vincent-c/conky/ubuntu xenial InRelease                     
Hit:26 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu xenial InRelease              
Ign:27 http://build.openvpn.net/debian/openvpn/stable xenial InRelease                      
Hit:28 http://build.openvpn.net/debian/openvpn/stable xenial Release                        
Hit:31 http://archive.canonical.com/ubuntu xenial InRelease                                 
Fetched 102 kB in 2s (34.4 kB/s)                                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  network-manager
0 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.
~ $ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 129, in main
    fix_command()
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 93, in fix_command
    command = get_command(settings, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 63, in get_command
    if wait_output(settings, result):
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 41, in wait_output
    child.kill()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 300, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1084, in kill
    self._send_signal(signal.SIGKILL)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1027, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=15322)
~ $ 

```

**Comment by HeroCC** [comment]
I think it has to do with sudo. I reproduced it by running ``sudo echo hello``, then running fuck. It will prompt for password, but before I finish typing it, it says this same error.
