### ISSUE TITLE
UnicodeDecodeError: on windows git bash

### ISSUE THREAD

**Issue by eromoe** [nvbn/thefuck#643]
Hi, I tried to use thefuck on windows git bash.

 ` eval $(thefuck --alias --winpty)`  would get error:

```
usage: thefuck [-v] [-a [ALIAS]] [-h] [-y | -r] [-d] [command [command ...]]
thefuck: error: unrecognized arguments: --winpty
```
So I use `eval $(thefuck --alias)` (fine on my machine) . But

```
$ fuck
Traceback (most recent call last):
  File "d:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\thefuck.exe\__main__.py", line 9, in <module>
  File "d:\python27\lib\site-packages\thefuck\main.py", line 51, in main
    fix_command(known_args)
  File "d:\python27\lib\site-packages\thefuck\main.py", line 27, in fix_command
    command = types.Command.from_raw_script(raw_command)
  File "d:\python27\lib\site-packages\thefuck\types.py", line 125, in from_raw_script
    stderr = result.stderr.read().decode('utf-8')
  File "d:\python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 7: invalid start byte
```

**Comment by nvbn** [comment]
Is it fails with 3.17 too?
Can you try with python 3?

**Comment by eromoe** [comment]
Now work fine with python2 , thanks!
