### ISSUE TITLE
error: Unable to find  vcvarsall.bat

### ISSUE THREAD

**Issue by djaskolka** [nvbn/thefuck#649]
Hi there. I'm attempting to install on Windows 10 via pip as follows:
> pip install --user thefuck

I'm seeing the following error message in the logs:
"error: Unable to find vcvarsall.bat"

When I try to run 'fuck', I get the following:

> fuck
Traceback (most recent call last):
  File "C:\ActivePython27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ActivePython27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ActivePython27\Scripts\fuck.exe\__main__.py", line 5, in <module>
  File "C:\ActivePython27\lib\site-packages\thefuck\not_configured.py", line 2, in <module>
    from .system import init_output
  File "C:\ActivePython27\lib\site-packages\thefuck\system\__init__.py", line 5, in <module>
    from .win32 import *  # noqa: F401,F403
  File "C:\ActivePython27\lib\site-packages\thefuck\system\win32.py", line 38, in <module>
    from pathlib2 import Path
  File "C:\Users\myuser\AppData\Roaming\Python\Python27\site-packages\pathlib2.py", line 46, in <module>
    from scandir import scandir as os_scandir
ImportError: No module named scandir

Can anyone shed some light on this? Thanks in advance!

**Comment by Notelzg** [comment]
are you resolved this problem？I have meet similar issus。

**Comment by djaskolka** [comment]
I haven't received any additional advice about this, nor have I had a chance to look into this on my own. Sorry!

**Comment by ioiogoo** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/fuck", line 7, in <module>
    from thefuck.not_configured import main
  File "/usr/local/lib/python2.7/dist-packages/thefuck/not_configured.py", line 2, in <module>
    from .system import init_output
  File "/usr/local/lib/python2.7/dist-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
  File "/usr/local/lib/python2.7/dist-packages/thefuck/system/unix.py", line 49, in <module>
    from pathlib2 import Path
  File "/usr/local/lib/python2.7/dist-packages/pathlib2.py", line 45, in <module>
    from scandir import scandir as os_scandir
ImportError: No module named scandir
```
same to me.
system: ubuntu 14.04 python 2.7
