### ISSUE TITLE
AttributeError: 'Command' object has no attribute 'output'

### ISSUE THREAD

**Issue by jgrondier** [nvbn/thefuck#691]
Tested with: 
* Fedora 26 64bits
* The Fuck 3.23 using Python 3.6.2, installed using pip,  and The Fuck 3.2 using Python 3.6.2 using dnf
* Independant of bash (Happens with GNU bash, version 4.4.12(1)-release (x86_64-redhat-linux-gnu) and zsh 5.3.1 (x86_64-redhat-linux-gnu))

What happens:

Create any rule that uses command.output, for example thefollowing bar.py, in ~/.config/thefuck/rules :

    def match(command):
        return ('fuck' in command.output)
    def get_new_command(command):
        return '{}'.format(command.script)

Run a command that triggers the rule:

Output is:

    ➜  ~ thefuck --version
    The Fuck 3.23 using Python 3.6.2
    ➜  ~ fuck
    [WARN] Rule bar:
    Traceback (most recent call last):
      File "/home/jgrondier/.local/lib/python3.6/site-packages/thefuck/types.py", line 173, in is_match
        if self.match(command):
      File "/home/jgrondier/.config/thefuck/rules/bar.py", line 2, in match
        return ('fuck' in command.output)
    AttributeError: 'Command' object has no attribute 'output'
    ----------------------------

    zsh --version [enter/↑/↓/ctrl+c]

    
This appears with any rule, even if I just copy past it from the rules folder in this repo, as long as command.output is called.

For reference, here was what the original rule I was trying to make was foo.py , which is supposed to trigger on any pip command resulting in a Permission denied error:

    from thefuck.utils import for_app

    @for_app('pip', 'pip2', 'pip3')
    def match(command):
        return ('pip install' in command.script and 'Permission denied' in command.output)

    def get_new_command(command):
        return '{} --user'.format(command.script)

Here is the full log with debug on:

```➜  ~ thefuck --version          
The Fuck 3.23 using Python 3.6.2
➜  ~ fuck
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'instant_mode': False,
 'no_colors': False,
 'priority': {'no_command': 9999, 'sudo': 100},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/home/jgrondier/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Received stdout: 
DEBUG: Received stderr: The Fuck 3.23 using Python 3.6.2

DEBUG: Call: thefuck --version; with env: {'QT_IM_MODULE': 'ibus', 'XDG_SEAT': 'seat0', 'LANG': 'C', 'DISPLAY': ':0', 'SHLVL': '1', 'LOGNAME': 'jgrondier', 'XDG_VTNR': '2', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PWD': '/home/jgrondier', 'USER': 'jgrondier', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'DESKTOP_AUTOSTART_ID': '101a7f0edcec77769a150446118586341800000019750008', 'QTDIR': '/usr/lib64/qt-3.3', 'JOURNAL_STREAM': '9:35609', 'COLORTERM': 'truecolor', 'XDG_SESSION_ID': '2', 'DESKTOP_SESSION': 'gnome-xorg', 'XDG_SESSION_DESKTOP': 'gnome-xorg', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GDMSESSION': 'gnome-xorg', 'USERNAME': 'jgrondier', 'LC_NUMERIC': 'fr_CH.UTF-8', 'LC_MEASUREMENT': 'fr_CH.UTF-8', 'LC_PAPER': 'fr_CH.UTF-8', 'WINDOWPATH': '2', 'LC_MONETARY': 'fr_CH.UTF-8', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'MAIL': '/var/spool/mail/jgrondier', 'XDG_DATA_DIRS': '/home/jgrondier/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/', 'VTE_VERSION': '4803', 'MOZ_GMP_PATH': '/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed', 'MODULESHOME': '/usr/share/Modules', 'XDG_MENU_PREFIX': 'gnome-', 'HISTCONTROL': 'ignoredups', 'GDM_LANG': 'en_US.UTF-8', 'HOSTNAME': 'jgrondier-laptop', 'XDG_SESSION_TYPE': 'x11', 'OLDPWD': '/home/jgrondier', 'LC_TIME': 'fr_CH.UTF-8', 'TERM': 'xterm-256color', 'HISTSIZE': '10000', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/1975,unix/unix:/tmp/.ICE-unix/1975', 'XDG_CURRENT_DESKTOP': 'GNOME', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'WINDOWID': '207618054', 'MODULEPATH': '/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles', 'PATH': '/usr/local/texlive/2017/bin/x86_64-linux:/usr/local/texlive/2017/bin/x86_64-linux:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jgrondier/bin:/home/jgrondier/.local/bin:/home/jgrondier/bin:/home/jgrondier/.local/bin:/home/jgrondier/bin', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XMODIFIERS': '@im=ibus', 'SHELL': '/bin/zsh', 'QTINC': '/usr/lib64/qt-3.3/include', 'LOADEDMODULES': '', 'HOME': '/home/jgrondier', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:', 'ZSH': '/home/jgrondier/.oh-my-zsh', 'PAGER': 'less', 'LESS': '-R', 'LC_CTYPE': 'en_US.UTF-8', 'LSCOLORS': 'Gxfxcxdxbxegedabagacad', 'THEFUCK_DEBUG': 'true', '_': '/home/jgrondier/.local/bin/thefuck', 'LC_ALL': 'C', 'GIT_TRACE': '1'}; is slow:  took: 0:00:00.334663
DEBUG: Importing rule: ag_literal; took: 0:00:00.000735
DEBUG: Importing rule: apt_get; took: 0:00:00.001219
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000547
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.001388
DEBUG: Importing rule: aws_cli; took: 0:00:00.000500
DEBUG: Importing rule: brew_install; took: 0:00:00.000618
DEBUG: Importing rule: brew_link; took: 0:00:00.000507
DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000498
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000287
DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000528
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000203
DEBUG: Importing rule: cargo; took: 0:00:00.000181
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000551
DEBUG: Importing rule: cd_correction; took: 0:00:00.001727
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.001060
DEBUG: Importing rule: cd_parent; took: 0:00:00.000259
DEBUG: Importing rule: chmod_x; took: 0:00:00.000250
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000916
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.001634
DEBUG: Importing rule: cpp11; took: 0:00:00.000599
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001578
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.001279
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000154
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000135
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000641
DEBUG: Importing rule: dry; took: 0:00:00.000138
DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000437
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000339
DEBUG: Importing rule: fix_file; took: 0:00:00.004722
DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.000553
DEBUG: Importing rule: git_add; took: 0:00:00.000882
DEBUG: Importing rule: git_add_force; took: 0:00:00.000638
DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000597
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000649
DEBUG: Importing rule: git_branch_exists; took: 0:00:00.001288
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000680
DEBUG: Importing rule: git_checkout; took: 0:00:00.000470
DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000392
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000338
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000483
DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000346
DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000365
DEBUG: Importing rule: git_not_command; took: 0:00:00.000375
DEBUG: Importing rule: git_pull; took: 0:00:00.000344
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000336
DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000348
DEBUG: Importing rule: git_push; took: 0:00:00.000358
DEBUG: Importing rule: git_push_force; took: 0:00:00.000321
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000327
DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000408
DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000375
DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000240
DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000235
DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000362
DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000363
DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000348
DEBUG: Importing rule: git_stash; took: 0:00:00.000366
DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000521
DEBUG: Importing rule: git_tag_force; took: 0:00:00.000363
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000339
DEBUG: Importing rule: go_run; took: 0:00:00.000342
DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000722
DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000313
DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000333
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000354
DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000565
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000323
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000327
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000311
DEBUG: Importing rule: history; took: 0:00:00.000133
DEBUG: Importing rule: hostscli; took: 0:00:00.000467
DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000444
DEBUG: Importing rule: java; took: 0:00:00.000305
DEBUG: Importing rule: javac; took: 0:00:00.000337
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000481
DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000334
DEBUG: Importing rule: ln_s_order; took: 0:00:00.000325
DEBUG: Importing rule: ls_all; took: 0:00:00.000305
DEBUG: Importing rule: ls_lah; took: 0:00:00.000298
DEBUG: Importing rule: man; took: 0:00:00.000378
DEBUG: Importing rule: man_no_space; took: 0:00:00.000125
DEBUG: Importing rule: mercurial; took: 0:00:00.000303
DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000142
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000321
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000331
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000337
DEBUG: Importing rule: no_command; took: 0:00:00.000349
DEBUG: Importing rule: no_such_file; took: 0:00:00.000133
DEBUG: Importing rule: npm_missing_script; took: 0:00:00.000680
DEBUG: Importing rule: npm_run_script; took: 0:00:00.000471
DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000812
DEBUG: Importing rule: open; took: 0:00:00.000646
DEBUG: Importing rule: pacman; took: 0:00:00.001258
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000369
DEBUG: Importing rule: path_from_history; took: 0:00:00.000228
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000597
DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000314
DEBUG: Importing rule: python_command; took: 0:00:00.000372
DEBUG: Importing rule: python_execute; took: 0:00:00.000518
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000253
DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.000749
DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000245
DEBUG: Importing rule: rm_dir; took: 0:00:00.000585
DEBUG: Importing rule: rm_root; took: 0:00:00.000954
DEBUG: Importing rule: scm_correction; took: 0:00:00.000792
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000454
DEBUG: Importing rule: sl_ls; took: 0:00:00.000159
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000348
DEBUG: Importing rule: sudo; took: 0:00:00.000150
DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000331
DEBUG: Importing rule: switch_lang; took: 0:00:00.000166
DEBUG: Importing rule: systemctl; took: 0:00:00.000495
DEBUG: Importing rule: test.py; took: 0:00:00.000134
DEBUG: Importing rule: tmux; took: 0:00:00.000357
DEBUG: Importing rule: touch; took: 0:00:00.000322
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000320
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000315
DEBUG: Importing rule: unknown_command; took: 0:00:00.000138
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000306
DEBUG: Importing rule: whois; took: 0:00:00.000481
DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000477
DEBUG: Importing rule: yarn_alias; took: 0:00:00.000338
DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000576
DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000484
DEBUG: Importing rule: yarn_help; took: 0:00:00.000315
DEBUG: Importing rule: bar; took: 0:00:00.000133
DEBUG: Importing rule: foo; took: 0:00:00.000309
DEBUG: Trying rule: sudo; took: 0:00:00.000081
DEBUG: Trying rule: path_from_history; took: 0:00:00.000851
DEBUG: Trying rule: dry; took: 0:00:00.000022
DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000054
DEBUG: Trying rule: test.py; took: 0:00:00.000003
DEBUG: Trying rule: ag_literal; took: 0:00:00.000028
DEBUG: Trying rule: aws_cli; took: 0:00:00.000021
DEBUG: Trying rule: brew_link; took: 0:00:00.000020
DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000018
DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000016
DEBUG: Trying rule: cargo; took: 0:00:00.000003
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000020
DEBUG: Trying rule: cd_correction; took: 0:00:00.000020
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000017
DEBUG: Trying rule: cd_parent; took: 0:00:00.000004
DEBUG: Trying rule: chmod_x; took: 0:00:00.000004
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000018
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000019
DEBUG: Trying rule: cpp11; took: 0:00:00.000017
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000017
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000017
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000004
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000004
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000019
DEBUG: Trying rule: fab_command_not_found; took: 0:00:00.000024
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000007
DEBUG: Trying rule: fix_file; took: 0:00:00.000015
DEBUG: Trying rule: gem_unknown_command; took: 0:00:00.000018
DEBUG: Trying rule: git_add; took: 0:00:00.000016
DEBUG: Trying rule: git_add_force; took: 0:00:00.000015
DEBUG: Trying rule: git_bisect_usage; took: 0:00:00.000014
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000014
DEBUG: Trying rule: git_branch_exists; took: 0:00:00.000014
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000014
DEBUG: Trying rule: git_checkout; took: 0:00:00.000014
DEBUG: Trying rule: git_diff_no_index; took: 0:00:00.000014
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000014
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000014
DEBUG: Trying rule: git_flag_after_filename; took: 0:00:00.000013
DEBUG: Trying rule: git_help_aliased; took: 0:00:00.000014
DEBUG: Trying rule: git_not_command; took: 0:00:00.000014
DEBUG: Trying rule: git_pull; took: 0:00:00.000019
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000015
DEBUG: Trying rule: git_pull_uncommitted_changes; took: 0:00:00.000014
DEBUG: Trying rule: git_push; took: 0:00:00.000014
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000014
DEBUG: Trying rule: git_push_without_commits; took: 0:00:00.000019
DEBUG: Trying rule: git_rebase_merge_dir; took: 0:00:00.000014
DEBUG: Trying rule: git_rebase_no_changes; took: 0:00:00.000014
DEBUG: Trying rule: git_remote_seturl_add; took: 0:00:00.000014
DEBUG: Trying rule: git_rm_local_modifications; took: 0:00:00.000014
DEBUG: Trying rule: git_rm_recursive; took: 0:00:00.000014
DEBUG: Trying rule: git_rm_staged; took: 0:00:00.000014
DEBUG: Trying rule: git_stash; took: 0:00:00.000014
DEBUG: Trying rule: git_tag_force; took: 0:00:00.000014
DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000016
DEBUG: Trying rule: go_run; took: 0:00:00.000017
DEBUG: Trying rule: gradle_no_task; took: 0:00:00.000018
DEBUG: Trying rule: gradle_wrapper; took: 0:00:00.000017
DEBUG: Trying rule: grep_arguments_order; took: 0:00:00.000017
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000016
DEBUG: Trying rule: grunt_task_not_found; took: 0:00:00.000017
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000017
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000026
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000020
DEBUG: Trying rule: hostscli; took: 0:00:00.000021
DEBUG: Trying rule: ifconfig_device_not_found; took: 0:00:00.000017
DEBUG: Trying rule: java; took: 0:00:00.000022
DEBUG: Trying rule: javac; took: 0:00:00.000017
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000018
DEBUG: Trying rule: ln_no_hard_link; took: 0:00:00.000009
DEBUG: Trying rule: ln_s_order; took: 0:00:00.000007
DEBUG: Trying rule: ls_all; took: 0:00:00.000017
DEBUG: Trying rule: ls_lah; took: 0:00:00.000016
DEBUG: Trying rule: man; took: 0:00:00.000018
DEBUG: Trying rule: mercurial; took: 0:00:00.000017
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000011
DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000017
DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000015
DEBUG: Trying rule: no_such_file; took: 0:00:00.000746
DEBUG: Trying rule: npm_missing_script; took: 0:00:00.000027
DEBUG: Trying rule: npm_run_script; took: 0:00:00.000017
DEBUG: Trying rule: npm_wrong_command; took: 0:00:00.000017
DEBUG: Trying rule: open; took: 0:00:00.000019
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000019
DEBUG: Trying rule: port_already_in_use; took: 0:00:00.000586
DEBUG: Trying rule: python_command; took: 0:00:00.000009
DEBUG: Trying rule: python_execute; took: 0:00:00.000026
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000004
DEBUG: Trying rule: react_native_command_unrecognized; took: 0:00:00.000019
DEBUG: Trying rule: remove_trailing_cedilla; took: 0:00:00.000005
DEBUG: Trying rule: rm_dir; took: 0:00:00.000006
DEBUG: Trying rule: scm_correction; took: 0:00:00.000019
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000017
DEBUG: Trying rule: sl_ls; took: 0:00:00.000004
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000020
DEBUG: Trying rule: sudo_command_from_user_path; took: 0:00:00.000017
DEBUG: Trying rule: switch_lang; took: 0:00:00.000004
DEBUG: Trying rule: systemctl; took: 0:00:00.000018
DEBUG: Trying rule: tmux; took: 0:00:00.000017
DEBUG: Trying rule: touch; took: 0:00:00.000017
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000020
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000015
DEBUG: Trying rule: unknown_command; took: 0:00:00.000150
DEBUG: Trying rule: vagrant_up; took: 0:00:00.000021
DEBUG: Trying rule: whois; took: 0:00:00.000019
DEBUG: Trying rule: workon_doesnt_exists; took: 0:00:00.000018
DEBUG: Trying rule: yarn_alias; took: 0:00:00.000017
DEBUG: Trying rule: yarn_command_not_found; took: 0:00:00.000018
DEBUG: Trying rule: yarn_command_replaced; took: 0:00:00.000016
DEBUG: Trying rule: yarn_help; took: 0:00:00.000017
DEBUG: Trying rule: bar; took: 0:00:00.000010
[WARN] Rule bar:
Traceback (most recent call last):
  File "/home/jgrondier/.local/lib/python3.6/site-packages/thefuck/types.py", line 173, in is_match
    if self.match(command):
  File "/home/jgrondier/.config/thefuck/rules/bar.py", line 2, in match
    return ('fuck' in command.output)
AttributeError: 'Command' object has no attribute 'output'
----------------------------

DEBUG: Trying rule: foo; took: 0:00:00.000024
DEBUG: Trying rule: man_no_space; took: 0:00:00.000004
DEBUG: Trying rule: missing_space_before_subcommand; took: 0:00:00.046487
DEBUG: Trying rule: history; took: 0:00:00.009782
zsh --version [enter/↑/↓/ctrl+c]```

So I was wondering what I was missing

**Comment by nvbn** [comment]
I upgraded readme too early. In the next release it will be `output`.
At the moment you can use `stdout`/`stderr` instead.

**Comment by jgrondier** [comment]
Great, thank you very much
