### ISSUE TITLE
Fuck permission denied

### ISSUE THREAD

**Issue by cdipaolo** [nvbn/thefuck#71]
On most recent version (1.1.8) I get this error on OSX 10.10.13 when calling `fuck`. I assume it has something to do with the $PATH walk on the most recent commit. If this is a permissions error, which it almost certainly is, can it be solved programmatically such that future users don't have to `chmod 777` anything to get this CLI to work? Can look in more detail tomorrow, but for now this is all I have.

```bash
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.18', 'console_scripts', 'thefuck')()
  File "/usr/local/lib/python2.7/site-packages/thefuck/main.py", line 136, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/usr/local/lib/python2.7/site-packages/thefuck/main.py", line 93, in get_matched_rule
    if rule.match(command, settings):
  File "/usr/local/lib/python2.7/site-packages/thefuck/rules/no_command.py", line 16, in match
    _get_all_bins()))
  File "/usr/local/lib/python2.7/site-packages/thefuck/rules/no_command.py", line 10, in _get_all_bins
    if exe.is_file()]
  File "/usr/local/lib/python2.7/site-packages/pathlib.py", line 1202, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/local/lib/python2.7/site-packages/pathlib.py", line 1051, in stat
    return self._accessor.stat(self)
  File "/usr/local/lib/python2.7/site-packages/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 13] Permission denied: '/usr/sbin/weakpass_edit'
```

**Comment by nwinkler** [comment]
I've got a similar error. My $PATH contains an entry for `./node_modules/bin` to include a potential local `node_modules/bin` folder under the current directory. Since this folder doesn't always exist, `fuck` fails with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.18', 'console_scripts', 'thefuck')()
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/main.py", line 136, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/main.py", line 93, in get_matched_rule
    if rule.match(command, settings):
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/rules/no_command.py", line 16, in match
    _get_all_bins()))
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/rules/no_command.py", line 9, in _get_all_bins
    for exe in Path(path).iterdir()
  File "/Library/Python/2.7/site-packages/pathlib.py", line 982, in iterdir
    for name in self._accessor.listdir(self):
  File "/Library/Python/2.7/site-packages/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 2] No such file or directory: 'node_modules/.bin'
```

**Comment by nvbn** [comment]
Is it repeats in 1.19+?

**Comment by nwinkler** [comment]
With 1.20, I'm now getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.20', 'console_scripts', 'thefuck')()
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/main.py", line 136, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/main.py", line 93, in get_matched_rule
    if rule.match(command, settings):
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/rules/no_command.py", line 23, in match
    _get_all_bins()))
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/rules/no_command.py", line 16, in _get_all_bins
    for exe in _safe(Path(path).iterdir, [])
  File "/Library/Python/2.7/site-packages/pathlib.py", line 982, in iterdir
    for name in self._accessor.listdir(self):
  File "/Library/Python/2.7/site-packages/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 2] No such file or directory: 'node_modules/.bin'
```

**Comment by nvbn** [comment]
@nwinkler, should work in 1.21+ =)

**Comment by nwinkler** [comment]
Sorry, no, still the same error:

```
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==1.21', 'console_scripts', 'thefuck')()
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/main.py", line 136, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/main.py", line 93, in get_matched_rule
    if rule.match(command, settings):
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/rules/no_command.py", line 23, in match
    _get_all_bins()))
  File "/Users/nils.winkler/workspaces/Nils/thefuck/thefuck/rules/no_command.py", line 16, in _get_all_bins
    for exe in _safe(lambda: Path(path).iterdir(), [])
  File "/Library/Python/2.7/site-packages/pathlib.py", line 982, in iterdir
    for name in self._accessor.listdir(self):
  File "/Library/Python/2.7/site-packages/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 2] No such file or directory: 'node_modules/.bin'
```

To test this, add `./node_modules/bin` to your $PATH variable and try to run `fuck` in a folder that does not have a `node_modules` folder.

**Comment by nvbn** [comment]
Ok, I've repeated that error locally and in 1.22+ it's definitely fixed =)

**Comment by nwinkler** [comment]
Yes, it's working fine for me now! Thanks a lot for the hard work on this fuck! (Pun intended)
