### ISSUE TITLE
Cannot Start.

### ISSUE THREAD

**Issue by OriginCode** [nvbn/thefuck#748]
It threw an error mesage when it start with the ZSH:
~~~~
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 7, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/local/lib/python3.6/site-packages/thefuck/entrypoints/main.py", line 11, in <module>
    from .alias import print_alias  # noqa: E402
  File "/usr/local/lib/python3.6/site-packages/thefuck/entrypoints/alias.py", line 3, in <module>
    from ..shells import shell
  File "/usr/local/lib/python3.6/site-packages/thefuck/shells/__init__.py", line 6, in <module>
    from psutil import Process
ImportError: cannot import name 'Process'
~~~~

When I was trying to use it, it threw another error:
~~~~
Traceback (most recent call last):
  File "/usr/local/bin/fuck", line 7, in <module>
    from thefuck.entrypoints.not_configured import main
  File "/usr/local/lib/python3.6/site-packages/thefuck/entrypoints/not_configured.py", line 11, in <module>
    from psutil import Process  # noqa: E402
ImportError: cannot import name 'Process'
~~~~

And then I tried to run the import in the Python 3 CLI, I discovered that there is NO SUCH attribute in the module 'psutil'.

Please repair it by using a newer solution or by changing a module.

**Comment by scorphus** [comment]
The `psutil` module should have been installed along with TheFuck in the installation process :thinking: Can you please give us more information:
1. How did you install TheFuck?
2. What is the output of `thefuck --version`?
3. What is the output of `pip list --format=columns`?
4. I think I know what you mean by start but I'm not sure. Can you clarify this?
5. What are the steps to reproduce what you're experiencing?

Thanks!

**Comment by OriginCode** [comment]
@scorphus Well, it is OK right now...
I don't know what happened...

**Comment by scorphus** [comment]
Glad to know it works! I'm closing this issue for now. Fell free to reopen it in case it raises again. Thanks!
