### ISSUE TITLE
Hebrew to English characters translation fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by thedrow** [nvbn/thefuck#791]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):

    The Fuck 3.25 using Python 2.7.14

Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):

    GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)

Your system (Debian 7, ArchLinux, Windows, etc.):

Ubuntu 17.10

How to reproduce the bug:
Type the following:
    ךד
    fuck

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):
```
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'instant_mode': False,
 'no_colors': False,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/home/omer/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Total took: 0:00:00.050230
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/thefuck", line 12, in <module>
    sys.exit(main())
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/entrypoints/main.py", line 25, in main
    fix_command(known_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/entrypoints/fix_command.py", line 36, in fix_command
    command = types.Command.from_raw_script(raw_command)
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/types.py", line 82, in from_raw_script
    output = get_output(script, expanded)
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/output_readers/__init__.py", line 18, in get_output
    return rerun.get_output(script, expanded)
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/output_readers/rerun.py", line 42, in get_output
    is_slow = shlex.split(expanded) in settings.slow_commands
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python2.7/shlex.py", line 275, in split
    lex = shlex(s, posix=posix)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python2.7/shlex.py", line 25, in __init__
    instream = StringIO(instream)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:
Nope

**Comment by nvbn** [comment]
Python 2.7 support is deprecated, please upgrade to Python 3.

**Comment by thedrow** [comment]
I can confirm this problem does not reproduce on Python 3.
