### ISSUE TITLE
Does not work in Elementary OS Freya

### ISSUE THREAD

**Issue by woverton** [nvbn/thefuck#80]
#### OS version:
```
woverton@pc-wover-06:~$ cat /etc/lsb-release
DISTRIB_ID="elementary OS"
DISTRIB_RELEASE=0.3
DISTRIB_CODENAME=freya
DISTRIB_DESCRIPTION="elementary OS Freya"
```

#### Using Fuck
```
woverton@pc-wover-06:~$ apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
woverton@pc-wover-06:~$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil
woverton@pc-wover-06:~$
```

**Comment by nvbn** [comment]
You installed it through `pip install thefuck`?
Although, `pip install psutil` should fix the error.

**Comment by woverton** [comment]
I did run ```pip install thefuck```

I have also installed ```pip install psutil```

**Comment by woverton** [comment]
Thanks, that fixed the issue
