### ISSUE TITLE
Problem using "fuck" command on GCP while using Fish shell

### ISSUE THREAD

**Issue by MostHated** [nvbn/thefuck#904]
**The output of `thefuck --version` (something like `The Fuck 3.1 using Python3.5.0 and Bash 4.4.12(1)-release`):**

The Fuck 3.28 using Python 3.6.7 and Fish Shell 2.7.1

**Your system (Debian 7, ArchLinux, Windows, etc.):**
Output of Neofetch. I didn't change the shell fully to fish, I only attempted to run it as seen in the log entry below.

OS: Ubuntu 18.04.2 LTS x86_64                                                              
Host: Google Compute Engine                                                                
Kernel: 4.15.0-1029-gcp                                                                    
Uptime: 14 days, 18 hours, 26 mins                                                         
Packages: 906                                                                              
Shell: bash 4.4.19                                                                         
Terminal: /dev/pts/0                                                                       
CPU: Intel Xeon (1) @ 2.300GHz                                                             
Memory: 1009MiB / 3693MiB 

**How to reproduce the bug:**
With Fish installed, just type the commands as I have below in the debug output.

**The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):**

```bash
user@server ~> fish
Welcome to fish, the friendly interactive shell
user@server  ~> fuck
No fucks given
user@server ~> fuck
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thefuck/output_readers/rerun.py", line 36, in _wait_output
    else settings.wait_command)
  File "/usr/local/lib/python3.6/dist-packages/psutil/__init__.py", line 1380, in wait
    return self._proc.wait(timeout)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1720, in wait
    return _psposix.wait_pid(self.pid, timeout, self._name)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_psposix.py", line 108, in wait_pid
    delay = check_timeout(delay)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_psposix.py", line 70, in check_timeout
    raise TimeoutExpired(timeout, pid=pid, name=proc_name)
DEBUG: Total took: 0:00:03.486597
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thefuck/output_readers/rerun.py", line 36, in _wait_output
    else settings.wait_command)
  File "/usr/local/lib/python3.6/dist-packages/psutil/__init__.py", line 1380, in wait
    return self._proc.wait(timeout)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1720, in wait
    return _psposix.wait_pid(self.pid, timeout, self._name)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_psposix.py", line 108, in wait_pid
    delay = check_timeout(delay)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_psposix.py", line 70, in check_timeout
    raise TimeoutExpired(timeout, pid=pid, name=proc_name)
psutil.TimeoutExpired: psutil.TimeoutExpired timeout after 3 seconds (pid=22101)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/thefuck/entrypoints/main.py", line 26, in main
    fix_command(known_args)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/entrypoints/fix_command.py", line 36, in fix_command
    command = types.Command.from_raw_script(raw_command)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/types.py", line 82, in from_raw_script
    output = get_output(script, expanded)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/output_readers/__init__.py", line 20, in get_output
    return rerun.get_output(script, expanded)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/output_readers/rerun.py", line 61, in get_output
    if _wait_output(result, is_slow):
  File "/usr/local/lib/python3.6/dist-packages/thefuck/output_readers/rerun.py", line 40, in _wait_output
    _kill_process(child)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/output_readers/rerun.py", line 17, in _kill_process
    proc.kill()
  File "/usr/local/lib/python3.6/dist-packages/psutil/__init__.py", line 387, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=22110)
user@server  ~> 
```

**Comment by scorphus** [comment]
Thanks for reporting. This is a known issue, check #741. It's fixed in current release, [3.29](https://pypi.org/project/thefuck/3.29/). Kindly update to it.
