### ISSUE TITLE
.bash_history permission denied despite running on latest version

### ISSUE THREAD

**Issue by mayukhnair** [nvbn/thefuck#927]
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

The Fuck 3.29 using Python 3.6.8 and Bash 4.4.19(1)-release

Your system (Debian 7, ArchLinux, Windows, etc.):

Ubuntu 18.04 LTS

How to reproduce the bug:

```sudo pip3 install thefuck
puthon
fuck
puthon
sudo fuck```

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'instant_mode': False,
 'no_colors': False,
 'num_close_matches': 3,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/home/mayukh/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Received output: /bin/sh: 1: puthon: not found

DEBUG: Call: puthon; with env: {'CLUTTER_IM_MODULE': 'xim', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_MENU_PREFIX': 'gnome-', 'LANG': 'C', 'DISPLAY': ':0', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'COLORTERM': 'truecolor', 'TF_SHELL_ALIASES': 'alias alert=\'notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e \'\\\'\'s/^\\s*[0-9]\\+\\s*//;s/[;&|]\\s*alert$//\'\\\'\')"\'\nalias egrep=\'egrep --color=auto\'\nalias fgrep=\'fgrep --color=auto\'\nalias grep=\'grep --color=auto\'\nalias l=\'ls -CF\'\nalias la=\'ls -A\'\nalias ll=\'ls -alF\'\nalias ls=\'ls --color=auto\'', 'DESKTOP_AUTOSTART_ID': '10ff105daef085e985156101898541644700000011900007', 'USERNAME': 'mayukh', 'XDG_VTNR': '2', 'PYTHONIOENCODING': 'utf-8', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XDG_SESSION_ID': '2', 'USER': 'mayukh', 'DESKTOP_SESSION': 'ubuntu', 'QT4_IM_MODULE': 'xim', 'TEXTDOMAINDIR': '/usr/share/locale/', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/6dd66c77_8916_4c1c_a1d4_58dfcf1b30c0', 'TF_SHELL': 'bash', 'PWD': '/home/mayukh', 'HOME': '/home/mayukh', 'TEXTDOMAIN': 'im-config', 'SSH_AGENT_PID': '1283', 'QT_ACCESSIBILITY': '1', 'XDG_SESSION_TYPE': 'x11', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'XDG_SESSION_DESKTOP': 'ubuntu', 'GTK_MODULES': 'gail:atk-bridge', 'WINDOWPATH': '2', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'VTE_VERSION': '5201', 'QT_IM_MODULE': 'xim', 'XMODIFIERS': '@im=ibus', 'IM_CONFIG_PHASE': '2', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'TF_ALIAS': 'fuck', 'GNOME_TERMINAL_SERVICE': ':1.209', 'XDG_SEAT': 'seat0', 'SHLVL': '1', 'GDMSESSION': 'ubuntu', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LOGNAME': 'mayukh', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'TF_HISTORY': '\t thefuck --version\n\t puthon\n\t fuck THEFUCK_DEBUG = true\n\t ls\n\t export THEFUCK_DEBUG = true\n\t export THEFUCK_DEBUG=true\n\t fuck THEFUCK_DEBUG = true\n\t clear\n\t puthon', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'THEFUCK_DEBUG': 'true', 'SESSION_MANAGER': 'local/mayukh:@/tmp/.ICE-unix/1190,unix/mayukh:/tmp/.ICE-unix/1190', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'GTK_IM_MODULE': 'ibus', '_': '/usr/local/bin/thefuck', 'LC_ALL': 'C', 'GIT_TRACE': '1'}; is slow:  took: 0:00:00.001393
DEBUG: Importing rule: adb_unknown_command; took: 0:00:00.000242
DEBUG: Importing rule: ag_literal; took: 0:00:00.000406
DEBUG: Importing rule: apt_get; took: 0:00:00.010504
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000422
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.000729
DEBUG: Importing rule: apt_list_upgradable; took: 0:00:00.000425
DEBUG: Importing rule: apt_upgrade; took: 0:00:00.000411
DEBUG: Importing rule: aws_cli; took: 0:00:00.000346
DEBUG: Importing rule: az_cli; took: 0:00:00.000259
DEBUG: Importing rule: brew_cask_dependency; took: 0:00:00.000524
DEBUG: Importing rule: brew_install; took: 0:00:00.000106
DEBUG: Importing rule: brew_link; took: 0:00:00.000251
DEBUG: Importing rule: brew_reinstall; took: 0:00:00.000519
DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000253
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000122
DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000253
DEBUG: Importing rule: brew_upgrade; took: 0:00:00.000093
DEBUG: Importing rule: cargo; took: 0:00:00.000080
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000266
DEBUG: Importing rule: cat_dir; took: 0:00:00.000254
DEBUG: Importing rule: cd_correction; took: 0:00:00.001016
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000390
DEBUG: Importing rule: cd_parent; took: 0:00:00.000092
DEBUG: Importing rule: chmod_x; took: 0:00:00.000089
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000252
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000442
DEBUG: Importing rule: cpp11; took: 0:00:00.000246
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001112
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000928
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000099
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000083
DEBUG: Importing rule: dnf_no_such_command; took: 0:00:00.000756
DEBUG: Importing rule: docker_login; took: 0:00:00.000260
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000486
DEBUG: Importing rule: dry; took: 0:00:00.000096
DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000374
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000295
DEBUG: Importing rule: fix_file; took: 0:00:00.002923
DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.000453
DEBUG: Importing rule: git_add; took: 0:00:00.000497
DEBUG: Importing rule: git_add_force; took: 0:00:00.000252
DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000258
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000249
DEBUG: Importing rule: git_branch_exists; took: 0:00:00.000314
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000242
DEBUG: Importing rule: git_checkout; took: 0:00:00.000260
DEBUG: Importing rule: git_commit_amend; took: 0:00:00.000715
DEBUG: Importing rule: git_commit_reset; took: 0:00:00.000254
DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000251
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000247
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000255
DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000260
DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000246
DEBUG: Importing rule: git_merge; took: 0:00:00.000247
DEBUG: Importing rule: git_merge_unrelated; took: 0:00:00.000236
DEBUG: Importing rule: git_not_command; took: 0:00:00.000250
DEBUG: Importing rule: git_pull; took: 0:00:00.000241
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000245
DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000244
DEBUG: Importing rule: git_push; took: 0:00:00.000251
DEBUG: Importing rule: git_push_different_branch_names; took: 0:00:00.000259
DEBUG: Importing rule: git_push_force; took: 0:00:00.000238
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000233
DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000276
DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000245
DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000175
DEBUG: Importing rule: git_remote_delete; took: 0:00:00.000240
DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000175
DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000257
DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000293
DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000247
DEBUG: Importing rule: git_stash; took: 0:00:00.000235
DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000236
DEBUG: Importing rule: git_tag_force; took: 0:00:00.000232
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000241
DEBUG: Importing rule: go_run; took: 0:00:00.000252
DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000592
DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000347
DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000313
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000274
DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000494
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000278
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000249
DEBUG: Importing rule: heroku_multiple_apps; took: 0:00:00.000256
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000242
DEBUG: Importing rule: history; took: 0:00:00.000097
DEBUG: Importing rule: hostscli; took: 0:00:00.000442
DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000306
DEBUG: Importing rule: java; took: 0:00:00.000243
DEBUG: Importing rule: javac; took: 0:00:00.000243
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000388
DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000239
DEBUG: Importing rule: ln_s_order; took: 0:00:00.000246
DEBUG: Importing rule: long_form_help; took: 0:00:00.000093
DEBUG: Importing rule: ls_all; took: 0:00:00.000246
DEBUG: Importing rule: ls_lah; took: 0:00:00.000245
DEBUG: Importing rule: man; took: 0:00:00.000247
DEBUG: Importing rule: man_no_space; took: 0:00:00.000089
DEBUG: Importing rule: mercurial; took: 0:00:00.000242
DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000098
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000243
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000244
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000251
DEBUG: Importing rule: no_command; took: 0:00:00.000251
DEBUG: Importing rule: no_such_file; took: 0:00:00.000093
DEBUG: Importing rule: npm_missing_script; took: 0:00:00.000517
DEBUG: Importing rule: npm_run_script; took: 0:00:00.000317
DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000379
DEBUG: Importing rule: open; took: 0:00:00.000313
DEBUG: Importing rule: pacman; took: 0:00:00.000352
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000099
DEBUG: Importing rule: path_from_history; took: 0:00:00.000106
DEBUG: Importing rule: php_s; took: 0:00:00.000250
DEBUG: Importing rule: pip_install; took: 0:00:00.000310
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000310
DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000161
DEBUG: Importing rule: prove_recursively; took: 0:00:00.000253
DEBUG: Importing rule: pyenv_no_such_command; took: 0:00:00.000461
DEBUG: Importing rule: python_command; took: 0:00:00.000238
DEBUG: Importing rule: python_execute; took: 0:00:00.000266
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000087
DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.000337
DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000095
DEBUG: Importing rule: rm_dir; took: 0:00:00.000244
DEBUG: Importing rule: rm_root; took: 0:00:00.000312
DEBUG: Importing rule: scm_correction; took: 0:00:00.000261
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000249
DEBUG: Importing rule: sl_ls; took: 0:00:00.000088
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000247
DEBUG: Importing rule: sudo; took: 0:00:00.000093
DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000246
DEBUG: Importing rule: switch_lang; took: 0:00:00.000127
DEBUG: Importing rule: systemctl; took: 0:00:00.000378
DEBUG: Importing rule: test.py; took: 0:00:00.000089
DEBUG: Importing rule: tmux; took: 0:00:00.000248
DEBUG: Importing rule: touch; took: 0:00:00.000251
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000261
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000257
DEBUG: Importing rule: unknown_command; took: 0:00:00.000103
DEBUG: Importing rule: unsudo; took: 0:00:00.000080
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000345
DEBUG: Importing rule: whois; took: 0:00:00.000799
DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000345
DEBUG: Importing rule: yarn_alias; took: 0:00:00.000284
DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000583
DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000330
DEBUG: Importing rule: yarn_help; took: 0:00:00.000271
DEBUG: Trying rule: path_from_history; took: 0:00:00.000370
DEBUG: Trying rule: dry; took: 0:00:00.000047
DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000020
DEBUG: Trying rule: test.py; took: 0:00:00.000002
DEBUG: Trying rule: adb_unknown_command; took: 0:00:00.000012
DEBUG: Trying rule: ag_literal; took: 0:00:00.000010
DEBUG: Trying rule: apt_get; took: 0:00:00.000255
DEBUG: Trying rule: apt_get_search; took: 0:00:00.000017
DEBUG: Trying rule: apt_invalid_operation; took: 0:00:00.000014
DEBUG: Trying rule: apt_list_upgradable; took: 0:00:00.000012
DEBUG: Trying rule: apt_upgrade; took: 0:00:00.000009
DEBUG: Trying rule: aws_cli; took: 0:00:00.000010
DEBUG: Trying rule: az_cli; took: 0:00:00.000010
DEBUG: Trying rule: brew_link; took: 0:00:00.000010
DEBUG: Trying rule: brew_reinstall; took: 0:00:00.000009
DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000008
DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000009
DEBUG: Trying rule: cargo; took: 0:00:00.000002
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000010
DEBUG: Trying rule: cat_dir; took: 0:00:00.000009
DEBUG: Trying rule: cd_correction; took: 0:00:00.000012
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000009
DEBUG: Trying rule: cd_parent; took: 0:00:00.000003
DEBUG: Trying rule: chmod_x; took: 0:00:00.000003
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000010
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000010
DEBUG: Trying rule: cpp11; took: 0:00:00.000009
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000010
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000009
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000003
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000002
DEBUG: Trying rule: docker_login; took: 0:00:00.000009
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000009
DEBUG: Trying rule: fab_command_not_found; took: 0:00:00.000009
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000004
DEBUG: Trying rule: fix_file; took: 0:00:00.000009
DEBUG: Trying rule: gem_unknown_command; took: 0:00:00.000010
DEBUG: Trying rule: git_add; took: 0:00:00.000009
DEBUG: Trying rule: git_add_force; took: 0:00:00.000007
DEBUG: Trying rule: git_bisect_usage; took: 0:00:00.000007
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000008
DEBUG: Trying rule: git_branch_exists; took: 0:00:00.000007
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000008
DEBUG: Trying rule: git_checkout; took: 0:00:00.000007
DEBUG: Trying rule: git_commit_amend; took: 0:00:00.000008
DEBUG: Trying rule: git_commit_reset; took: 0:00:00.000007
DEBUG: Trying rule: git_diff_no_index; took: 0:00:00.000008
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000007
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000008
DEBUG: Trying rule: git_flag_after_filename; took: 0:00:00.000008
DEBUG: Trying rule: git_help_aliased; took: 0:00:00.000007
DEBUG: Trying rule: git_merge; took: 0:00:00.000008
DEBUG: Trying rule: git_merge_unrelated; took: 0:00:00.000007
DEBUG: Trying rule: git_not_command; took: 0:00:00.000008
DEBUG: Trying rule: git_pull; took: 0:00:00.000010
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000007
DEBUG: Trying rule: git_pull_uncommitted_changes; took: 0:00:00.000007
DEBUG: Trying rule: git_push; took: 0:00:00.000007
DEBUG: Trying rule: git_push_different_branch_names; took: 0:00:00.000008
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000008
DEBUG: Trying rule: git_push_without_commits; took: 0:00:00.000007
DEBUG: Trying rule: git_rebase_merge_dir; took: 0:00:00.000007
DEBUG: Trying rule: git_rebase_no_changes; took: 0:00:00.000008
DEBUG: Trying rule: git_remote_delete; took: 0:00:00.000009
DEBUG: Trying rule: git_remote_seturl_add; took: 0:00:00.000008
DEBUG: Trying rule: git_rm_local_modifications; took: 0:00:00.000007
DEBUG: Trying rule: git_rm_recursive; took: 0:00:00.000008
DEBUG: Trying rule: git_rm_staged; took: 0:00:00.000008
DEBUG: Trying rule: git_stash; took: 0:00:00.000007
DEBUG: Trying rule: git_tag_force; took: 0:00:00.000008
DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000008
DEBUG: Trying rule: go_run; took: 0:00:00.000009
DEBUG: Trying rule: gradle_no_task; took: 0:00:00.000012
DEBUG: Trying rule: gradle_wrapper; took: 0:00:00.000009
DEBUG: Trying rule: grep_arguments_order; took: 0:00:00.000009
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000009
DEBUG: Trying rule: grunt_task_not_found; took: 0:00:00.000009
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000009
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000011
DEBUG: Trying rule: heroku_multiple_apps; took: 0:00:00.000009
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000010
DEBUG: Trying rule: hostscli; took: 0:00:00.000010
DEBUG: Trying rule: ifconfig_device_not_found; took: 0:00:00.000009
DEBUG: Trying rule: java; took: 0:00:00.000009
DEBUG: Trying rule: javac; took: 0:00:00.000009
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000009
DEBUG: Trying rule: ln_no_hard_link; took: 0:00:00.000003
DEBUG: Trying rule: ln_s_order; took: 0:00:00.000005
DEBUG: Trying rule: ls_all; took: 0:00:00.000009
DEBUG: Trying rule: ls_lah; took: 0:00:00.000008
DEBUG: Trying rule: man; took: 0:00:00.000010
DEBUG: Trying rule: mercurial; took: 0:00:00.000009
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000003
DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000009
DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000008
DEBUG: Trying rule: no_such_file; took: 0:00:00.000458
DEBUG: Trying rule: open; took: 0:00:00.000016
DEBUG: Trying rule: php_s; took: 0:00:00.000012
DEBUG: Trying rule: pip_install; took: 0:00:00.000016
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000014
DEBUG: Trying rule: port_already_in_use; took: 0:00:00.000372
DEBUG: Trying rule: prove_recursively; took: 0:00:00.000027
DEBUG: Trying rule: pyenv_no_such_command; took: 0:00:00.000015
DEBUG: Trying rule: python_command; took: 0:00:00.000005
DEBUG: Trying rule: python_execute; took: 0:00:00.000011
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000003
DEBUG: Trying rule: react_native_command_unrecognized; took: 0:00:00.000009
DEBUG: Trying rule: remove_trailing_cedilla; took: 0:00:00.000003
DEBUG: Trying rule: rm_dir; took: 0:00:00.000003
DEBUG: Trying rule: scm_correction; took: 0:00:00.000012
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000010
DEBUG: Trying rule: sl_ls; took: 0:00:00.000003
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000010
DEBUG: Trying rule: sudo; took: 0:00:00.000008
DEBUG: Trying rule: sudo_command_from_user_path; took: 0:00:00.000012
DEBUG: Trying rule: switch_lang; took: 0:00:00.000016
DEBUG: Trying rule: systemctl; took: 0:00:00.000012
DEBUG: Trying rule: tmux; took: 0:00:00.000010
DEBUG: Trying rule: touch; took: 0:00:00.000009
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000009
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000008
DEBUG: Trying rule: unknown_command; took: 0:00:00.000096
DEBUG: Trying rule: unsudo; took: 0:00:00.000003
DEBUG: Trying rule: vagrant_up; took: 0:00:00.000013
DEBUG: Trying rule: whois; took: 0:00:00.000011
DEBUG: Trying rule: workon_doesnt_exists; took: 0:00:00.000010
DEBUG: Trying rule: yarn_alias; took: 0:00:00.000012
DEBUG: Trying rule: yarn_command_not_found; took: 0:00:00.000009
DEBUG: Trying rule: yarn_command_replaced; took: 0:00:00.000008
DEBUG: Trying rule: yarn_help; took: 0:00:00.000009
DEBUG: Trying rule: man_no_space; took: 0:00:00.000003
DEBUG: Trying rule: no_command; took: 0:00:00.005490
DEBUG: Total took: 0:00:00.089261
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/thefuck/entrypoints/main.py", line 26, in main
    fix_command(known_args)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/entrypoints/fix_command.py", line 42, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/ui.py", line 71, in select_command
    selector = CommandSelector(corrected_commands)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/ui.py", line 34, in __init__
    self._commands = [next(self._commands_gen)]
  File "/usr/local/lib/python3.6/dist-packages/thefuck/corrector.py", line 60, in organize_commands
    first_command = next(corrected_commands)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/corrector.py", line 91, in <genexpr>
    for corrected in rule.get_corrected_commands(command))
  File "/usr/local/lib/python3.6/dist-packages/thefuck/types.py", line 189, in get_corrected_commands
    new_commands = self.get_new_command(command)
  File "</home/mayukh/.local/lib/python3.6/site-packages/decorator.py:decorator-gen-212>", line 2, in get_new_command
  File "/usr/local/lib/python3.6/dist-packages/thefuck/specific/sudo.py", line 9, in sudo_support
    return fn(command)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/rules/no_command.py", line 27, in get_new_command
    fallback_to_first=False)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/utils.py", line 92, in get_closest
    possibilities = list(possibilities)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/rules/no_command.py", line 16, in _get_used_executables
    for script in get_valid_history_without_current(command):
  File "/usr/local/lib/python3.6/dist-packages/thefuck/utils.py", line 34, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/utils.py", line 315, in get_valid_history_without_current
    history = shell.get_history()
  File "/usr/local/lib/python3.6/dist-packages/thefuck/utils.py", line 34, in wrapper
    memo[key] = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/thefuck/shells/generic.py", line 54, in get_history
    return list(self._get_history_lines())
  File "/usr/local/lib/python3.6/dist-packages/thefuck/shells/generic.py", line 61, in _get_history_lines
    encoding='utf-8', errors='ignore') as history_file:
PermissionError: [Errno 13] Permission denied: '/home/mayukh/.bash_history'
```

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

The app refuses to work at all citing that access to bash_history is denied. Upon running the command with sudo i.e. `sudo fuck`, I get the following:
```
Seems like fuck alias already configured!
For applying changes run source ~/.bashrc or restart your shell.
```

**Comment by angelod1as** [comment]
@mayukhnair the issue might not be with thefuck itself, but with zsh permissions.

I solved this by running: `sudo chmod 755 /Users/angelo/.zsh_history` (of course change `angelo` for your user.
