### ISSUE TITLE
Breaks after composer require when there is only one suggested package

### ISSUE THREAD

**Issue by zakini** [nvbn/thefuck#959]
**The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):**
﻿The Fuck 3.29 using Python 3.7.4 and Bash 3.2.57(1)-release

**Your system (Debian 7, ArchLinux, Windows, etc.):**
macOS 10.14.6

**How to reproduce the bug:**
Try to `composer require` something that doesn't exist and for which composer only has one suggestion. For example: `laravel-nova-csv-import`

**The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):**
```
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'instant_mode': False,
 'no_colors': False,
 'num_close_matches': 3,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/Users/josh/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Received output:

  [InvalidArgumentException]
  Could not find package laravel-nova-csv-import.

  Did you mean this?
      simonhamp/laravel-nova-csv-import


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...


DEBUG: Call: composer require laravel-nova-csv-import; with env: {'THEFUCK_DEBUG': 'true', 'TERM_PROGRAM': 'iTerm.app', 'NVM_CD_FLAGS': '', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'TMPDIR': '/var/folders/gp/bttvyvfx7wlb7vvrrq8cjk3h0000gr/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.EVDHqcPRJM/Render', 'TERM_PROGRAM_VERSION': '3.3.4', 'OLDPWD': '/Users/josh', 'TF_SHELL': 'bash', 'TERM_SESSION_ID': 'w0t1p0:0F5F7369-CFF1-4BA1-BA3F-2FCC815A8087', 'TF_HISTORY': '\t fuck\n\t composer rquire\n\t thefuck --version\n\t thefuck --version | pbcopy\n\t composer require lravel\n\t composer require lravel/laravel\n\t composer require lravel/tinker\n\t composer require laravel/tnker\n\t composer require laravel-nova-csv-import\n\t composer require laravel-nova-csv-import', 'TF_ALIAS': 'fuck', 'TF_SHELL_ALIASES': "alias artisan='php artisan'\nalias phpunit='vendor/bin/phpunit'\nalias tinker='artisan tinker'\nalias watch='tail -f -n 0'", 'PYTHONIOENCODING': 'utf-8', 'NVM_DIR': '/Users/josh/.nvm', 'USER': 'josh', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.gmDvk4jN4u/Listeners', '__CF_USER_TEXT_ENCODING': '0x1F8:0x0:0x2', 'PATH': '/Users/josh/.nvm/versions/node/v10.16.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/josh/.composer/vendor/bin', 'PWD': '/Users/josh/Code/ye-accounts', 'LANG': 'C', 'ITERM_PROFILE': 'Default', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'SHLVL': '1', 'HOME': '/Users/josh', 'COLORFGBG': '7;0', 'LC_TERMINAL_VERSION': '3.3.4', 'ITERM_SESSION_ID': 'w0t1p0:0F5F7369-CFF1-4BA1-BA3F-2FCC815A8087', 'LOGNAME': 'josh', 'NVM_BIN': '/Users/josh/.nvm/versions/node/v10.16.3/bin', 'LC_TERMINAL': 'iTerm2', 'SECURITYSESSIONID': '186a9', 'COLORTERM': 'truecolor', '_': '/usr/local/bin/thefuck', 'LC_ALL': 'C', 'GIT_TRACE': '1'}; is slow:  took: 0:00:01.038031
DEBUG: Importing rule: adb_unknown_command; took: 0:00:00.000345
DEBUG: Importing rule: ag_literal; took: 0:00:00.000717
DEBUG: Importing rule: apt_get; took: 0:00:00.001036
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000325
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.000909
DEBUG: Importing rule: apt_list_upgradable; took: 0:00:00.000567
DEBUG: Importing rule: apt_upgrade; took: 0:00:00.000693
DEBUG: Importing rule: aws_cli; took: 0:00:00.001101
DEBUG: Importing rule: az_cli; took: 0:00:00.000369
DEBUG: Importing rule: brew_cask_dependency; took: 0:00:00.000623
DEBUG: Importing rule: brew_install; took: 0:00:00.000181
DEBUG: Importing rule: brew_link; took: 0:00:00.000477
DEBUG: Importing rule: brew_reinstall; took: 0:00:00.000711
DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000323
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000153
DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000363
DEBUG: Importing rule: cargo; took: 0:00:00.000189
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000307
DEBUG: Importing rule: cat_dir; took: 0:00:00.000363
DEBUG: Importing rule: cd_correction; took: 0:00:00.001286
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000425
DEBUG: Importing rule: cd_parent; took: 0:00:00.000115
DEBUG: Importing rule: chmod_x; took: 0:00:00.000126
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000353
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000418
DEBUG: Importing rule: cpp11; took: 0:00:00.000274
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001264
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.001376
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000172
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000187
DEBUG: Importing rule: dnf_no_such_command; took: 0:00:00.000912
DEBUG: Importing rule: docker_login; took: 0:00:00.000383
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000764
DEBUG: Importing rule: dry; took: 0:00:00.000205
DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000427
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000309
DEBUG: Importing rule: fix_file; took: 0:00:00.002201
DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.000614
DEBUG: Importing rule: git_add; took: 0:00:00.000656
DEBUG: Importing rule: git_add_force; took: 0:00:00.000359
DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000539
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000383
DEBUG: Importing rule: git_branch_exists; took: 0:00:00.000514
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000311
DEBUG: Importing rule: git_checkout; took: 0:00:00.000302
DEBUG: Importing rule: git_commit_amend; took: 0:00:00.000274
DEBUG: Importing rule: git_commit_reset; took: 0:00:00.000272
DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000350
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000313
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000284
DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000479
DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000319
DEBUG: Importing rule: git_merge; took: 0:00:00.000308
DEBUG: Importing rule: git_merge_unrelated; took: 0:00:00.000309
DEBUG: Importing rule: git_not_command; took: 0:00:00.000312
DEBUG: Importing rule: git_pull; took: 0:00:00.000341
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000308
DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000307
DEBUG: Importing rule: git_push; took: 0:00:00.000308
DEBUG: Importing rule: git_push_different_branch_names; took: 0:00:00.000341
DEBUG: Importing rule: git_push_force; took: 0:00:00.000334
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000348
DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000409
DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000316
DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000256
DEBUG: Importing rule: git_remote_delete; took: 0:00:00.000366
DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000358
DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000474
DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000301
DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000362
DEBUG: Importing rule: git_stash; took: 0:00:00.000337
DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000381
DEBUG: Importing rule: git_tag_force; took: 0:00:00.000276
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000313
DEBUG: Importing rule: go_run; took: 0:00:00.000294
DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000645
DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000292
DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000533
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000349
DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000538
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000304
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000280
DEBUG: Importing rule: heroku_multiple_apps; took: 0:00:00.000287
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000282
DEBUG: Importing rule: history; took: 0:00:00.000119
DEBUG: Importing rule: hostscli; took: 0:00:00.000428
DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000356
DEBUG: Importing rule: java; took: 0:00:00.000332
DEBUG: Importing rule: javac; took: 0:00:00.000283
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000419
DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000282
DEBUG: Importing rule: ln_s_order; took: 0:00:00.000281
DEBUG: Importing rule: long_form_help; took: 0:00:00.000150
DEBUG: Importing rule: ls_all; took: 0:00:00.000322
DEBUG: Importing rule: ls_lah; took: 0:00:00.000307
DEBUG: Importing rule: man; took: 0:00:00.000322
DEBUG: Importing rule: man_no_space; took: 0:00:00.000132
DEBUG: Importing rule: mercurial; took: 0:00:00.000428
DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000179
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000413
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000339
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000312
DEBUG: Importing rule: no_command; took: 0:00:00.000332
DEBUG: Importing rule: no_such_file; took: 0:00:00.000178
DEBUG: Importing rule: npm_missing_script; took: 0:00:00.000629
DEBUG: Importing rule: npm_run_script; took: 0:00:00.000307
DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000659
DEBUG: Importing rule: open; took: 0:00:00.000513
DEBUG: Importing rule: pacman; took: 0:00:00.000501
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000181
DEBUG: Importing rule: path_from_history; took: 0:00:00.000223
DEBUG: Importing rule: php_s; took: 0:00:00.000346
DEBUG: Importing rule: pip_install; took: 0:00:00.000495
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000441
DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000358
DEBUG: Importing rule: prove_recursively; took: 0:00:00.000352
DEBUG: Importing rule: pyenv_no_such_command; took: 0:00:00.000857
DEBUG: Importing rule: python_command; took: 0:00:00.000427
DEBUG: Importing rule: python_execute; took: 0:00:00.000376
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000121
DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.000493
DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000121
DEBUG: Importing rule: rm_dir; took: 0:00:00.000285
DEBUG: Importing rule: rm_root; took: 0:00:00.000348
DEBUG: Importing rule: scm_correction; took: 0:00:00.000366
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000315
DEBUG: Importing rule: sl_ls; took: 0:00:00.000142
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000363
DEBUG: Importing rule: sudo; took: 0:00:00.000123
DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000284
DEBUG: Importing rule: switch_lang; took: 0:00:00.000166
DEBUG: Importing rule: systemctl; took: 0:00:00.000421
DEBUG: Importing rule: test.py; took: 0:00:00.000114
DEBUG: Importing rule: tmux; took: 0:00:00.000558
DEBUG: Importing rule: touch; took: 0:00:00.000312
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000288
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000287
DEBUG: Importing rule: unknown_command; took: 0:00:00.000120
DEBUG: Importing rule: unsudo; took: 0:00:00.000108
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000286
DEBUG: Importing rule: whois; took: 0:00:00.000437
DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000404
DEBUG: Importing rule: yarn_alias; took: 0:00:00.000285
DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000597
DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000418
DEBUG: Importing rule: yarn_help; took: 0:00:00.000350
DEBUG: Trying rule: path_from_history; took: 0:00:00.000502
DEBUG: Trying rule: dry; took: 0:00:00.000088
DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000064
DEBUG: Trying rule: test.py; took: 0:00:00.000002
DEBUG: Trying rule: adb_unknown_command; took: 0:00:00.000013
DEBUG: Trying rule: ag_literal; took: 0:00:00.000013
DEBUG: Trying rule: aws_cli; took: 0:00:00.000014
DEBUG: Trying rule: az_cli; took: 0:00:00.000024
DEBUG: Trying rule: brew_cask_dependency; took: 0:00:00.000011
DEBUG: Trying rule: brew_install; took: 0:00:00.000002
DEBUG: Trying rule: brew_link; took: 0:00:00.000025
DEBUG: Trying rule: brew_reinstall; took: 0:00:00.000027
DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000010
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000002
DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000011
DEBUG: Trying rule: cargo; took: 0:00:00.000002
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000037
DEBUG: Trying rule: cat_dir; took: 0:00:00.000011
DEBUG: Trying rule: cd_correction; took: 0:00:00.000035
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000010
DEBUG: Trying rule: cd_parent; took: 0:00:00.000002
DEBUG: Trying rule: chmod_x; took: 0:00:00.000002
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000016
DEBUG: Total took: 0:00:01.132401
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 13, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/entrypoints/main.py", line 26, in main
    fix_command(known_args)
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/entrypoints/fix_command.py", line 42, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/ui.py", line 71, in select_command
    selector = CommandSelector(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/ui.py", line 34, in __init__
    self._commands = [next(self._commands_gen)]
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/corrector.py", line 60, in organize_commands
    first_command = next(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/corrector.py", line 91, in <genexpr>
    for corrected in rule.get_corrected_commands(command))
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/types.py", line 189, in get_corrected_commands
    new_commands = self.get_new_command(command)
  File "/usr/local/Cellar/thefuck/3.29/libexec/lib/python3.7/site-packages/thefuck/rules/composer_not_command.py", line 12, in get_new_command
    broken_cmd = re.findall(r"Command \"([^']*)\" is not defined", command.output)[0]
IndexError: list index out of range
```

**If the bug only appears with a specific application, the output of that application and its version:**
`composer -V` outputs: Composer version 1.9.0 2019-08-02 20:55:32
`composer require laravel-nova-csv-import` outputs:
> [InvalidArgumentException]
> Could not find package laravel-nova-csv-import.
> 
> Did you mean this?
>     simonhamp/laravel-nova-csv-import

**Anything else you think is relevant:**
Seems like `composer_not_command` is incorrectly matching on this output. Also, maybe there should be a rule for when composer can't find the package you asked for?

**Comment by chesnutcase** [comment]
Interesting, I can pick up this feature and add a PR this week. But what do you expect `thefuck` to do if `composer` suggests more than one package?

For instance, `composer require potato` will result in the following output:

```
  [InvalidArgumentException]      
  Could not find package potato.  
                                  
  Did you mean one of these?      
      drteam/potato               
      florence/potato             
      kola/potato-orm             
      vundi/potato-orm            
      jsyqw/potato-bot 
```

**Comment by Zakini** [comment]
I guess it should suggest `composer require drteam/potato`, then pressing up/down would suggest the other packages?

**Comment by chesnutcase** [comment]
i've opened a pull request that contains my attempt at fixing this issues, and adds some cool integration with composer. hope it passes!
